### ISSUE TITLE
WAFS needs its own UPP branch for WAFS separation from GFS

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/UPP#1000]
The separation starts from GFS v16.3 which is using upp_v8.3.0.

@WenMeng-NOAA May a branch release/wafs_v7 be created? After that, I need to add a few levels to WAFS control file.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA I created the branch "release/wafs_v7" based on "release/gfs_v16" for wafs v7 implementation.
