### ISSUE TITLE
New UPP branch for MPAS-related development?

### ISSUE THREAD

**Issue by jaymes-kenyon** [NOAA-EMC/UPP#1008]
GSL staff are beginning to modify UPP codes to support MPAS runs.  For now, the "INITPOST.F" interface is being used, since the netCDF array names (from MPASSIT) are largely identical to those in HRRR (WRF-ARW).

The first UPP PRs for MPAS work will likely be ready in the days ahead.  @HuiyaChuang-NOAA suggested that a new UPP branch may be helpful for this code development.

**Comment by WenMeng-NOAA** [comment]
@jaymes-kenyon From the UPP code management perspective, we reserve the interface "INITPOST.F" for ops. HRRR/RAP in the UPP develop branch. I would suggest renaming your interface "INITPOST.F" (e.g. INITPOST_MPAS.F). You may submit this MPAS PR to the develop branch, as it is intended for the future implementation. We will retire the legacy interfaces once the replacements have been  implemented for operations.
