### ISSUE TITLE
Update UPP with spack-stack 1.8.0

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#1020]
According to EIB, spack-stack 1.8.0 will be released and installed soon.  The ufs-weather-model side will update modulefiles with the spack-stack 1.8.0, the same updates should be implemented in the UPP develop branch.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Could the PEIC work on this issue and coordinate with ufs-weather-model code manager to bundle the corresponding upp harsh in the UFS PR for spack-stack 1.8.0 update? Thanks!

**Comment by FernandoAndrade-NOAA** [comment]
Adding a note here that this issue now includes an update to CRTMv3 as well.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA @gspetro-NOAA Could you start working on the updates in UPP and combine the corresponding upp submodule update in the ufs-weather-model PR #[2453](https://github.com/ufs-community/ufs-weather-model/pull/2453)?

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA @gspetro-NOAA Could you start working on the updates in UPP and combine the corresponding upp submodule update in the ufs-weather-model PR #[2453](https://github.com/ufs-community/ufs-weather-model/pull/2453)?

I've opened a draft PR in UPP, but testing will be on hold until an env with CRTMv3 is set up for spack-stack 1.8.0

**Comment by FernandoAndrade-NOAA** [comment]
Leaving a note that CRTMv3 will be split off into a separate issue.

**Comment by DavidHuber-NOAA** [comment]
Is there a follow-up issue to upgrade to CRTMv3?
