### ISSUE TITLE
ip 5/5.1

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/UPP#1063]
Just as a headsup, the sp library is deprecated and its functionality is now under ip 5.0 (present in spack-stack-1.8.0; #983). Moving to ip 5.0 should be fairly straightforward, and involves removing/replacing `find_package(sp)` and `target_link_libraries(sp:sp_*)`. For ip 5.1, which will hopefully be in spack-stack-1.9.0, the sp functionality is in a module and therefore must be accessed through `use sp_mod`.

**Comment by FernandoAndrade-NOAA** [comment]
@AlexanderRichert-NOAA would you like to introduce your proposed updates to my #1062, or would you prefer a separate PR? This seems like a related update to link to the PR.

**Comment by AlexanderRichert-NOAA** [comment]
Sure, I'll try adding it to #1062.

**Comment by FernandoAndrade-NOAA** [comment]
I've added you as fork collaborator, so there should hopefully be no issues making updates to the PR branch.

**Comment by AlexanderRichert-NOAA** [comment]
Sounds good, thanks.
