### ISSUE TITLE
Update UPP interface with GTG4 to use instantaneous fluxes

### ISSUE THREAD

**Issue by HuiyaChuang-NOAA** [NOAA-EMC/UPP#1073]
UPP interface with GTG currently uses **time-averaged** sensible and latent heat fluxes most likely because GFS used to only output
time-averaged fluxes.  During recent exercise to validate UPP GTG4 using HRRR output, it was discovered **instantaneous fluxes** are used for producing GTG for HRRR. 

 **NCAR decided they want to use instantaneous fluxes for all models.**  

@hsinmulin-NOAA already updated his local version of UPP code and make comparison plots using HRRR output.  He will attach plots.
@YaliMao-NOAA will make and attach comparison plots for her GFS benchmark case.

**Comment by YaliMao-NOAA** [comment]
WAFS(GFS) GTG difference when switching from time-averaged flux to instantaneous flux:
[wafs gtg diff_flux.pptx](https://github.com/user-attachments/files/17510513/wafs.gtg.diff_flux.pptx)
As shown in the plots, the lower vertical level, the bigger difference.
There is no difference when pressure level is 410hPa and above, which is not plotted.

**Comment by hsinmulin-NOAA** [comment]
From the RRFS sensitivity test, the impact from the difference (new-org) plot show little to none from bottom (L1) to top.
 
plots (2024071812 fcst=06) of individual and the difference

new ([CATEDR](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_CATEDR-2024071812.f06.plots-new/)  [CITEDR](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_CITEDR-2024071812.f06.plots-new/)  [EPDARM](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_EDPARM-2024071812.f06.plots-new/)  [MWTURB](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_MWTURB-2024071812.f06.plots-new/)  [MXEDPRM](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_MXEDPRM-2024071812.f06.plots-new/))
org ([CATEDR](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_CATEDR-2024071812.f06.plots-org/)  [CITEDR](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_CITEDR-2024071812.f06.plots-org/)  [EPDARM](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_EDPARM-2024071812.f06.plots-org/)  [MWTURB](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_MWTURB-2024071812.f06.plots-org/)  [MXEDPRM](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_MXEDPRM-2024071812.f06.plots-org/))
diff (new-org) ([CATEDR](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_CATEDR-diff-2024071812.f06.plots/)  [CITEDR](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_CITEDR-diff-2024071812.f06.plots/)  [EPDARM](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_EDPARM-diff-2024071812.f06.plots/)  [MWTURB](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_MWTURB-diff-2024071812.f06.plots/)  [MXEDPRM](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_MXEDPRM-diff-2024071812.f06.plots/))

The best way is to see the diff animation
diff (new-org) ([CATEDR](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_CATEDR-diff-2024071812.f06.plots/conus3km_CATEDR_diff-2024071812.f06.gif)  [CITEDR](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_CITEDR-diff-2024071812.f06.plots/conus3km_CITEDR_diff-2024071812.f06.gif) [ EPDARM](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_EDPARM-diff-2024071812.f06.plots/conus3km_EDPARM_diff-2024071812.f06.gif)  [MWTURB](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_MWTURB-diff-2024071812.f06.plots/conus3km_MWTURB_diff-2024071812.f06.gif)  [MXEDPRM](https://www.emc.ncep.noaa.gov/mmb/wd20hl/CIRA/aviation/HRRR/GTG/HRRR-conus3km_MXEDPRM-diff-2024071812.f06.plots/conus3km_MXEDPRM_diff-L01-2024071812.f06.png))

the difference is small and mostly at the few lower levels
