### ISSUE TITLE
New GEFS products needed for AI/ML applications

### ISSUE THREAD

**Issue by EricSinsky-NOAA** [NOAA-EMC/UPP#1086]
The following variables need to be added to GEFS for PSL's AI/ML applications:

- [x] ugrd: 125hPa, 175hPa, 775hPa, 825hPa, 875hPa
- [x] vgrid: 125hPa, 175hPa, 775hPa, 825hPa, 875hPa
- [x] tmp: 125hPa, 175hPa, 225hPa, 775hPa, 825hPa, 875hPa
- [x] hgt: 125hPa, 175hPa, 775hPa, 825hPa, 875hPa
- [x] spfh: 125hPa, 175hPa, 225hPa, 775hPa, 825hPa, 875hPa
- [x] dzdt: 125hPa, 175hPa, 225hPa, 775hPa, 825hPa, 875hPa

**Comment by yangfanglin** [comment]
Eric,  I assume outputs on the "standard" pressure levels, for instance, 850, 800, 750hPa ..., have already been included.  These are additional output specifically for meeting PSL's request for ML/AL app

**Comment by EricSinsky-NOAA** [comment]
@yangfanglin Yes, that is correct.

**Comment by WenMeng-NOAA** [comment]
@EricSinsky-NOAA Would you like to combine the changes in your PR #1085?

**Comment by EricSinsky-NOAA** [comment]
> @EricSinsky-NOAA Would you like to combine the changes in your PR #1085?

@WenMeng-NOAA If permitted, yes. This issue can be addressed in PR #1085 too.

**Comment by WenMeng-NOAA** [comment]
> > @EricSinsky-NOAA Would you like to combine the changes in your PR #1085?
> 
> @WenMeng-NOAA If permitted, yes. This issue can be addressed in PR #1085 too.

@EricSinsky-NOAA Yes, please do it.
