### ISSUE TITLE
MPAS applications: fix / add several aviation fields, remove "if imp_physics..." logic from INITPOST_MPAS

### ISSUE THREAD

**Issue by jaymes-kenyon** [NOAA-EMC/UPP#1087]
A forthcoming PR will do the following for MPAS-related applications:

- For VIL, discontinue use of the local GRIB2 table
- Add GSL's experimental ceiling fields to the GRIB2 output
- Within "INITPOST_MPAS", remove instances of "if imp_physics...".  These portions of the code initialize various arrays based upon the microphysics scheme.  However, many of these "imp_physics" identifiers correspond to schemes in WRF-ARW.  If they are again needed for MPAS, these codes can be re-introduced.

This issue can be assigned to @jaymes-kenyon

**Comment by gspetro-NOAA** [comment]
Completed by PR #1088
