### ISSUE TITLE
Transition the updated U Utah SLR algorithm to UPP

### ISSUE THREAD

**Issue by JesseMeng-NOAA** [NOAA-EMC/UPP#1101]
U Utah has updated the snow-liquid-ration (SLR) algorithm trained with data across CONUS (including west and east). The new algorithm will be transitioned to UPP.

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA Please submit the PR to the 'release/rrfs_v1' branch for RRFS v1 update.

**Comment by JesseMeng-NOAA** [comment]
PR submitted to the develop branch.
https://github.com/NOAA-EMC/UPP/pull/1104

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA If you have any scientific evaluation results for U UTA2 scheme, please include them in this issue.

**Comment by JesseMeng-NOAA** [comment]
> @JesseMeng-NOAA If you have any scientific evaluation results for U UTA2 scheme, please include them in this issue.

https://docs.google.com/presentation/d/1MiVLbq76a2RfWTBv-A0KIqpyOl6Ef9zgtw45kV3Bc8Y/edit?usp=sharing
