### ISSUE TITLE
UPP runs slow on HERA -- staskfarm and multi-prog options 

### ISSUE THREAD

**Issue by yangfanglin** [NOAA-EMC/UPP#118]
UPP runs slow on HERA because "srun" does not support MPMD or CFP.   Wen Meng suggested to use staskfarm, which is equivalent to MPMD/CFP.  Offline tests showed staskfarm appears to be working. However, there are two issues.  First, it always creates a directory .taskfarm_job_$LSF_JOB_ID under the running directory, it contains many small job scripts to be run on each task.  $LSF_JOB_ID is uniquely determined by the system and cannot be changed by users.  fv3gfs_downstream_nems.sh has nset=2, and submits staskfarm twice.  In the 2nd submission, jobs that have been run when nset=1 are catted to the same small job scripts and are executed one more time.  I have not been able to found a solution to overcome this without restructuring the UPP script.  Secondly, when staskfarm is submitted from the global-workflow by the Rocoto job scheduler, the program always fails with "slurmstepd: error: execve(): : No such file or directory".   It appears environmental variables are not properly broadcasted to each task.  I searched the internet and tested various options to load the modules at different locations,  but could not find a solution.

**Comment by yangfanglin** [comment]
I then noticed "srun" has this --multi-prog option that can send multiple jobs to different PEs.  I have updated fv3gfs_downstream_nems.sh to use this function.  It works great, producing UPP products within 1-2 minutes for each forecast hour (without the GOES Images). Here are the changes

diff --git a/ush/fv3gfs_downstream_nems.sh b/ush/fv3gfs_downstream_nems.sh
index fa4fc3e..eb06859 100755
--- a/ush/fv3gfs_downstream_nems.sh
+++ b/ush/fv3gfs_downstream_nems.sh
@@ -99,7 +99,7 @@ fi
 
 #-----------------------------------------------------
 #-----------------------------------------------------
-if [ $machine = WCOSS -o $machine = WCOSS_C -o $machine = WCOSS_DELL_P3 ]; then
+if [ $machine = WCOSS -o $machine = WCOSS_C -o $machine = WCOSS_DELL_P3 -o $machine = HERA ]; then
 #-----------------------------------------------------
 #-----------------------------------------------------
 export nset=1
@@ -173,6 +173,15 @@ date
   launcher=${APRUN_DWN:-"aprun -j 1 -n 24 -N 24 -d 1 cfp"}
   if [ $machine = WCOSS_C -o $machine = WCOSS_DELL_P3 ] ; then
      $launcher $MP_CMDFILE
+  elif [ $machine = HERA ] ; then
+     if [ -s $DATA/poescript_srun ]; then rm -f $DATA/poescript_srun; fi
+     touch $DATA/poescript_srun
+     nm=0
+     cat $DATA/poescript | while read line; do
+         echo "$nm  $line" >> $DATA/poescript_srun 
+         nm=$((nm+1))
+     done
+     ${launcher:-"srun --export=ALL"}  -n $nm --multi-prog $DATA/poescript_srun
   else
      $launcher
   fi


Wen, please test  the updated script (Hera /scratch1/NCEPDEV/global/Fanglin.Yang/save/git/gfsv16b_retro1/sorc/gfs_post.fd/ush/fv3gfs_downstream_nems.sh), and see if it can be included in the UPP repository.

**Comment by WenMeng-NOAA** [comment]
@yangfanglin Your change look good for me with the UPP standalone test. I combine it with the UPP 
PR #117 at https://github.com/NOAA-EMC/EMC_post/pull/117. Please review.

**Comment by WenMeng-NOAA** [comment]
The changes were integrated in develop commit @d59cabf. Close the issue.
