### ISSUE TITLE
Adding a line to fixed the bug of scattering calculation 

### ISSUE THREAD

**Issue by zhanglikate** [NOAA-EMC/UPP#120]
Change line " IF (IDECID == 17 ) THEN" as
"IF (IDECID == 17 .or. IDECID == 20 .or. IDECID == 21) THEN"

**Comment by WenMeng-NOAA** [comment]
Kate's change was submitted at the PR #121 at
https://github.com/NOAA-EMC/EMC_post/pull/121

**Comment by zhanglikate** [comment]
Your change is not correct. You should update the red part, you missed the middle one. Thanks very much for your help.

Change line " IF (IDECID == 17 ) THEN” as "IF (IDECID == 17 .or. IDECID == 20 .or. IDECID == 21) THEN”. 

Thanks.

Kate

**Comment by WenMeng-NOAA** [comment]
Kate,

You are right. The new change was added in the PR #122.

**Comment by WenMeng-NOAA** [comment]
The branch gefs_v12_release was committed at @0baf6bf with the bug fix of scattering calculation.

**Comment by WenMeng-NOAA** [comment]
On 11/06/2020, this fix was synced in branch develop with PR #217 at 43ba912.
