### ISSUE TITLE
include install directory destination is incorrect in cmake.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/UPP#129]
`module_dir` variable for Fortran module files in [L189](https://github.com/NOAA-EMC/EMC_post/blob/564e26f550d5b444a885286fe6e648249021ed04/sorc/ncep_post.fd/CMakeLists.txt#L189) is  defined as:
```
set(module_dir "${CMAKE_CURRENT_BINARY_DIR}/include")
```

During install, these files are copied into the destination `include` as seen in [L221](
https://github.com/NOAA-EMC/EMC_post/blob/564e26f550d5b444a885286fe6e648249021ed04/sorc/ncep_post.fd/CMakeLists.txt#L221) reproduced here as:
```
install(DIRECTORY ${module_dir} DESTINATION include)
```

This means that the final installation directory containing these Fortran module files is:
```
${CMAKE_INSTALL_PREFIX}/include/include
```

The correct [L221](https://github.com/NOAA-EMC/EMC_post/blob/564e26f550d5b444a885286fe6e648249021ed04/sorc/ncep_post.fd/CMakeLists.txt#L221) should be
```
install(DIRECTORY ${module_dir} DESTINATION ${CMAKE_INSTALL_PREFIX})
```

**Comment by WenMeng-NOAA** [comment]
The PR #130 was merged in release/public-v1 at @87f9840 on 05/26/2020.
