### ISSUE TITLE
Merge DTC_post  into develop

### ISSUE THREAD

**Issue by fossell** [NOAA-EMC/UPP#133]
A major sync of the DTC community branch into the develop branch was performed.  This includes merging in the community build structure into the develop branch, allowing for smoother code management and development procedures between community and operations moving forward.  

PR #131 details the merge.

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests are conducted on Dell, Cray and Hera. No changed results are found.
The PR is merged to branch develop at @34c7a61 on 06/09/2020.
