### ISSUE TITLE
Build fails on Jet due to removal of /lfs3 soft links for NCEP libraries

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [NOAA-EMC/UPP#134]

**Comment by WenMeng-NOAA** [comment]
I have been starting this work and will keep you updated.

**Comment by JeffBeck-NOAA** [comment]
Thanks, Wen!

- Jeff

**Comment by WenMeng-NOAA** [comment]
@JeffBeck-NOAA Can you test the branch post_jet on my UPP fork at
https://github.com/WenMeng-NOAA/EMC_post/

Beside updating lfs4, I also upgrade netcdf library with parallel_netcdf. You may change your runtime module with:
module load hdf5_parallel/1.10.6
module load netcdf_parallel/4.7.4

**Comment by JeffBeck-NOAA** [comment]
@WenMeng-NOAA Branch post_jet in your fork compiles successfully on Jet.  Thank you!  Feel free to tag me on the PR and I will be happy to approve it.

I am in the process of modifying the FV3-SAR community workflow to directly source all module files from the build repository to use at run time, so this change will be automatically incorporated when the workflow checks out EMC_post in the future.

Thanks again!

**Comment by WenMeng-NOAA** [comment]
The PR #135 was merged to the branch develop at @a30924d.
