### ISSUE TITLE
Syntax error in MDL2STD_P.f

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/UPP#152]
```
/home/dusan/simple-ufs/src/post/sorc/ncep_post.fd/MDL2STD_P.f:254:68:                                     

  254 |             QIN(1:IM,JSTA:JEND,1:LM,nFDS)=QQW(1:IM,JSTA:JEND,1:LM)+ \
      |                                                                    1
Error: Syntax error in expression at (1)
```
Backslash is not standard Fortran line continuation character. Please use ampersand.

https://github.com/NOAA-EMC/EMC_post/blob/427fa51fbf42ce92d47d53b890c1865f4f296b33/sorc/ncep_post.fd/MDL2STD_P.f#L254

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Thanks for catching this bug. Can you submit a PR so I can proceed merging in develop.

**Comment by DusanJovic-NOAA** [comment]
See: https://github.com/NOAA-EMC/EMC_post/pull/153
