### ISSUE TITLE
FV3 LAM low/mid/high/total clouds in fv3sar.xml

### ISSUE THREAD

**Issue by hertneky** [NOAA-EMC/UPP#171]
The fv3sar.xml has ID's 037-039 for outputting inst low/mid/high clouds for FV3 LAM, in which post computes from the 3D cloud field. Post uses the following layers:

Low: ≥ 642 hPa
Mid: ≥ 350 hPa
High: <350 hPa

However, FV3 computes ave low/mid/high clouds using different layers. These can be output directly using ID's 300-302.

Low: ≥ 650 hPa
Mid: ≥ 400 hPa
High: <400 hPa

@WenMeng-NOAA, @JeffBeck-NOAA (or other SAR folks - feel free to tag) - I feel the preferred fields would be the direct model output, especially since the levels used are different. Same goes for total which is also directly output from model. Is there a reason the direct model output for these fields aren't being output? Also, does the 'ave' in the model output refer to time- or layer-average (more of a question for LAM folks).

**Comment by WenMeng-NOAA** [comment]
@hertneky  Thanks for bringing this issue. 
In UPP,  IDs 037-039 are instantaneous low/mid/hi cloud fraction.  IDs 300-302 are time averaged low/mid/hi cloud fraction. 
I would invite @ericaligo-NOAA to comment the inconsistency between instant  and time averaged cloud fraction for processing regional FV3.

**Comment by ericaligo-NOAA** [comment]
That's correct.  Fields 037-039 are the instantaneous cloud fractions 
based  off of cfr, which is the new cldfra array (instantaneous cloud 
fractions) passed in from the LAM.

!-- Initialize low, middle, high, and total cloud cover;
!   also a method for cloud ceiling height
!
         DO J=JSTA,JEND
           DO I=1,IM
             CFRACL(I,J)=0.
             CFRACM(I,J)=0.
             CFRACH(I,J)=0.
             TCLD(I,J)=0.
           ENDDO
         ENDDO
         DO L=LM,1,-1
           DO J=JSTA,JEND
             DO I=1,IM
               FRAC=CFR(I,J,L) !- 3D cloud fraction at model layers
               PCLDBASE=PMID(I,J,L)    !-- Using PCLDBASE variable for 
convenience
               IF (PCLDBASE>=PTOP_LOW) THEN
                 CFRACL(I,J)=MAX(CFRACL(I,J),FRAC)
               ELSE IF (PCLDBASE>=PTOP_MID) THEN
                 CFRACM(I,J)=MAX(CFRACM(I,J),FRAC)
               ELSE
                 CFRACH(I,J)=MAX(CFRACH(I,J),FRAC)
               ENDIF
               TCLD(I,J)=MAX(TCLD(I,J),FRAC)

!     LOW CLOUD FRACTION.
       IF (IGET(037) > 0) THEN
!$omp parallel do private(i,j)
         DO J=JSTA,JEND
           DO I=1,IM
             IF(CFRACL(I,J) < SPVAL) then
               GRID1(I,J) = CFRACL(I,J)*100.
             else
               GRID1(I,J) = spval
             endif
           ENDDO
         ENDDO
        if(grib=="grib1" )then
         ID(1:25)=0
         CALL GRIBIT(IGET(037),LVLS(1,IGET(037)),GRID1,IM,JM)

!     MIDDLE CLOUD FRACTION.
       IF (IGET(038) > 0) THEN
!       GRID1=SPVAL
!$omp parallel do private(i,j)
         DO J=JSTA,JEND
           DO I=1,IM
             IF(CFRACM(I,J) < SPVAL) then
               GRID1(I,J) = CFRACM(I,J)*100.
             else
               GRID1(I,J) = spval
             endif
           ENDDO
         ENDDO
        if(grib=="grib1" )then
         ID(1:25)=0
         CALL GRIBIT(IGET(038),LVLS(1,IGET(038)),GRID1,IM,JM)

!
!     HIGH CLOUD FRACTION.
       IF (IGET(039).GT.0) THEN
!       GRID1=SPVAL
!$omp parallel do private(i,j)
         DO J=JSTA,JEND
           DO I=1,IM
             IF(CFRACH(I,J) < SPVAL) then
               GRID1(I,J) = CFRACH(I,J)*100.
             else
               GRID1(I,J) = spval
             endif
           ENDDO
         ENDDO
        if(grib=="grib1" )then
         ID(1:25)=0
         CALL GRIBIT(IGET(039),LVLS(1,IGET(039)),GRID1,IM,JM)

**Comment by hertneky** [comment]
Thanks @WenMeng-NOAA and @ericaligo-NOAA for confirming the FV3 LAM direct l/m/h output is time-averaged. I think the main question was regarding which was more appropriate for including in the default fv3sar.xml, especially since post and fv3 compute the layers differently (use different levels) and using the post algorithm will produce different results than the direct model output and could raise questions.

**Comment by ericaligo-NOAA** [comment]
Wen, we want to make sure the instantaneous cloud fractions are output, 
not the time averaged ones.

**Comment by WenMeng-NOAA** [comment]
@ericaligo-NOAA That's correct. If you look into fv3sar.xml for fv3 lAM implementation, FV3 LAM only output instant low/mid/high cloud fraction,

**Comment by ericaligo-NOAA** [comment]
Sounds good!

**Comment by hertneky** [comment]
Thanks for the confirmation on this
