### ISSUE TITLE
Check integrity of UPP control file for GFS

### ISSUE THREAD

**Issue by JesseMeng-NOAA** [NOAA-EMC/UPP#184]
Update the GFS post control xml files to ensure enough packing precision.

Background of this issue is described in 
https://docs.google.com/document/d/18GaSoq2ZSfo_WM8PPBHgQPfCJEQ9xl6Z9lTfWU-ivjg/edit?usp=sharing

A Github branch is created for this modification
https://github.com/JesseMeng-NOAA/EMC_post/tree/gfs_v16_precision

The change is summarized in
https://docs.google.com/document/d/1ulFox0KMvasvr6PyhY4Vlo4BtWZ8AAightzC1RVNF-o/edit?usp=sharing

Sample plots demonstrating the changes can be viewed in 
https://www.emc.ncep.noaa.gov/mmb/gldas/gfsv16_precision

**Comment by WenMeng-NOAA** [comment]
The GFS V16 product change request can be reviewed at [here](https://docs.google.com/presentation/d/1y0Ew-1yPuBA3tuNU3Hf0i2bsxbnrM1ukHE86I8H9q9o/edit#slide=id.p).

**Comment by WenMeng-NOAA** [comment]
The regression test for GFS V16 was conducted on WCOSS Dell. 
The changed fields are:
-------------------------------------
master file --
:SPFH:3 mb:rpn_corr=0.999999:rpn_rms=3.22313e-09
126:300778093:TMP:5 mb:rpn_corr=0.999996:rpn_rms=0.0291623
128:304258710:SPFH:5 mb:rpn_corr=0.999999:rpn_rms=3.13584e-09
136:328927524:TMP:7 mb:rpn_corr=0.999995:rpn_rms=0.0291623
138:332050887:SPFH:7 mb:rpn_corr=0.999999:rpn_rms=3.25396e-09
146:355737402:TMP:10 mb:rpn_corr=0.999994:rpn_rms=0.0291434
148:358952890:SPFH:10 mb:rpn_corr=0.999999:rpn_rms=2.98761e-09
156:384526374:TMP:15 mb:rpn_corr=0.999994:rpn_rms=0.0291651
158:388083216:SPFH:15 mb:rpn_corr=0.999999:rpn_rms=3.23727e-09
166:414669843:TMP:20 mb:rpn_corr=0.999993:rpn_rms=0.0291543
168:418358733:SPFH:20 mb:rpn_corr=0.999999:rpn_rms=3.16458e-09
176:445808547:TMP:30 mb:rpn_corr=0.999993:rpn_rms=0.0291599
178:449600074:SPFH:30 mb:rpn_corr=0.999999:rpn_rms=3.20956e-09
186:476142877:TMP:40 mb:rpn_corr=0.999994:rpn_rms=0.0291577
196:507106066:TMP:50 mb:rpn_corr=0.999995:rpn_rms=0.0291462
198:511303613:TCDC:50 mb:rpn_corr=0.999946:rpn_rms=0.000227915
212:540868839:TMP:70 mb:rpn_corr=0.999997:rpn_rms=0.0291414
214:545755490:TCDC:70 mb:rpn_corr=0.999713:rpn_rms=0.0442202
224:567170977:SNMR:70 mb:rpn_corr=0.99994:rpn_rms=8.45889e-10
225:567171458:GRLE:70 mb:rpn_corr=0.999967:rpn_rms=8.77393e-10
228:576878417:TMP:100 mb:rpn_corr=0.999997:rpn_rms=0.0291524
230:582129043:TCDC:100 mb:rpn_corr=0.999957:rpn_rms=0.124949
240:603438825:SNMR:100 mb:rpn_corr=0.999996:rpn_rms=5.75335e-09
241:603443398:GRLE:100 mb:rpn_corr=0.999982:rpn_rms=3.52421e-08
244:612613453:TMP:125 mb:rpn_corr=0.999996:rpn_rms=0.0291619
246:618119475:TCDC:125 mb:rpn_corr=0.999985:rpn_rms=0.101369
247:618890458:SPFH:125 mb:rpn_corr=0.999997:rpn_rms=3.19051e-09
256:638584777:SNMR:125 mb:rpn_corr=0.999998:rpn_rms=9.60927e-09
257:638598309:GRLE:125 mb:rpn_corr=0.999991:rpn_rms=5.53561e-08
260:647388066:TMP:150 mb:rpn_corr=0.999994:rpn_rms=0.0291691
262:652991203:TCDC:150 mb:rpn_corr=0.999987:rpn_rms=0.104709
272:674841163:SNMR:150 mb:rpn_corr=0.999874:rpn_rms=1.03147e-07
273:674890263:GRLE:150 mb:rpn_corr=0.999993:rpn_rms=7.08761e-08
276:683453428:TMP:175 mb:rpn_corr=0.99999:rpn_rms=0.0291607
278:689334800:TCDC:175 mb:rpn_corr=0.999992:rpn_rms=0.098619
279:690226348:SPFH:175 mb:rpn_corr=0.999995:rpn_rms=3.18271e-08
288:710454012:SNMR:175 mb:rpn_corr=0.999693:rpn_rms=2.07827e-07
289:710558975:GRLE:175 mb:rpn_corr=0.999994:rpn_rms=7.92774e-08
292:719088042:TMP:200 mb:rpn_corr=0.999988:rpn_rms=0.0291527
294:725141813:TCDC:200 mb:rpn_corr=0.999988:rpn_rms=0.127568
295:726336631:SPFH:200 mb:rpn_corr=0.999999:rpn_rms=3.02147e-08
304:747309435:SNMR:200 mb:rpn_corr=0.999461:rpn_rms=3.40233e-07
305:747511658:GRLE:200 mb:rpn_corr=0.999994:rpn_rms=8.87452e-08
308:755792017:TMP:225 mb:rpn_corr=0.999989:rpn_rms=0.0291531
310:761970490:TCDC:225 mb:rpn_corr=0.99999:rpn_rms=0.125418
317:783798884:CLMR:225 mb:rpn_corr=0.999999:rpn_rms=2.92297e-10
320:784865785:SNMR:225 mb:rpn_corr=0.999479:rpn_rms=4.1277e-07
321:785122804:GRLE:225 mb:rpn_corr=0.999994:rpn_rms=9.85468e-08
324:793263869:TMP:250 mb:rpn_corr=0.999992:rpn_rms=0.0291548
326:799607194:TCDC:250 mb:rpn_corr=0.999989:rpn_rms=0.131964
336:823038114:SNMR:250 mb:rpn_corr=0.999614:rpn_rms=4.38864e-07
337:823346524:GRLE:250 mb:rpn_corr=0.999688:rpn_rms=7.84879e-07
340:832772733:TMP:275 mb:rpn_corr=0.999994:rpn_rms=0.0291527
342:839190693:TCDC:275 mb:rpn_corr=0.999989:rpn_rms=0.136411
343:840860733:SPFH:275 mb:rpn_corr=0.999998:rpn_rms=2.89508e-07
352:863442543:SNMR:275 mb:rpn_corr=0.999728:rpn_rms=4.52699e-07
353:863804431:GRLE:275 mb:rpn_corr=0.999675:rpn_rms=8.62274e-07
356:873145141:TMP:300 mb:rpn_corr=0.999996:rpn_rms=0.0291445
358:879669809:TCDC:300 mb:rpn_corr=0.999991:rpn_rms=0.131848
359:881379850:SPFH:300 mb:rpn_corr=0.999999:rpn_rms=2.88956e-07
368:904492140:SNMR:300 mb:rpn_corr=0.999806:rpn_rms=4.62082e-07
369:904884321:GRLE:300 mb:rpn_corr=0.999657:rpn_rms=9.40262e-07
372:914770733:TMP:325 mb:rpn_corr=0.999996:rpn_rms=0.0291556
374:921112833:TCDC:325 mb:rpn_corr=0.99999:rpn_rms=0.135037
383:945763598:RWMR:325 mb:rpn_corr=0.999999:rpn_rms=7.77325e-13
384:945764082:SNMR:325 mb:rpn_corr=0.999852:rpn_rms=4.74822e-07
385:946204224:GRLE:325 mb:rpn_corr=0.99964:rpn_rms=1.01282e-06
388:956029326:TMP:350 mb:rpn_corr=0.999997:rpn_rms=0.0291501
390:962224759:TCDC:350 mb:rpn_corr=0.99999:rpn_rms=0.132211
399:986897201:RWMR:350 mb:rpn_corr=0.999988:rpn_rms=2.31595e-11
400:986898995:SNMR:350 mb:rpn_corr=0.99988:rpn_rms=4.9293e-07
401:987377936:GRLE:350 mb:rpn_corr=0.999616:rpn_rms=1.09149e-06
404:997102879:TMP:375 mb:rpn_corr=0.999997:rpn_rms=0.0291499
406:1003277571:TCDC:375 mb:rpn_corr=0.999991:rpn_rms=0.128031
415:1028227819:RWMR:375 mb:rpn_corr=0.999998:rpn_rms=3.21024e-11
416:1028230503:SNMR:375 mb:rpn_corr=0.999897:rpn_rms=5.11648e-07
417:1028734624:GRLE:375 mb:rpn_corr=0.999597:rpn_rms=1.1641e-06
420:1038318454:TMP:400 mb:rpn_corr=0.999997:rpn_rms=0.0291553
422:1044342779:TCDC:400 mb:rpn_corr=0.999991:rpn_rms=0.126215
429:1068320902:CLMR:400 mb:rpn_corr=0.999998:rpn_rms=8.79819e-09
431:1069948158:RWMR:400 mb:rpn_corr=0.999824:rpn_rms=4.10784e-10
432:1069952332:SNMR:400 mb:rpn_corr=0.999906:rpn_rms=5.34903e-07
433:1070494961:GRLE:400 mb:rpn_corr=0.999988:rpn_rms=2.11236e-07
436:1080001872:TMP:425 mb:rpn_corr=0.999997:rpn_rms=0.0291572
438:1086041393:TCDC:425 mb:rpn_corr=0.999991:rpn_rms=0.123008
445:1110135077:CLMR:425 mb:rpn_corr=0.999997:rpn_rms=1.38153e-08
447:1111760728:RWMR:425 mb:rpn_corr=0.999789:rpn_rms=6.06801e-10
448:1111770920:SNMR:425 mb:rpn_corr=0.999912:rpn_rms=5.55788e-07
449:1112328733:GRLE:425 mb:rpn_corr=0.999986:rpn_rms=2.30502e-07
452:1121756513:TMP:450 mb:rpn_corr=0.999997:rpn_rms=0.0291536
454:1127711194:TCDC:450 mb:rpn_corr=0.999991:rpn_rms=0.121981
461:1151595521:CLMR:450 mb:rpn_corr=0.999998:rpn_rms=1.99469e-08
463:1153285561:RWMR:450 mb:rpn_corr=0.999851:rpn_rms=9.37815e-10
464:1153304832:SNMR:450 mb:rpn_corr=0.999913:rpn_rms=5.79343e-07
465:1153892577:GRLE:450 mb:rpn_corr=0.999984:rpn_rms=2.50292e-07
468:1163877654:TMP:475 mb:rpn_corr=0.999997:rpn_rms=0.0291415
470:1169805196:TCDC:475 mb:rpn_corr=0.999992:rpn_rms=0.118111
477:1195347877:CLMR:475 mb:rpn_corr=0.999998:rpn_rms=2.9855e-08
479:1197060122:RWMR:475 mb:rpn_corr=0.999936:rpn_rms=1.39518e-09
480:1197100614:SNMR:475 mb:rpn_corr=0.999912:rpn_rms=6.02291e-07
481:1197706816:GRLE:475 mb:rpn_corr=0.999981:rpn_rms=2.76249e-07
484:1207616745:TMP:500 mb:rpn_corr=0.999997:rpn_rms=0.0291442
486:1213456320:TCDC:500 mb:rpn_corr=0.999992:rpn_rms=0.118259
493:1238830516:CLMR:500 mb:rpn_corr=0.999999:rpn_rms=4.03584e-08
495:1240576865:RWMR:500 mb:rpn_corr=0.995302:rpn_rms=1.5012e-07
496:1240632359:SNMR:500 mb:rpn_corr=0.999908:rpn_rms=6.25136e-07
497:1241268571:GRLE:500 mb:rpn_corr=0.999975:rpn_rms=3.13435e-07
500:1251140228:TMP:525 mb:rpn_corr=0.999997:rpn_rms=0.0291641
502:1257011860:TCDC:525 mb:rpn_corr=0.999992:rpn_rms=0.118172
509:1282343818:CLMR:525 mb:rpn_corr=0.999999:rpn_rms=4.80224e-08
511:1284154249:RWMR:525 mb:rpn_corr=0.999014:rpn_rms=2.16341e-07
512:1284233552:SNMR:525 mb:rpn_corr=0.999901:rpn_rms=6.43116e-07
513:1284890595:GRLE:525 mb:rpn_corr=0.999964:rpn_rms=3.56372e-07
516:1294695742:TMP:550 mb:rpn_corr=0.999997:rpn_rms=0.0291611
518:1300572252:TCDC:550 mb:rpn_corr=0.999991:rpn_rms=0.120717
527:1328621070:RWMR:550 mb:rpn_corr=0.999799:rpn_rms=3.40895e-07
528:1328772674:SNMR:550 mb:rpn_corr=0.999872:rpn_rms=6.55002e-07
529:1329443594:GRLE:550 mb:rpn_corr=0.999937:rpn_rms=3.88175e-07
532:1339143988:TMP:575 mb:rpn_corr=0.999997:rpn_rms=0.0291558
534:1345012125:TCDC:575 mb:rpn_corr=0.999992:rpn_rms=0.117612
543:1372979202:RWMR:575 mb:rpn_corr=0.999913:rpn_rms=4.40756e-07
544:1373194708:SNMR:575 mb:rpn_corr=0.999835:rpn_rms=6.10324e-07
545:1373820399:GRLE:575 mb:rpn_corr=0.999897:rpn_rms=3.27801e-07
548:1383642722:TMP:600 mb:rpn_corr=0.999997:rpn_rms=0.0291555
550:1389561438:TCDC:600 mb:rpn_corr=0.999992:rpn_rms=0.112758
551:1390906632:SPFH:600 mb:rpn_corr=0.999999:rpn_rms=2.88749e-06
557:1416778030:CLMR:600 mb:rpn_corr=0.999999:rpn_rms=5.94123e-08
559:1418455847:RWMR:600 mb:rpn_corr=0.999908:rpn_rms=4.74339e-07
560:1418701741:SNMR:600 mb:rpn_corr=0.999844:rpn_rms=5.48828e-07
561:1419230238:GRLE:600 mb:rpn_corr=0.99988:rpn_rms=2.65545e-07
564:1428896432:TMP:625 mb:rpn_corr=0.999997:rpn_rms=0.0291542
566:1434791719:TCDC:625 mb:rpn_corr=0.999992:rpn_rms=0.110218
567:1436100395:SPFH:625 mb:rpn_corr=0.999999:rpn_rms=2.88878e-06
573:1461318574:CLMR:625 mb:rpn_corr=0.999999:rpn_rms=5.64559e-08
575:1462939663:RWMR:625 mb:rpn_corr=0.999871:rpn_rms=4.90491e-07
576:1463201211:SNMR:625 mb:rpn_corr=0.999843:rpn_rms=5.43688e-07
577:1463706414:GRLE:625 mb:rpn_corr=0.999866:rpn_rms=2.54012e-07
580:1473279812:TMP:650 mb:rpn_corr=0.999997:rpn_rms=0.0291572
582:1479216899:TCDC:650 mb:rpn_corr=0.999992:rpn_rms=0.108227
583:1480509109:SPFH:650 mb:rpn_corr=0.999999:rpn_rms=2.8894e-06
589:1505911675:CLMR:650 mb:rpn_corr=0.999999:rpn_rms=5.53473e-08
591:1507509153:RWMR:650 mb:rpn_corr=0.999851:rpn_rms=5.08171e-07
592:1507793298:SNMR:650 mb:rpn_corr=0.999833:rpn_rms=5.41227e-07
593:1508291899:GRLE:650 mb:rpn_corr=0.999812:rpn_rms=2.5789e-07
596:1517825017:TMP:675 mb:rpn_corr=0.999997:rpn_rms=0.0291455
598:1523830257:TCDC:675 mb:rpn_corr=0.999992:rpn_rms=0.107951
599:1525133637:SPFH:675 mb:rpn_corr=0.999999:rpn_rms=2.88954e-06
605:1550673487:CLMR:675 mb:rpn_corr=0.999999:rpn_rms=5.68713e-08
607:1552261812:RWMR:675 mb:rpn_corr=0.99985:rpn_rms=5.27533e-07
608:1552574085:SNMR:675 mb:rpn_corr=0.999819:rpn_rms=5.34593e-07
609:1553134911:GRLE:675 mb:rpn_corr=0.999769:rpn_rms=2.54088e-07
612:1562552335:TMP:700 mb:rpn_corr=0.999997:rpn_rms=0.0291545
614:1568613300:TCDC:700 mb:rpn_corr=0.999991:rpn_rms=0.109409
621:1595614880:CLMR:700 mb:rpn_corr=0.999999:rpn_rms=6.15429e-08
623:1597399319:RWMR:700 mb:rpn_corr=0.999841:rpn_rms=5.48851e-07
624:1597738536:SNMR:700 mb:rpn_corr=0.999796:rpn_rms=5.33528e-07
625:1598293889:GRLE:700 mb:rpn_corr=0.999732:rpn_rms=2.52629e-07
628:1607640518:TMP:725 mb:rpn_corr=0.999997:rpn_rms=0.0291559
630:1613779576:TCDC:725 mb:rpn_corr=0.999991:rpn_rms=0.110217
637:1640994524:CLMR:725 mb:rpn_corr=0.999999:rpn_rms=6.53712e-08
639:1642841724:RWMR:725 mb:rpn_corr=0.99983:rpn_rms=5.69417e-07
640:1643209349:SNMR:725 mb:rpn_corr=0.999782:rpn_rms=5.24064e-07
641:1643779117:GRLE:725 mb:rpn_corr=0.999714:rpn_rms=2.4682e-07
644:1653063678:TMP:750 mb:rpn_corr=0.999997:rpn_rms=0.02917
646:1659286273:TCDC:750 mb:rpn_corr=0.999992:rpn_rms=0.11044
653:1686717730:CLMR:750 mb:rpn_corr=0.999999:rpn_rms=6.85617e-08
655:1688601982:RWMR:750 mb:rpn_corr=0.999813:rpn_rms=5.93676e-07
656:1689001188:SNMR:750 mb:rpn_corr=0.999771:rpn_rms=5.23745e-07
657:1689580724:GRLE:750 mb:rpn_corr=0.999664:rpn_rms=2.44802e-07
660:1698793587:TMP:775 mb:rpn_corr=0.999997:rpn_rms=0.0291363
662:1705120794:TCDC:775 mb:rpn_corr=0.999992:rpn_rms=0.112128
669:1732811755:CLMR:775 mb:rpn_corr=0.999999:rpn_rms=7.28651e-08
671:1734792231:RWMR:775 mb:rpn_corr=0.999792:rpn_rms=6.24267e-07
672:1735232603:SNMR:775 mb:rpn_corr=0.999747:rpn_rms=5.30283e-07
673:1735830867:GRLE:775 mb:rpn_corr=0.999561:rpn_rms=2.50654e-07
676:1746249747:TMP:800 mb:rpn_corr=0.999997:rpn_rms=0.0291536
678:1752716169:TCDC:800 mb:rpn_corr=0.999991:rpn_rms=0.116733
685:1780722627:CLMR:800 mb:rpn_corr=0.999999:rpn_rms=8.01904e-08
687:1782891639:RWMR:800 mb:rpn_corr=0.999761:rpn_rms=6.696e-07
688:1783395570:SNMR:800 mb:rpn_corr=0.999721:rpn_rms=5.29615e-07
689:1784009568:GRLE:800 mb:rpn_corr=0.999322:rpn_rms=2.62671e-07
692:1794424405:TMP:825 mb:rpn_corr=0.999997:rpn_rms=0.0291722
694:1801037380:TCDC:825 mb:rpn_corr=0.999991:rpn_rms=0.123246
701:1829440070:CLMR:825 mb:rpn_corr=0.999999:rpn_rms=9.06282e-08
703:1831864996:RWMR:825 mb:rpn_corr=0.999709:rpn_rms=7.33696e-07
704:1832459101:SNMR:825 mb:rpn_corr=0.999669:rpn_rms=5.38867e-07
705:1833103847:GRLE:825 mb:rpn_corr=0.998783:rpn_rms=2.81754e-07
708:1843876507:TMP:850 mb:rpn_corr=0.999997:rpn_rms=0.0291385
710:1850635861:TCDC:850 mb:rpn_corr=0.99999:rpn_rms=0.130955
717:1878739669:CLMR:850 mb:rpn_corr=0.999999:rpn_rms=1.0122e-07
719:1881419445:RWMR:850 mb:rpn_corr=0.999614:rpn_rms=8.33914e-07
720:1882145546:SNMR:850 mb:rpn_corr=0.999991:rpn_rms=8.06722e-08
721:1882824001:GRLE:850 mb:rpn_corr=0.998128:rpn_rms=2.89907e-07
724:1893444096:TMP:875 mb:rpn_corr=0.999998:rpn_rms=0.0291531
726:1900472404:TCDC:875 mb:rpn_corr=0.99999:rpn_rms=0.136721
733:1928890160:CLMR:875 mb:rpn_corr=0.999999:rpn_rms=1.08839e-07
735:1931710960:RWMR:875 mb:rpn_corr=0.999488:rpn_rms=9.45075e-07
736:1932574469:SNMR:875 mb:rpn_corr=0.99999:rpn_rms=7.69269e-08
737:1933216231:GRLE:875 mb:rpn_corr=0.997442:rpn_rms=2.949e-07
740:1943605006:TMP:900 mb:rpn_corr=0.999998:rpn_rms=0.0291567
742:1950510014:TCDC:900 mb:rpn_corr=0.999989:rpn_rms=0.138926
749:1979019549:CLMR:900 mb:rpn_corr=0.999999:rpn_rms=1.05743e-07
751:1981704386:RWMR:900 mb:rpn_corr=0.999388:rpn_rms=1.0091e-06
752:1982640828:SNMR:900 mb:rpn_corr=0.999989:rpn_rms=7.05731e-08
753:1983212516:GRLE:900 mb:rpn_corr=0.997044:rpn_rms=2.76944e-07
756:1993303825:TMP:925 mb:rpn_corr=0.999998:rpn_rms=0.0291536
758:2000317768:TCDC:925 mb:rpn_corr=0.999986:rpn_rms=0.140735
765:2028674668:CLMR:925 mb:rpn_corr=0.999998:rpn_rms=9.45057e-08
767:2031062695:RWMR:925 mb:rpn_corr=0.999351:rpn_rms=1.01411e-06
768:2032002943:SNMR:925 mb:rpn_corr=0.999989:rpn_rms=6.31915e-08
769:2032490859:GRLE:925 mb:rpn_corr=0.996473:rpn_rms=2.50066e-07
772:2041825063:TMP:950 mb:rpn_corr=0.999998:rpn_rms=0.0291561
774:2048574299:TCDC:950 mb:rpn_corr=0.999988:rpn_rms=0.123645
783:2078198931:RWMR:950 mb:rpn_corr=0.999351:rpn_rms=9.86681e-07
784:2079116206:SNMR:950 mb:rpn_corr=0.999989:rpn_rms=5.47372e-08
785:2079507858:GRLE:950 mb:rpn_corr=0.999852:rpn_rms=3.52751e-08
789:2089340395:TMP:975 mb:rpn_corr=0.999998:rpn_rms=0.0291555
791:2096190312:TCDC:975 mb:rpn_corr=0.999988:rpn_rms=0.101503
798:2122972506:CLMR:975 mb:rpn_corr=0.999998:rpn_rms=6.10931e-08
800:2124154266:RWMR:975 mb:rpn_corr=0.9994:rpn_rms=9.13667e-07
801:2124964691:SNMR:975 mb:rpn_corr=0.999989:rpn_rms=4.03516e-08
802:2125209098:GRLE:975 mb:rpn_corr=0.999558:rpn_rms=2.60046e-08
804:2129488778:TMP:1000 mb:rpn_corr=0.999998:rpn_rms=0.0291529
806:2136189846:TCDC:1000 mb:rpn_corr=0.999977:rpn_rms=0.0683013
815:2161769142:RWMR:1000 mb:rpn_corr=0.999508:rpn_rms=7.17309e-07
816:2162273580:SNMR:1000 mb:rpn_corr=0.999984:rpn_rms=1.53546e-08
817:2162313775:GRLE:1000 mb:rpn_corr=0.99997:rpn_rms=1.39898e-09
838:2210244030:CNWAT:surface:rpn_corr=0.996771:rpn_rms=0.016024
839:2211586573:WEASD:surface:rpn_corr=0.999989:rpn_rms=0.177372
840:2213898054:SNOD:surface:rpn_corr=0.999983:rpn_rms=0.00186165
854:2250571024:CPRAT:surface:rpn_corr=0.999999:rpn_rms=1.65114e-07
855:2253174091:PRATE:surface:rpn_corr=0.998304:rpn_rms=1.24347e-05
856:2255687304:CPRAT:surface:rpn_corr=0.999994:rpn_rms=2.15416e-07
857:2258421432:PRATE:surface:rpn_corr=0.999869:rpn_rms=2.19263e-06
890:2304787029:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.999999:rpn_rms=0.0288774
891:2309488058:CWAT:entire atmosphere (considered as a single layer):rpn_corr=0.999944:rpn_rms=0.00223723
892:2313153611:RH:entire atmosphere (considered as a single layer):rpn_corr=0.999853:rpn_rms=0.291709
894:2317395239:LCDC:low cloud layer:rpn_corr=0.999992:rpn_rms=0.175503
895:2320380979:LCDC:low cloud layer:rpn_corr=0.999985:rpn_rms=0.219115
896:2324053111:MCDC:middle cloud layer:rpn_corr=0.999995:rpn_rms=0.127754
897:2326092525:MCDC:middle cloud layer:rpn_corr=0.999986:rpn_rms=0.189709
898:2328897580:HCDC:high cloud layer:rpn_corr=0.999994:rpn_rms=0.150909
899:2331502350:HCDC:high cloud layer:rpn_corr=0.999984:rpn_rms=0.227425
900:2335197978:TCDC:entire atmosphere:rpn_corr=0.999992:rpn_rms=0.169651
901:2338280807:TCDC:entire atmosphere:rpn_corr=0.999982:rpn_rms=0.224101
907:2367068357:BRTMP:top of atmosphere:rpn_corr=0.999916:rpn_rms=0.291257
912:2391072183:TMP:low cloud top level:rpn_corr=0.999998:rpn_rms=0.0291567
913:2395611040:TMP:middle cloud top level:rpn_corr=0.999997:rpn_rms=0.0291437
914:2399438025:TMP:high cloud top level:rpn_corr=0.999998:rpn_rms=0.0291537
915:2404679757:TCDC:convective cloud layer:rpn_corr=0.999958:rpn_rms=0.156582
916:2407457762:TCDC:boundary layer cloud layer:rpn_corr=0.999979:rpn_rms=0.219881
917:2411067277:CWORK:entire atmosphere (considered as a single layer):rpn_corr=0.999997:rpn_rms=0.12873
918:2412288894:DSWRF:surface:rpn_corr=0.999955:rpn_rms=2.41806
919:2416152366:DUVB:surface:rpn_corr=0.999986:rpn_rms=0.0242841
-------------------------------------------
flux file --
22:49240825:CNWAT:surface:rpn_corr=0.996771:rpn_rms=0.016024
23:50583368:WEASD:surface:rpn_corr=0.999989:rpn_rms=0.177372
25:53807434:SNOD:surface:rpn_corr=0.999983:rpn_rms=0.00186165
29:61853712:EVCW:surface:rpn_corr=0.999977:rpn_rms=0.14844
30:63017051:EVBS:surface:rpn_corr=0.999965:rpn_rms=0.232741
31:64727504:TRANS:surface:rpn_corr=0.999978:rpn_rms=0.169787
32:65945812:SBSNO:surface:rpn_corr=0.999765:rpn_rms=0.146168
42:97099367:CPRAT:surface:rpn_corr=0.999994:rpn_rms=2.15416e-07
43:99833495:PRATE:surface:rpn_corr=0.999869:rpn_rms=2.19263e-06
44:102543355:SSRUN:surface:rpn_corr=0.999998:rpn_rms=0.00102628
68:150246336:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.999999:rpn_rms=0.0288774
69:154947365:LCDC:low cloud layer:rpn_corr=0.999985:rpn_rms=0.219115
70:158619497:MCDC:middle cloud layer:rpn_corr=0.999986:rpn_rms=0.189709
71:161424552:HCDC:high cloud layer:rpn_corr=0.999984:rpn_rms=0.227425
72:165120180:TCDC:entire atmosphere:rpn_corr=0.999982:rpn_rms=0.224101
81:210083642:TMP:low cloud top level:rpn_corr=0.999998:rpn_rms=0.0291567
82:214622499:TMP:middle cloud top level:rpn_corr=0.999997:rpn_rms=0.0291437
83:218449484:TMP:high cloud top level:rpn_corr=0.999998:rpn_rms=0.0291537
84:223691216:TCDC:convective cloud layer:rpn_corr=0.999958:rpn_rms=0.156582
85:226469221:TCDC:boundary layer cloud layer:rpn_corr=0.999979:rpn_rms=0.219881
87:230786661:DSWRF:surface:rpn_corr=0.999955:rpn_rms=2.41806
88:234650133:DUVB:surface:rpn_corr=0.999986:rpn_rms=0.0242841
89:238282571:CDUVB:surface:rpn_corr=0.999989:rpn_rms=0.024373
90:240454999:DLWRF:surface:rpn_corr=0.999994:rpn_rms=0.291577
91:244009542:USWRF:surface:rpn_corr=0.999991:rpn_rms=0.242055
92:247298200:ULWRF:surface:rpn_corr=0.999994:rpn_rms=0.291564
93:250034037:USWRF:top of atmosphere:rpn_corr=0.999998:rpn_rms=0.246733
94:254017387:ULWRF:top of atmosphere:rpn_corr=0.99998:rpn_rms=0.291489
95:257436356:DSWRF:surface:rpn_corr=0.999977:rpn_rms=2.04236
96:260562106:DLWRF:surface:rpn_corr=0.999994:rpn_rms=0.291441
97:264481602:USWRF:surface:rpn_corr=0.999996:rpn_rms=0.2042
98:267236901:ULWRF:surface:rpn_corr=0.999994:rpn_rms=0.29175
99:270144021:CSDSF:surface:rpn_corr=0.999967:rpn_rms=2.43256
100:272542977:CSUSF:surface:rpn_corr=0.999992:rpn_rms=0.243638
101:274945139:CSUSF:top of atmosphere:rpn_corr=0.999994:rpn_rms=0.246681
102:277660088:DSWRF:top of atmosphere:rpn_corr=0.999981:rpn_rms=2.45537
103:278628824:CSDLF:surface:rpn_corr=0.999994:rpn_rms=0.29156
104:281120076:CSULF:surface:rpn_corr=0.999994:rpn_rms=0.291472
105:283812257:CSULF:top of atmosphere:rpn_corr=0.999965:rpn_rms=0.291539
106:286100662:VBDSF:surface:rpn_corr=0.999997:rpn_rms=0.210229
107:289617374:VDDSF:surface:rpn_corr=0.999993:rpn_rms=0.24539
108:293735208:NBDSF:surface:rpn_corr=0.999998:rpn_rms=0.213432
109:297453010:NDDSF:surface:rpn_corr=0.99999:rpn_rms=0.245493
112:307851166:ICEC:surface:rpn_corr=0.999998:rpn_rms=0.000389138
