### ISSUE TITLE
Updates for Standalone release from DTC - Fall 2020

### ISSUE THREAD

**Issue by fossell** [NOAA-EMC/UPP#189]
This issue contains details and tasks needed for release of standalone UPP package in conjunction with SRW release.

Details/Tasks:

- Will be same as final tag for SRW tag. Working out of the release/public-v2
- Goal is to use Cmake and retire configure/compile for community builds. (*Note: EMC/operations will continue  to use gnu make and maintain their makefile)
- Uses authoritative NOAA/NCEPLIBS as dependency for build (release/public-v2 branch/tag)
- CRTM: Upgraded to v2.3.0; uses source code from NCEPLIBS
   - subset of coefficient files will be uploaded to GitHub release page
- Retire use of "unipost.exe" nomenclature from community packages and change to "ncep_post" for consistency throughout builds - COMPLETE with #197 
   - Update UG to use ncep_post for executable name
   - Update run_unipost script to use ncep_post name, and rename script to run_upp
- Add fv3r model name to run script
- Version numbering for UPP will begin with v9* series in release/public-v2 - COMPLETE with #203 
- Documentation: Add advanced documentation detailing how to "Add a New Variable"

**Comment by jwolff-ncar** [comment]
@mkavulich @kayeekayee Wanted to tag you on this issue so you can update as necessary.

**Comment by fossell** [comment]
UPP V9.0.0 standalone community release was completed and tagged as upp-v9.0.0 on March 9, 2021.
