### ISSUE TITLE
Add a README in accordance with NCEPLIBS requirements

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UPP#206]
I would like to add a README to match those on the other NCEPLIBS libraries. See https://github.com/NOAA-EMC/NCEPLIBS/issues/120

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett It sounds good to me. Will you file a PR to branch develop?

**Comment by edwardhartnett** [comment]
Yes. Who is the code manager for this repo?

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett I am one of code managers. You may follow the procedure at
https://github.com/NOAA-EMC/EMC_post/wiki/UPP-Code-Development#contribute-changes-in-upp-main-development-branch-develop

to submit your PR. Please let me know if you need other information. Thanks!
