### ISSUE TITLE
Add CI with github actions?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UPP#209]
It would benefit the NCEPLIBS team, and presumably also the UPP team, to add continuous integration to this repository with github actions.

GitHub actions are a free CI service offered by GitHub. We use it for most of the NCEPLIBS projects. A good example can be seen here:
https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/34

Note that the tests are automatically run on each PR.

This is accomplished by adding one or more build files, in a special directory .github/workflows. This requires no changes to any of your codes or build system. A sample may be seen here: https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/develop/.github/workflows/main.yml

NCEPLIBS libraries are used by many UPP programs, and we need to ensure that NCEPLIBS continue to provide the services required by UPP. So UPP testing is NCEPLIBS testing too. ;-) As we test and work with NCEPLIBS, we would like to also add tests to UPP related to NCEPLIBS functionality.

If this seems a good idea, the first step would be for me to submit a build .yml file for EMC_post.

**Comment by fossell** [comment]
This is another item on our wishlist, so I'm in favor.  However, DTC is not likely going to have time to help with this in the near term.  Perhaps in a couple months after UFS release and refactor merge is complete, and we tackle the repo reorganization as well.

**Comment by edwardhartnett** [comment]
I don't need any help turning on the CI and that can be in place this week. 

Adding tests is the next step, and one that will take many months of effort. But turning on the CI is easy, only one file is added to the repo, no code is changed, and there is no cost to NOAA.

Can I proceed to add CI?

**Comment by fossell** [comment]
@edwardhartnett - It's ok with me to proceed with the PR to turn on CI as long as @WenMeng-NOAA agrees.  Just need understanding that our ability to assist with adding tests or any issues that arise will be very limited in the next couple months as we attend to other priorities.

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett It's ok for me for starting PR. As the code managers at DTC and EMC have many tasks, it might be taking some time for final integration. Please let us know if it works for you. Thanks!

**Comment by edwardhartnett** [comment]
We have had some interesting discussions about how we will do this. @aerorahul has offered some suggestions about using the docker images to load prerequisite libraries. We will continue to work on this and we will put up a PR when we have a build that works well.

**Comment by fossell** [comment]
Two of us on the DTC team (myself and @mkavulich) have some experience dockerizing community versions of UPP for another project.  We plan to make a docker container available for what is essentially public-v2 branch post-SRW release, which will depend on NCEPLIBS repos.  This is separate from the CI initiative, but I just mention it in case there are efforts/issues evolving at the same time that we can leverage from each other. @mkavulich will be heading up that effort while I'm on leave, so touch base with him if needed.
