### ISSUE TITLE
Non-reproducible aborts in GOES lookalike UPP job running in regional FV3

### ISSUE THREAD

**Issue by EricRogers-NOAA** [NOAA-EMC/UPP#225]
The UPP job making GOES-16 lookalike fields in the FV3 regional run will occasionally abort with this traceback:

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
regional_post.x    0000000000F7DD8D  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B4B6B979630  Unknown               Unknown  Unknown
regional_post.x    000000000099A044  initpost_netcdf_          948  INITPOST_NETCDF.f
regional_post.x    0000000000797C24  MAIN__                    772  WRFPOST.f
regional_post.x    000000000040E53E  Unknown               Unknown  Unknown
libc-2.17.so       00002B4B6C263545  __libc_start_main     Unknown  Unknown
regional_post.x    000000000040E443  Unknown               Unknown  Unknown

Line #948 in INITPOST_NETCDF.f is a print statement:

941       do l=2,lp1
 942         do j=jsta,jend
 943           do i=1,im
 944             pint(i,j,l)   = pint(i,j,l-1) + dpres(i,j,l-1)
 945           enddo
 946         enddo
 947         if (me == 0) print*,'sample model pint,pmid' ,ii,jj,l &
 948           ,pint(ii,jj,l),pmid(ii,jj,l)
 949       end do

When rerun the job runs to conclusion.

**Comment by WenMeng-NOAA** [comment]
@ericaligo-NOAA There is a bug in  line 948 which intends to printout a out of dimension array pmid(i,j,61), where the third dimension of pmid is set as 60. This printout line should be commented out. The fix will be added with PR #255.
