### ISSUE TITLE
Bad values in GOES satellite brightness temps in CONUS LAM domain

### ISSUE THREAD

**Issue by EricRogers-NOAA** [NOAA-EMC/UPP#236]
Since the CONUS LAM parallels started running with the latest version of the new Equidistant Spaced Gnomonic (ESG) regional FV3 model grid, the GOES brightness temperatures are either 0 or set to a fill value everywhere, for example:

  ndata=1770444:undef=0:mean=2.70735e+06:min=0:max=9.786e+10

The regular UPP job is running fine using this grid. Tests with debug prints turned on in the CALRAD_WCLOUD_newcrtm.f routine revealed points with undefined values on the lambert conformal grid output by the CONUS LAM UFS model write component:

bad atmosphere(1)%level_pressure      1    559      3   2970000128.00000
bad atmosphere(1)%pressure      1    559      3   990000000.000000

As a stopgap fix, Wen provided Ben and Eric R. a version of the CLDRAD_WCLOUD_newcrtm.f routine that checks for undefined points. This fixed the problem for now, but in the future this should issue should be revisited to see if a better solution is possible.

**Comment by WenMeng-NOAA** [comment]
Wen will combine the fixes in Jun's regional in-line post pull request #255.
