### ISSUE TITLE
Memory error on TACC

### ISSUE THREAD

**Issue by tsupinie** [NOAA-EMC/UPP#238]
I've run into an issue on TACC machines (stampede2, frontera). It works fine with an unoptimized binary, but when I use -O1 or higher, I get variations on this error:

```
forrtl: severe (41): insufficient virtual memory
Image              PC                Routine            Line        Source     
ncep_post          0000000000CD83BC  Unknown               Unknown  Unknown
libnetcdff.so.6.1  00002B208777ECF0  nf_get_vara_real_     Unknown  Unknown
libnetcdff.so.6.1  00002B20877D8C79  netcdf_mp_nf90_ge     Unknown  Unknown
ncep_post          0000000000737476  read_netcdf_2d_sc        2913  INITPOST_NETCDF.f
ncep_post          000000000073FEEE  initpost_netcdf_         1285  INITPOST_NETCDF.f
ncep_post          0000000000603E54  MAIN__                    773  WRFPOST.f
ncep_post          000000000040E8BE  Unknown               Unknown  Unknown
libc-2.17.so       00002B2089AB13D5  __libc_start_main     Unknown  Unknown
ncep_post          000000000040E7A9  Unknown               Unknown  Unknown
```

It's always that line, though sometimes it's "just" a regular segmentation fault. Has anyone ever run into that and/or have a workaround that doesn't involve running an unoptimized binary? The unoptimized binary has been mostly doable, but I've run into a situation where I'd really like to be able to optimize it.

**Comment by WenMeng-NOAA** [comment]
This is the first time that the UPP user reports the memory issue from the regional FV3 read interface INITPOST_NETCDF.f. It is fine
for our UPP stand-alone tests for regional FV3 on Hera and Orion. It might be related to your platform configuration. Will you get assistance from TACC machine SA?

**Comment by WenMeng-NOAA** [comment]
This issue is closed since no new updates from the issue reporter.
