### ISSUE TITLE
restrict post computation from undefined points  

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/UPP#240]
Currently in POST, there is no restriction to keep the computation only happening on valid points with reasonable value. The undefined value are participating in the computation in many places which causes wrong value in post products. One example is when regional output domain is larger than the forecast computational domain. FillValue is put on the extra domain for all the fields, however those fields are still involved in post computation and causes issues.

**Comment by HuiyaChuang-NOAA** [comment]
After Wen tested and merged Jun's UPP updates, Jesse will take over and scan through all UPP subroutines to make sure derivations are only done when none of input has missing values.
Jesse will also follow Jun's advice to test use of negative value as missing value instead, e.g., -1.e10
Jesse's task is tracked and documented in
https://vlab.ncep.noaa.gov/redmine/issues/87352

**Comment by JesseMeng-NOAA** [comment]
Wen, please let me know when you are ready. Thanks,

Jesse

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA The UPP branch was updated with the PR #255 for regional in-line post.

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA Any updates on this issue?

**Comment by JesseMeng-NOAA** [comment]
> @JesseMeng-NOAA Any updates on this issue?

working on it

**Comment by JesseMeng-NOAA** [comment]
pull request submitted
https://github.com/NOAA-EMC/EMC_post/pull/306

**Comment by WenMeng-NOAA** [comment]
> Correct. 
> ==============================================
> Dr. Jesse Meng
> IMSG at NOAA/NWS/NCEP/EMC
> 5830 University Research Ct. Room 2037
> College Park, MD 20740
> email: jesse.meng@noaa.gov
