### ISSUE TITLE
Update the user guide of adding new variable in UPP

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#250]
The DTC has a user guide of adding new variable in UPP at
https://dtcenter.org/sites/default/files/community-code/add-new-upp-variable.pdf

This document is needed an update for reflecting the UPP refactor change such as removing GRIB1 output.

**Comment by WenMeng-NOAA** [comment]
@kayeekayee Does the DTC UPP team have any suggestions or a plan for this update? We have several UPP collaborators have plans of adding new fields in UPP for different projects. A updated guidance would be good for them. Thanks!

**Comment by hertneky** [comment]
@WenMeng-NOAA There is a PR #241 with the updated "Add New Variable" documentation for our release/public-v2. The example in the documentation was tested and successful for me, but last I heard Ka Yee was unable to produce the new example field in the output. Do you have any update on this @kayeekayee?

**Comment by WenMeng-NOAA** [comment]
@hertneky The PR #241 is very helpful. Would you guide me how to review rst format file either online or off-line? Thanks!

**Comment by jwolff-ncar** [comment]
Hopefully @kayeekayee or @mkavulich can help! (@hertneky and @fossell are on maternity leave.)

**Comment by fossell** [comment]
@WenMeng-NOAA - Our procedure is to serve up the rst files using readthedocs, which is where current versions of UPP user guides are available for UFS.  Tracy had a demo of this up (non-public) but it looks like it's no longer available.  We do plan to make a new UG publicly available with the release of SRW public-v2 and stand alone community UPP. If you need  something accessible before that (February, last I heard), let us know and we can build a UG for you.  

@kayeekayee @mkavulich @llpcarson - Are you able to build a temporary UG on your readthedocs account based off of public-v2 for Wen to review with the understanding that this shouldn't be distributed yet?

**Comment by WenMeng-NOAA** [comment]
@fossell Thanks for replying during your maternity leave. I hope you and your family are doing well.  I created this issue because recently a few UPP collaborators have been using the DTC document from https://dtcenter.org/sites/default/files/community-code/add-new-upp-variable.pdf for their development of adding few fields.  I briefly look at AddNewVariable.rst from Tracy's branch on github. It looks good to me. I might have a few comments. Since you and Tracy are on maternity leave, we could address later. I will point the new rst file from Tracy's branch on github to our collaborators and email them a few tips for their specific cases. Thanks!

**Comment by hertneky** [comment]
@WenMeng-NOAA I do have the document viewable from my fork, based off of release/public-v2 via readthedocs. This is public, so it should be viewable. Section 7 is adding a new variable. I certainly welcome any comments/feedback you have on this document, and can address those at a later date when I return from maternity leave. https://upp-hertneky.readthedocs.io/en/v2_addvar_mods/

**Comment by WenMeng-NOAA** [comment]
@hertneky Thanks for pointing the readthedocs link. I would pass it to our UPP developers. Wish everything is doing well during your maternity leave! Thanks!

**Comment by WenMeng-NOAA** [comment]
Hui-ya and Wen updated adding new fields in UPP procedure at
https://docs.google.com/document/d/1r2BQtAI33S_zCDh6Ko-aFW0kO79MYILspW31Bw4zE60/edit

**Comment by hertneky** [comment]
@WenMeng-NOAA I am updating the 'Add new variable' documentation. I have incorporated all changes you made in the google document. I need to update the actual example. Can you point me to GFS V16 model output (e.g. what is used for regression tests), so I can update and test the steps? This will be on my fork for final review via readthedocs once complete.

**Comment by WenMeng-NOAA** [comment]
@hertneky If you have Hera access, the GFS V16 model output for regression tests can be found at /scratch2/NCEPDEV/ovp/Wen.Meng/ncep_post/post_regression_test_new/data_in/ as gfs.t00z.atmf006.nc and gfs.t00z.sfcf006.nc.

**Comment by fossell** [comment]
@WenMeng-NOAA @hertneky - Has this issue been resolved now with Tracy's recent documentation updates in #355?

**Comment by WenMeng-NOAA** [comment]
@fossell I think so. Thanks Tracy's efforts.
