### ISSUE TITLE
Add 0-1km above ground Vertical U and V-Component of the Wind Shear

### ISSUE THREAD

**Issue by EricRogers-NOAA** [NOAA-EMC/UPP#253]
The LAM team would like to have the 0-1km AGL vertical u/v components of the wind shear (VUCSH and VVCSH) added to the fv3sar.xml file in the EMC_post repository, and have the postxconfig-NT-fv3sar.txt file updated accordingly. A copy of fv3sar.xml with these added can be found on Mars in /gpfs/dell6/emc/modeling/noscrub/Eric.Rogers/fv3lam_for_dellp3.5/sorc/regional_post.fd/parm

**Comment by WenMeng-NOAA** [comment]
@EricRogers-NOAA 
Eric,

I will pick up the changes into my branch, submit a pull request and have you being code reviewer. Please let me know if this plan is working for you.

Thanks,

Wen

**Comment by WenMeng-NOAA** [comment]
@EricRogers-NOAA 
It appears to me besides UVCSH/VVCSH AGL 0-1km, there are more updates in fv3sar.xml from your branch:

- Rename dataset BGDAWP to AGDAWP
- Increase precision of ICMR, RWMR, SNMR at hybrid levels and isobaric level  from 3 to 6
- Remove  ACM_WEASD_ON_SURFACE
- Increase precision of INST_PRATE_ON_SURFACE from 3 to 6
- Increase precision of MAX_PRATE_ON_SURFACE from 4 to 6
- Rename dataset BGRD3D to AGRD3D
- Remove ACM_WEASD_ON_SURFACE
- Increase precision of INST_PRATE_ON_SURFACE from 3 to 6
- Increase precision of RWMR_ON_HYBRID_LVL, SNMR_ON_HYBRID_LVL, FRAIN_ON_HYBRID_LVL, FICE_ON_HYBRID_LVL from 3 to 6
- Remove TCDC_ON_SIGMA_LVLS
-
Please let me know you would like the above changes to be updated in branch develop on UPP repository also.

Thanks,
