### ISSUE TITLE
Resolve different field names for regional and global applications

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/UPP#259]
It was discussed at the UFS infrastructure meeting that a unified inline post will be created. Since standalone POST is using two different initialization subroutines (INITPOST_GFS_NETCDF_PARA.f and INITPOST_NETCDF.f) for global and regional applications, the different fields names used in the two applications need to  be unified with consistent fields names in POST. Also changes need to be made to either (or both) global/regional diag_table file in order for post to work in global and regional workflow. Also It is good to create a unified post initialization interface so that the unified inline post can be verified.

**Comment by WenMeng-NOAA** [comment]
This issue was solved in the PR #453.
