### ISSUE TITLE
Non b4b reproducible master.grb2fXXX files from GFS v16 model with inline UPP

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/UPP#262]
GFS v16 forecast model runs with differrent WRITE_GROUP_GFS yield master.grb2fXXX files that are not b4b identical.   Investigations thus far show the differences to be limited to cloud ceiling height.

NCO's implementation of the GFS v16 package was run on Venus using NCO's warm start initial conditions for 2021020712 gfs.    The gfs forecast step was run three times out to F024 with hourly output.  Each forecast job used a different WRITE_GROUP_GFS (4, 6, 8).   NCO runs the GFS v16 pre-implementation parallel with WRITE_GROUP_GFS=8.   Using NCO's output as the control, the following behavior was observed as a function of WRITE_GROUP_GFS
- WRITE_GROUP_GFS=8:  master.grbfXXX files are b4b identical with NCO's output
- WRITE_GROUP_GFS=6:  master.grbfXXX files are b4b identical with NCO's output for f000 to f005.  master.grb2fxxx differ for f006 to f024.  A $WGRIB2 listing of the test and NCO files show the difference to be in record 902, cloud ceiling height.
- WRITE_GROUP_GFS=4:  master.grbfXXX files are b4b identical with NCO's output for f000 to f003.  master.grb2fxxx differ for f004 to f024.   A $WGRIB2 listing of the test and NCO files show the difference to be in record 902, cloud ceiling height.
 
These findings were shared with EMC staff who work on the model and UPP.   The following hypothesis as to what may be happening was shared:

> If there is any uninitialized or saved value in POST, then if there are 4 groups, the write tasks computing master.grb2f004 (second round of write groups) could use the computed/saved value from previous computation for master.grb2f000. This is different from 8 write groups, where master.grb2f000 to master.grb2f007 are all computed the same way.

It was requested that a github issue be opened in EMC_post to document and track resolution of this unexpected behavior.

**Comment by WenMeng-NOAA** [comment]
Quoted from Qingfu for cloud ceiling fix on 02/15/2021

> The code fix:
/scratch1/NCEPDEV/global/Qingfu.Liu/gfsv16_ccpp/sorc/fv3gfs.fd/FV3/io/post_gfs.F90

> start from line 2429:

`  ! hbot

      do j=jsta,jend
        do i=1,im
          hbot(i,j)  = SPVAL     ! Qingfu Liu added
          if(pbot(i,j) < spval)then
            do l=lm,1,-1
              if(pbot(i,j) >= pmid(i,j,l)) then
                hbot(i,j) = l
                exit
              end if
            end do
          end if
        end do
      end do
`

**Comment by WenMeng-NOAA** [comment]
On 02/17/2021, Qingfu conducted the following four tests for cloud ceiling fix:

>   The data before the fix:
WRITE_GROUP_GFS=8:  /scratch1/NCEPDEV/stmp2/Qingfu.Liu/ROTDIRS/ccpp_gfsv16/gfs.20190701_82
WRITE_GROUP_GFS=2:  /scratch1/NCEPDEV/stmp2/Qingfu.Liu/ROTDIRS/ccpp_gfsv16_4/gfs.20190701_42

     The data after the fix:
WRITE_GROUP_GFS=8:  /scratch1/NCEPDEV/stmp2/Qingfu.Liu/ROTDIRS/ccpp_gfsv16/gfs.20190701_83
WRITE_GROUP_GFS=2:  /scratch1/NCEPDEV/stmp2/Qingfu.Liu/ROTDIRS/ccpp_gfsv16_4/gfs.20190701_43

I quickly checked the differences of the data, the fix only impacts results from  WRITE_GROUP_GFS=2 cloud ceiling. All other differences seem random since all the tests have difference values (you can compare the two runs before the fix).

Qingfu and Wen verified the cloud ceiling fix is working for FV3GFS.

**Comment by WenMeng-NOAA** [comment]
On 02/23/2021, Jun picked up this cloud ceiling fix and combined her changes for regional in-line post at fv3atm repository
at https://github.com/junwang-noaa/fv3atm/commit/5dcd1f5600f7a35085e9950a186c4d843f8c2567

**Comment by WenMeng-NOAA** [comment]
@RussTreadon-NOAA, @yangfanglin @HuiyaChuang-NOAA @junwang-noaa  The cloud ceiling fix from Qingfu will be updated in the ufs-weather-model with Jun's PR for regional in-line post capability. I will close this issue as completed. Please let me know if you have any concerns/comments.
