### ISSUE TITLE
Compiling UPP via cmake without openmp option

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#264]
The current UPP is not threading safe. It was found that building upp library via cmake having **openmp** option involved. 
` [ 2%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CTLBLK.f.o
cd /home/Wen.Meng/stmp2/develop/EMC_post/tests/build/sorc/ncep_post.fd && /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/ifort -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/bacio/2.4.1/include_4 -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/crtm/2.3.0/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/g2/3.4.1/include_4 -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/png/1.6.35/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/zlib/1.2.11/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/g2tmpl/1.9.1/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/ip/3.3.3/include_4 -I/apps/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/sp/2.3.3/include_4 -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/w3nco/2.4.1/include_4 -g -traceback -fp-model source -free -convert big_endian -O3 -module include -qopenmp -c /home/Wen.Meng/stmp2/develop/EMC_post/sorc/ncep_post.fd/CTLBLK.f -o CMakeFiles/upp.dir/CTLBLK.f.o `

**Comment by WenMeng-NOAA** [comment]
02/19/21 from Rahaul:

> I dug in and I think I have found the problem. It is rooted in how transient dependencies are found and linked in CMake.  Basically, the -qopenmp that you see in UPP (or UFS) even when compiling these applications/libraries without OPENMP comes from the underlying dependencies that are built with OpenMP.
I am working on a test to test my hypothesis in a simple case. 

> Kyle,
We may need to make a change wherever OpenMP is linked in by replacing:

> -   target_link_libraries(${lib_name} PRIVATE OpenMP::OpenMP_Fortran) 
>+   target_link_libraries(${lib_name} "$<BUILD_INTERFACE:OpenMP::OpenMP_Fortran>")

**Comment by WenMeng-NOAA** [comment]
02/21/21 from Qingfu's tests on upp/10.0.0:

>   I set the thread=1 (nth_fv3=1) and run two tests using the upp/10.0.0. The master grib2 files are identical for WRITE_GROUP_GFS=8 and WRITE_GROUP_GFS=2. I also tested the newly built UPP library and the results for master grib2 files are also identical for different WRITE_GROUP_GFS when set "nth_fv3=1". So the problem comes from threading.

**Comment by HuiyaChuang-NOAA** [comment]
Now that we know using cmake/HPC stack resulted in compiling UPP with OpenMP, it has become more
urgent to update UPP to make it thread safe going forward.  Especially because in-line post is run in GFS development 
and soon will be by RRFS.  WE need to make sure these development output are valid. 

I spoke to two UPP re-engineering staff but they do not have experiences working on threading and will
need some time to spin up.

Emailed Arun and set up a meeting on 2/26/2021 to request EIB's help to quickly update UPP to become thread safe.

**Comment by aerorahul** [comment]
@HuiyaChuang-NOAA 
CMake brings in transient dependencies automatically; i.e. if a program depends on a library that depends on other libraries, it is the job of the dependent library to bring forth its dependencies. e.g. if NCEPLIBS were compiled with OpenMP, when linking with them, they bring forward those OpenMP flags (`-qopenmp`).
If one wants to build a non-threaded version of UPP, one should probably want to use OpenMP OFF versions of its dependencies. Normally one would probably compile the whole dependency chain one way
or the other.

One can however, tell CMake to not bring forth transient dependencies, but that breaks one of the fundamental functionality of cmake to handle dependencies.  In that case, the user has to know explicitly what those dependencies are and how to resolve them.  Doing so, one is back to writing Makefiles for each scenario.

**Comment by WenMeng-NOAA** [comment]
@aerorahul To improve UPP thread safe might not be finished within one month. 
Please advise the fix for building non-thread upp lib via cmake or other options. We have global in-line post and upcoming regional in-line post relying on it. Thanks!

**Comment by WenMeng-NOAA** [comment]
The efforts of making UPP code thread safe was just started from the UPP re-factor. This issue should be solved with that UPP -refactor task completed.

**Comment by aerorahul** [comment]
@WenMeng-NOAA 
I wrote a build script for you that will clone the UPP and its NCEPLIBS dependencies and build them.
The dependencies (and UPP) can be built with or without OPENMP (The script has an option, default is OFF).
I tested the build on Hera (Orion is down today).

You can find the script on Hera at:
```
/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/test/Wen.Meng/build_upp.sh
```

To use it:
```
target=hera ./build_upp.sh 2>&1 | tee log.upp
```

**Comment by WenMeng-NOAA** [comment]
@aerorahul That's great! I did my test with your new script on hera and saw openmp option was not involved UPP code compiling.  My understanding is your new cmake build way would be checking all dependency libs from their repositories and building without openmp instead of using existing libs at the hpc-stack, right? 
I will add a link of your script in the hpc-stack issue #[171](https://github.com/NOAA-EMC/hpc-stack/issues/171) for the reference of installing upp lib. I would integrate your script in the UPP repository later. Thanks!

**Comment by aerorahul** [comment]
@WenMeng-NOAA 
It is not `new` cmake way.  This is exactly how we build the hpc-stack.  The difference is hpc-stack is built with all the bells and whistles.  In your case, OpenMP enabled.
I just made this standalone for a user who wants full control of building the UPP and its NCEPlibs dependencies.

**Comment by WenMeng-NOAA** [comment]
On 02/25/2021, Dusan submitted the PR #269 for removing upp lib dependency on ip, sp, and w3nco. This PR is aiming to solve this UPP openmp issue.

**Comment by WenMeng-NOAA** [comment]
On 02/26/2021, Wen tested on building upp lib on Hera and WCOSS-Dell. Wen verified the -qopenmp option is not removed.

**Comment by WenMeng-NOAA** [comment]
The code handoff of new tag upp_v10.0.4 was done. The work needs to be done to verify thread safe in FV3GFS. @HuiyaChuang-NOAA Would you consider this new verifying in-line post threading procedure delivered from UPP re-factor efforts?
