### ISSUE TITLE
Radar reflectivity from UPP standalone pe tests for HAFS

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#267]
The HAFS team reported that the radar reflectivity in HAFS grib2 data files were not bitwise identical in the pe tests.

**Comment by junwang-noaa** [comment]
Thanks, Wen. Do you want to create a new tag for hpc_stack?

**Comment by WenMeng-NOAA** [comment]
Wen figured out a bug in the setting of the flag Model_Radar in subroutine MDLFLD.f. A fix will be added.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa I might use the same tag name(upp/10.0.4) after the fix is committed. The hpc-stack team doesn't like the frequent library upgrade. It would be my concern how to maintain and upgrade upp library at the hpc-stack with more ufs applications using in-line post. Do you have any suggestions?

**Comment by junwang-noaa** [comment]
Sure. that is OK.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa I recreated the tag upp_v10.0.4 based on this commit 1d3d6ff for installing upp/10.0.4 at the hpc-stack.

**Comment by junwang-noaa** [comment]
Thanks.
