### ISSUE TITLE
Fix thread violation issues in UPP

### ISSUE THREAD

**Issue by HuiyaChuang-NOAA** [NOAA-EMC/UPP#270]
A decision was made 10 years ago to focus on improving UPP's efficiency using MPI.
As a consequence, UPP has not been thread safe for at least a decade and users have
been advised to run with OMP_NUM_THREADS=1

UPP recently switched to use cmake as request from EIB.
It was quickly discovered the use of cmake in UPP compilation resulted in intrinsic use of OpenMP
which caused UPP to generate different output when using different numbers of threads both inline
and stand-alone.

Qingfu found the following fields to be different when running with different numbers of threads in inline post:
821:2269498972:vt=2019070112:4000 m above ground:12 hour fcst:REFD Reflectivity [dB]:
 822:2270643799:vt=2019070112:1000 m above ground:12 hour fcst:REFD Reflectivity [dB]:
1005:2836535014:vt=2019070112:120-90 mb above ground:12 hour fcst:TMP Temperature [K]:
1009:2852643053:vt=2019070112:120-90 mb above ground:12 hour fcst:VGRD V-Component of Wind [m/s]:
1020:2896927589:vt=2019070112:surface:12 hour fcst:4LFTX Best (4 layer) Lifted Index [K]:
 1022:2901122654:vt=2019070112:180-0 mb above ground:12 hour fcst:CIN Convective Inhibition [J/kg]:

Jesse found only Radar relativities are different in his stand-alone tests using different threads.

Qingfu provided a fix which Jesse verified fixing radar ref irreproducibility in his stand-alone tests.

**Comment by HuiyaChuang-NOAA** [comment]
Arun tasked Jim A. to help make UPP thread safe.
Wen already provided Jim a stand-alone test package. 
Huiya organized a meeting on 2/26 for all involved to discuss and mainly make sure Jim has enough information to
test his changes.

**Comment by WenMeng-NOAA** [comment]
Wen Provided an UPP standalone test case with FV3GFS configuration on Hera to Jim and Jesse at
/scratch1/NCEPDEV/stmp2/Wen.Meng/Jim.

**Comment by WenMeng-NOAA** [comment]
On 02/27/2021, Per @JamesAbeles-NOAA 's feedback 

> I made modifications to 10 routines to enable the post to get reproducible answers when run with 1 or 2 threads.
> 
> BNDLYR.f   CALPW.f   CALVOR.f   MDLFLD.f   SLP_new.f
> CALMCVG.f  CALRCH.f CALWXT_EXPLICIT.f SLP_NMM.f  SURFCE.f
> 
> The modified source code (the original source has .orig suffix) plus diffs(in file diffs)  are in 
> /scratch2/NCEPDEV/fv3-cam/James.A.Abeles/wen/EMC_post/sorc/ncep_post.fd
> 
> I can discuss the changes with you and add some comments to the diffs file if you wish. One routine I would like you to check is SLP_new.f. Please look at lines 287 and 288, 359 and 360 and 369 and 370. Please verify that the I and J indices computed will always be distinct for each KM. If they won't be , we should remove the threading from the loops.
> 
> I created a much simpler run script and made a run with 1 thread and then a loop of 10 runs with 2 threads. I compared the output from the 2 threads runs,GFSPRS.GrbF06, with the same file for the 1 thread run.
> 
> res.1t GFSPRS.GrbF06 and run 1 GFSPRS.GrbF06 are identical
> res.1t GFSPRS.GrbF06 and run 2 GFSPRS.GrbF06 are identical
> res.1t GFSPRS.GrbF06 and run 3 GFSPRS.GrbF06 are identical
> res.1t GFSPRS.GrbF06 and run 4 GFSPRS.GrbF06 are identical
> res.1t GFSPRS.GrbF06 and run 5 GFSPRS.GrbF06 are identical
> res.1t GFSPRS.GrbF06 and run 6 GFSPRS.GrbF06 are identical
> res.1t GFSPRS.GrbF06 and run 7 GFSPRS.GrbF06 are identical
> res.1t GFSPRS.GrbF06 and run 8 GFSPRS.GrbF06 are identical
> res.1t GFSPRS.GrbF06 and run 9 GFSPRS.GrbF06 are identical
> res.1t GFSPRS.GrbF06 and run 10 GFSPRS.GrbF06 are identical
> 
>  My working directory is: 
>   /scratch2/NCEPDEV/fv3-cam/James.A.Abeles/wen/work
> The loop script is run.loop.2t and the 1 thread run script, run.post.1t  
> This is not an exhaustive test I realize (I only used 1 and 2 threads), but would like you and Jesse to run some tests as well in case I have missed something. As Jesse noted, the runtime improvement with 2 threads is minimal.

**Comment by JamesAbeles-NOAA** [comment]
Found one more loop in BNDLYR.f that should not have been threaded. The code now reproduces answers for 1,2 and 4 threads. Jesse also said it does for 3 threads. I fixed the timer (using mpi_wtime) and a few non essential timers are removed. The improvement in certain routines with threading is good, but for the standalone run most of the time is in the initialization. It will be good to test this code for the inline post

**Comment by HuiyaChuang-NOAA** [comment]
@JamesAbeles-NOAA, Thank you!  Exciting news!
@JesseMeng-NOAA I assume you're running UPP GFS stand-alone test with 3 threads.  Please follow Qingfu's procedure to test Jim's version of source code  in GFS inline post.

**Comment by HuiyaChuang-NOAA** [comment]
@JesseMeng-NOAA 
Jesse, I'd also like you to start testing Jim's changes for stand-alone FV3-LAM (regional) UPP regression tests using different threads and let Jim know if FV3 regional output reproduces with different threads.  Thank you.

**Comment by JesseMeng-NOAA** [comment]
Tested standalone UPP with 1, 2, 3, 4 threads. Errors found and fixed.
Ran regression test for all the models, FV3GFS, FV3GEFS, FV3LAM, FV3HAFS, RAP, HRRR, NMMB, with 1, 2, 3, 4 threads. Results are good.
Ran FV3GFS inline post and results are good.
PR submitted pending for review.

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA Will there be changed results expected from the current UPP regression test baselines?

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA Did you conduct the tests on WCOSS-Cray and Hera? If yes, how are the results?

**Comment by WenMeng-NOAA** [comment]
> Tested standalone UPP with 1, 2, 3, 4 threads. Errors found and fixed.

@JesseMeng-NOAA Could you document the errors before and after fix?

**Comment by JesseMeng-NOAA** [comment]
> @JesseMeng-NOAA Will there be changed results expected from the current UPP regression test baselines?
No change

**Comment by JesseMeng-NOAA** [comment]
> @JesseMeng-NOAA Did you conduct the tests on WCOSS-Cray and Hera? If yes, how are the results?

Standalone tests are done on wcoss-dell and hera. All good.

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA, @JamesAbeles-NOAA, @Qingfu-Liu  Could you share with me some testing tips for identifying fields having thread safe issue? From Jesse's the UPP testing, it seems to me that we couldn't identify issue from off-line post test. I know Qingfu found the radar reflectivity issue from FV3GFS threading tests. Will the changed results be reproduceable from two threading tests or more tests?

**Comment by JesseMeng-NOAA** [comment]
> > Tested standalone UPP with 1, 2, 3, 4 threads. Errors found and fixed.
> 
> @JesseMeng-NOAA Could you document the errors before and after fix?

Radar reflectivity errors occur with OMP_NUM_THREADS=4
821:2175320360:REFD:4000 m above ground:rpn_corr=0.999998:rpn_rms=0.0149834
822:2176585918:REFD:1000 m above ground:rpn_corr=0.999982:rpn_rms=0.0495933

Bug fixed in MDLFLD.f
596c596
< !$omp parallel do private(i,j,l,dens,llmh)
---
> !$omp parallel do private(i,j,l,dens,llmh,CUREFL,FCTR,Lctop,DELZ,ze_nc)

===================================================================

Some TMP records errors occur with OMP_NUM_THREADS=4
999:2720604606:TMP:90-60 mb above ground:rpn_corr=0.999999:rpn_rms=0.0197934
1004:2739867743:TMP:120-90 mb above ground:rpn_corr=0.999993:rpn_rms=0.0528894
1014:2779035895:TMP:180-150 mb above ground:rpn_corr=0.99999:rpn_rms=0.063279

Bug fixed in BNDLYR.f
177c177
< !$omp  parallel do private(i,j,l,dp,pm,es,qsat)
<       DO L=1,LM
<          DO J=JSTA,JEND
<           DO I=1,IM
---
> !!$omp  parallel do private(i,j,l,dp,pm,es,qsat)
>       DO L=1,LM
> !$omp  parallel do private(i,j,dp,pm,es,qsat)
>          DO J=JSTA,JEND
>            DO I=1,IM

**Comment by WenMeng-NOAA** [comment]
> 999:2720604606:TMP:90-60 mb above ground:rpn_corr=0.999999:rpn_rms=0.0197934
> 1004:2739867743:TMP:120-90 mb above ground:rpn_corr=0.999993:rpn_rms=0.0528894
> 1014:2779035895:TMP:180-150 mb above ground:rpn_corr=0.99999:rpn_rms=0.063279

@JesseMeng-NOAA Were these changed results identified from the UPP standalone tests with threading or FV3GFS inline post with threading?

**Comment by JesseMeng-NOAA** [comment]
> > 999:2720604606:TMP:90-60 mb above ground:rpn_corr=0.999999:rpn_rms=0.0197934
> > 1004:2739867743:TMP:120-90 mb above ground:rpn_corr=0.999993:rpn_rms=0.0528894
> > 1014:2779035895:TMP:180-150 mb above ground:rpn_corr=0.99999:rpn_rms=0.063279
> 
> @JesseMeng-NOAA Were these changed results identified from the UPP standalone tests with threading or FV3GFS inline post with threading?

Both

**Comment by WenMeng-NOAA** [comment]
On 03/10/2021, Wen built upp lib with the PR#275 at /u/Wen.Meng/noscrubd6/ncep_post/jesse/EMC_post/tests/install on Venus and provided to the RRFS team and HAFS team to test in their application's inline post.

**Comment by JesseMeng-NOAA** [comment]
It was found in the initial multi-threads tests that some output fields were not reproduced and also the performance was degraded in runtime. Some of the openmp code were incorrect and/or unnecessary.  After the fix, regression tests were re-run for various threads for multiple times and results were satisfied.

Runtime performance examples:

1 thread
03/03 21:09:12Z -Runtime: fv3gfs_test 00:11:43 -- baseline 00:18:00
03/03 21:09:57Z -Runtime: fv3gfs_pe_test 00:12:15 -- baseline 00:18:00
03/03 21:09:58Z -Runtime: fv3r_test 00:02:57 -- baseline 00:03:00
03/03 21:09:58Z -Runtime: fv3r_pe_test 00:02:26 -- baseline 00:03:00

Initial 4 threads test (error and inefficient)
03/04 21:23:57Z -Runtime: fv3gfs_test 00:13:35 -- baseline 00:18:00
03/04 21:24:43Z -Runtime: fv3gfs_pe_test 00:14:11 -- baseline 00:18:00
03/04 21:24:58Z -Runtime: fv3r_test 00:12:24 -- baseline 00:03:00
03/04 21:24:58Z -Runtime: fv3r_pe_test 00:11:54 -- baseline 00:03:00

Updated 4 threads test (efficiency improved)
03/23 16:45:21Z -Runtime: fv3gfs_test 00:12:28 -- baseline 00:18:00
03/23 16:45:51Z -Runtime: fv3gfs_pe_test 00:13:01 -- baseline 00:18:00
03/23 16:45:52Z -Runtime: fv3r_test 00:03:27 -- baseline 00:03:00
03/23 16:45:52Z -Runtime: fv3r_pe_test 00:02:50 -- baseline 00:03:00
