### ISSUE TITLE
Update UPP local memory allocation 

### ISSUE THREAD

**Issue by BoCui-NOAA** [NOAA-EMC/UPP#276]
In UPP, many of the 3-D arrays have been allocated as  X( im,jsta_2l:jend_2u,lm), the exact size based on the number of MPI tasks.  
Some 2-D arrays continue to be dimensioned (im,jm). This task is to improve them to be X( im,jsta_2l:jend_2u) if possible.

The table below lists UPP subroutines that have been reviewed and modified. I will continue working on the left codes and keep update it。

https://docs.google.com/spreadsheets/d/10jlqaBHlcg8xHHc4kH1JWJbTPGMcZeZLNbMCszdza2c/edit?usp=sharing

@WenMeng-NOAA @HuiyaChuang-NOAA

**Comment by BoCui-NOAA** [comment]
The changes are saved at:
https://github.com/BoCui-NOAA/EMC_post/tree/upp_local_memory

**Comment by HuiyaChuang-NOAA** [comment]
Bo, thank you for documenting your changes in a Google doc and also update this Github issue.
Let's discuss your work at next week's monthly UPP re-engineering tag-up.

Huiya

**Comment by BoCui-NOAA** [comment]
Updated document and submit pull request #284.

**Comment by WenMeng-NOAA** [comment]
@BoCui-NOAA Did you conduct the UPP standalone tests? If yes, document the results and platforms.

**Comment by BoCui-NOAA** [comment]
Run UPP standalone tests on Dell.  The specified models include nmmb, gfs, gefs, fv3r, rap and  hrrr. The results look fine.

I will test hafs.

**Comment by BoCui-NOAA** [comment]
UPP standalone test for hafs on Dell is done. Results are fine.

**Comment by BoCui-NOAA** [comment]
Wen,

I run UPP standalone tests on Luna. The rt_log* file shows that fv3hafs test did not generate bit-identical results. But the *diff files in temporary directory didn't have any record. Do you think is it acceptable? The results are located at:
/gpfs/hps3/emc/ensemble/save/Bo.Cui/post_regression_test_new/scripts/rt.log.WCOSS_C
/gpfs/hps3/ptmp/Bo.Cui/upp_ref_bocui

Thanks!

@WenMeng-NOAA @GeorgeVandenberghe-NOAA

**Comment by WenMeng-NOAA** [comment]
@BoCui-NOAA It would be fine as long as there are no unexpected changes in field values.
