### ISSUE TITLE
Can CRTM submodule be deleted?

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/UPP#281]
The CRTM submodule on the develop branch is no longer used by the DTC build (the CRTM code is contained in NCEPLIBS and the CRTM fix files are now downloaded separately). Does anyone else make use of this submodule, or can it be deleted from the develop branch?

**Comment by fossell** [comment]
@mkavulich No, this was only for DTC. It can be removed.

**Comment by WenMeng-NOAA** [comment]
@mkavulich and @fossell For NCEP implementation, we use CRTM from the dev. hpc-stack or NCEP ops. libraries sites.

**Comment by WenMeng-NOAA** [comment]
@mkavulich and @fossell Is the solution of this issue included in the PR #295?

**Comment by fossell** [comment]
@WenMeng-NOAA - Yes, I will try to finish that PR up today.
