### ISSUE TITLE
duplicate code in SURFCE.f

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/UPP#288]
The code in lines 5860-5909 are identical to lines 5912-5960 in SURFCE.f. So the field AKHS and AKMS (iget(503) and iget(504)) will be output twice if requested. Please remove lines 5912-5960 in  SURFCE.f

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa The changes were committed in my working branch post_xml_unify at
https://github.com/WenMeng-NOAA/EMC_post/commit/5e88b061c68a20d7e5295ad4644cdf76b251fa34

**Comment by WenMeng-NOAA** [comment]
The changes are combined in PR #289. With this update, the baselines for NMMB BGRD3D dataset and FVLAM PRSLEV dataset will be changed.
