### ISSUE TITLE
GSD specified fields cloud base height(711) and pressure(798) in pe test

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#290]
The GSD specified fields cloud base height (711) and pressure (798) are not generated bitwise results in the UPP pe regression 
tests.  A sample from  regression tests for rap. The results generated with 48 tasks (24 per node) are not bitwise identical to the results generated with 36 tasks (24 per node) on Hera. These two tests can be access at /scratch1/NCEPDEV/stmp2/Wen.Meng/case on Hera.

**Comment by WenMeng-NOAA** [comment]
The user guidance for running UPP regression tests can be found at
https://docs.google.com/document/d/1gtk1DBxEa9GsaWbxrxtB4Ot7U_lNIHjLXaU2F6FyD7M/edit

**Comment by SamuelTrahanNOAA** [comment]
Did you test this after #286? The bug that PR fixed would have produced non-deterministic output from that region of the code.

**Comment by WenMeng-NOAA** [comment]
Yes. The changed results from pe tests exist before #286 and after #286.
