### ISSUE TITLE
initialize all the allocated post variables

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/UPP#291]
In Post code, when the internal variables are allocated, they need to be initialized. The uninitialized variables could cause run-to-run reproducibility issues when the fields are requested to output.

**Comment by WenMeng-NOAA** [comment]
The changes are made in Wen's branch post_initial for:
1) Initialize all variables in ALLOCATE_ALL.f with spval except u(:,:,:) and v(:,:,:).
2) Initialize u/v in ALLOCATE_ALL.f with value 0. (There might be a enhancement for vucsh/vvcsh 0-1km above ground which require u/v for fv3lam in the future. Currently u/v for fv3lam are not defined.)
3) Set spval as 9.99e20 for all fv3 applications in WRFPOST.f.
The PR #293 was submitted.

**Comment by WenMeng-NOAA** [comment]
The regression tests were conducted. With this PR, there will be changed results for:
fv3lam dataset PRSLEV
45:70499675:VIS:cloud top:rpn_corr=0.999954:rpn_rms=132.225
1079:1644957928:d=2019062000:MXSALB:surface:6 hour fcst::ndata=3754001:undef=3754001:mean=0:min=0:max=0

nmmb--
43:18622202:VIS:cloud top:rpn_corr=0.817364:rpn_rms=3461.3
