### ISSUE TITLE
Read maximum snow albedo from fv3lam and hafs history file

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#296]
The maximum snow albedo is output in fv3lam and hafs model history file but isn't  read by the regional fv3 read interface for
 off-line  post.

**Comment by WenMeng-NOAA** [comment]
The fix was added Wen's branch post_snoalb and submitted the PR #298.

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted on Hera. With this fix, the changed results in fv3lam are:
dataset PRSLEV06.tm00--
From 
1079:1644515289:d=2019062000:MXSALB:surface:6 hour fcst::ndata=3754001:undef=3754001:mean=0:min=0:max=0
into 
   1079:1644515289:d=2019062000:MXSALB:surface:6 hour fcst::ndata=3754001:undef=0:mean=34.6073:min=0:max=84:cos_wt_mean=33.802

**Comment by junwang-noaa** [comment]
Wen, would you please check if you get run-to-run reproducibility for this
field from the latest POST code?

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa From the current UPP version, the UPP standalone test shows MXSALB in fv3lam dataset has all zero values.

**Comment by junwang-noaa** [comment]
I mean your updated code with PR#298. If you make several runs, do the
results reproduce?

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa I ran the UPP standalone regression tests at least two times with the commit from PR #298. MXSALB is all zero values. My understanding is that unproducible MXSALB issue was from from inline post only due to unitarizing snoalb.

**Comment by junwang-noaa** [comment]
Thanks. I will try the upp lib you built, if it fixes the lam inline post,
I will wait for a new UPP lib before we turn the lam inline post test back
on.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa I would like to confirm with you that snoalb from model history file has valid values range at (0, 100) instead of (0,1).

**Comment by WenMeng-NOAA** [comment]
@ericaligo-NOAA 

Eric,

I would like you to be warn of this upcoming PR #298 for the impact on fv3lam dataset. Please let me know if you have any concerns/suggestions. Thanks!
