### ISSUE TITLE
Resolve tag naming conventions

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/UPP#297]
There is an inconsistency in the way that various EMC_post tags are named. DTC/community UPP tags have been named with dashes (e.g. upp-v9.0.0, ufs-v1.1.0) whereas EMC/operational tags have been named with underscores (e.g. upp_v10.0.0, upp_gfsv16_release.v1.1.1). This led to some confusion when creating the latest community release, as some links were created with underscores and others with dashes. It may be beneficial to agree on a common format for tags going forward.

**Comment by WenMeng-NOAA** [comment]
For NCEP model suite implementation, we use naming tags based on model developer's preference (e.g. upp_gfsv16_release.vX.X.X).  The tags upp_v10.X.X were created from the develop branch and used for installing upp lib at the hpc-stack for in-line post in ufs-weather-model only.

**Comment by fossell** [comment]
Public release tag name issue has been resolved - the Github release was edited to point to upp_v9.0.0 and all links updated appropriately.  

*** Moving forward we will continue to use underscore in the release tag names to remain consistent across releases. ***
