### ISSUE TITLE
Initializing aextc55 and extcof55 in all FV3 model read interfaces

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#300]
In order to calculating GSL visibility, the aextc55 and extcof55 are needed to be set as 0 in the read interface if the model history
file doesn't include them.

**Comment by WenMeng-NOAA** [comment]
@yangfanglin, @EricRogers-NOAA, @HuiyaChuang-NOAA  
Fanglin/Eric/Huiya,
The aextc55 and extcof55 are initialized with the UPP filling value (9.99+20) in ALLOCATE_ALL.f. That might cause GSL visibility computation failure. I plan to file a new UPP PR for setting aextc55 and extcof55 as 0 in the FV3GFS read interface INITPOST_GFS_NETCDF_PARA.f and regional FV3 read interface INITPOST_NETCDF.f  for off-line post. Please let me know your thought. Thanks!

**Comment by junwang-noaa** [comment]
@WenMeng-Noaa, can we initialize aextc55 and extcof55 with value 0. in
ALLOCATE_ALL.f so that we don't need to initialize it again in both inline
post and standalone post interface? If those two fields are in history
files, new values can be read in and replace the default 0..

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa Good suggestion. I will do that. But this change would be reflected  in the next upp library upgrade (we just upgrde upp/10.0.6). Please let me know if it works for you.

**Comment by junwang-noaa** [comment]
Ok, that is fine, I will keep the initialization in UFS inline post when
using upp 10.0.6.

**Comment by HuiyaChuang-NOAA** [comment]
@WenMeng-NOAA Thank you Wen, for catching this.  @junwang-noaa Good suggestion.

**Comment by WenMeng-NOAA** [comment]
The changes were added in my branch post post_aextc55 and submitted the PR #301.

**Comment by WenMeng-NOAA** [comment]
The test were conducted on WCOSS-Dell. With the PR #301, the changes in fv3lam datasets are:
----------------
PRSLEV06.tm00--
1)
From
   [Wen.Meng@v71a1 data_out]$ wgrib2 PRSLEV06.tm00.WCOSS_DELL_P3 -match SNFALB -stats -s
1078:1644513140:ndata=3754001:undef=0:mean=0.0120296:min=0:max=100:cos_wt_mean=0.00935122:d=2019062000:SNFALB:surface:6 hour fcst:
Into
   [Wen.Meng@v71a1 fv3r_2019062000]$ wgrib2 PRSLEV06.tm00 -match SNFALB -stats -s
1078:1644514027:ndata=3754001:undef=3754001:mean=0:min=0:max=0:d=2019062000:SNFALB:surface:6 hour fcst:
 
2) GSL visibility changed result
    45:70499675:VIS:cloud top:rpn_corr=0.999954:rpn_rms=132.225
