### ISSUE TITLE
value of CONST1 used for visibility

### ISSUE THREAD

**Issue by Steve-Albers** [NOAA-EMC/UPP#302]
I would like to suggest trying to migrate to using a value of 3.00 ( -ln(.05) ) more uniformly in the UPP code. This would make visibility calculations more compatible with the METAR definition of visibility. It is my understanding that the instrumentation presently used by METARs utilizes a 5% contrast threshold instead of 2%.

A reference mentioning this is here:

https://www.metoffice.gov.uk/weather/guides/observations/how-we-measure-visibility

Another one is Attachment D in this document (search for Koschmeider):

https://www.icao.int/airnavigation/IMP/Documents/Annex%203%20-%2075.pdf

This references also mentions the 0.05 threshold:

https://www.biral.com/wp-content/uploads/2015/02/Introduction_to_visibility-v2-2.pdf

**Comment by Steve-Albers** [comment]
A reference mentioning this is here:

https://www.metoffice.gov.uk/weather/guides/observations/how-we-measure-visibility

**Comment by HuiyaChuang-NOAA** [comment]
Thank you for the suggestion which comes in a good timing.  We're in the process of unifying visibility computation toward using
CALVIS_GSD for all models supported by UPP.  Looking at this subroutine, GSD already switched to use CONST1= 3.000 for RAP/HRRR.  We will plan on doing this for all models assuming no objections from EMC and GSL.

@WenMeng-NOAA I will start an email exchange with EMC Physics group and GSL colleagues to remove model name dependency in CALVIS_GSD

**Comment by Steve-Albers** [comment]
Thanks much Huiya for the response and update. I had played a role in the earlier change to CALVIS_GSD and it's good to hear this can be streamlined further.

A code search reveals that CONST1 is used in CALVIS_GSD.f, CALVIS.f, and CLDRAD.f and perhaps these occurrences can all be considered.

Another thing I noticed in CALVIS_GSD.f is the following line:

VIS(I,J)=MIN(90.,CONST1/BETAV+extcof55(i,j,lm))      ! max of 90km

Here I wonder if 'extcof55' should also be operated on by CONST1? We might be lucky things work in this case as it seems 'extcof55' isn't presently being utilized and may have a value of zero if I recall correctly. Perhaps the parentheses can be rearranged in this line? Something like this:

VIS(I,J)=MIN(90.,CONST1/(BETAV+extcof55(i,j,lm)))      ! max of 90km

**Comment by WenMeng-NOAA** [comment]
@Steve-Albers 

> VIS(I,J)=MIN(90.,CONST1/(BETAV+extcof55(i,j,lm))) ! max of 90km

Thanks for catching this bug. I will submit a fix soon. Then we will work on unifying CONST1 after coordinating with model developers at EMC and GSL later.

**Comment by WenMeng-NOAA** [comment]
@Steve-Albers I would ask the admin of the organization NOAA-EMC  to add in your github user name so that you can be a contributor or code reviewer at EMC_post repository. Please let me know if this plan works for you. Thanks!

**Comment by Steve-Albers** [comment]
Sounds good WenMeng - thanks. I'd be happy to be included as a contributor and code reviewer.

**Comment by WenMeng-NOAA** [comment]
@Steve-Albers The fix was committed in @JesseMeng-NOAA 's PR #306. You may review the change at
https://github.com/NOAA-EMC/EMC_post/commit/bdf65580c72ff33e6f7c941aca75565260607785

**Comment by WenMeng-NOAA** [comment]
@Steve-Albers 

> Steven should now have an email from GitHub inviting him to join the NOAA-EMC org there. Once he accepts he'll be in the memberlist. Thanks!

Please see our Admin's response of inviting you being code contributor and code reviewer at EMC_post repository. Thanks!

**Comment by WenMeng-NOAA** [comment]
On 04/20/2021, Huiya proposed the changes in GSL visibility algorithms as:
I looked through CALVID_GSL and saw there are two places where thresholds
are set differently for RAP versus other models:

> 1. Line 180: Const1 is set to 3 for RAP.  According to a user who submitted a
> Github ticket, this should be a correct value consistent with Metar.  
> I propose that we remove if condition and use Const1=3 for all models
> 
> 2. Line 242: the base value for RH attenuation on visibility is set to 90 km for
> RAP but 60 km for other models.  I am wondering if using 90 km for GFS visibility based on GSL algorithm would have reduced <10 mile high
>  frequency bias as shown in Shannon's verification plots?  I did a quick calculation and with current 60 km RH attenuation base value, 50% RH corresponds to 10 miles visibility while using 90  km RH attenuation base value would change visibility to 16 miles.
> I propose we use 90 km RH attenuation base value for all models based on
> above rough estimate  I am hoping GSL colleges can give us feedback on why they switch to 90 km.

**Comment by WenMeng-NOAA** [comment]
On 05/13/2021, Eric James sent feedback as:

> Thanks for following up about the CALVIS_GSD code, and sorry for the late response!  Regarding your point (1), we switched the Const1 variable to 3.0 to be consistent with the AWOS calculation for METARs.  So we agree that it would be good to switch to use Const1 = 3.0 for all models.

**Comment by WenMeng-NOAA** [comment]
On 05/13/2021, Stan Bejamin sent feedback as:

> Yes, you have the right idea on increasing the attenuation base value from 60km to 90km - to avoid or at least minimize too much low visibility in clear-air regions without cloud hydrometeors.   So yes, we agree to make that change for UPP in general.
> 
> Background: In our GSL group, until looking more closely at Alaska results, we had not considered too much that value.  In the lower 48 US (CONUS), the flight restrictions only were important with visibilities of 3 miles or less.   But in Alaska and with lots of general aviation (small aircraft) flights through mountainous terrain, their aviation community cared a great deal about visibility at 5 mi and 10 mi.   By making this change, we were able to remove a too-high bias for 5-mi and 10-mi visibility (starting with RAPv4 and HRRRv3 in 2018), even in the 0h RAP/HRRR.
> 
> I think that all of the models will have approximately the same RH range, so, yes, it’s a good update for UPP for all models including for GFS.  It’s helpful that all of the NOAA models now are reporting RH as RH with respect to water saturation under all conditions.
> 
> There is a little more information on the vis diagnostic on p. 34 of this tech memo
> https://rapidrefresh.noaa.gov/Diag-vars-NOAA-TechMemo.pdf .

**Comment by WenMeng-NOAA** [comment]
Wen will submit PR for unifying CONST1 and RH attenuation in CALVIS_GSD.f.

**Comment by WenMeng-NOAA** [comment]
The changes would have impact on GSL visibility like:
------------
[Wen.Meng@llogin2 ptmp]$ cat fv3r_2019062000/PRSLEV06.tm00.diff
45:70499700:VIS:cloud top:rpn_corr=0.999335:rpn_rms=10219.7

**Comment by WenMeng-NOAA** [comment]
From the UPP regression tests, the changes will only have impact on GSL visibility field in the datasets of all applications.
