### ISSUE TITLE
Bug in GSD Visibility Computation

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#305]
Steve Albers pointed out that a bug in GSD visibility computation in the issue #302. 
Change
VIS(I,J)=MIN(90.,CONST1/BETAV+extcof55(i,j,lm)) ! max of 90km
into
VIS(I,J)=MIN(90.,CONST1/(BETAV+extcof55(i,j,lm))) ! max of 90km

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA Could you combine this fix in your PR #306? Thanks!

**Comment by JesseMeng-NOAA** [comment]
> @JesseMeng-NOAA Could you combine this fix in your PR #306? Thanks!

Done!
