### ISSUE TITLE
wafs dataset generation failure at operational GFS post job

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#329]
On 06/05/2021, NCO SPAer Alexander Richert reported t18z gfs post f108 failure as:

> jgfs_atmos_post_f108 has failed a few times now. The issue appears to be the wafs component; the goes part completes/alerted to dbnet.
> 
> LSF output file: /gpfs/dell1/nco/ops/com/output/prod/20210605/gfs_atmos_post_f108_18.o60308168
> DATA dir: /gpfs/dell1/nco/ops/tmpnwprd/jgfs_atmos_post_f108_18.60308168
> 
> Please let me know if there's anything else I can provide you.

**Comment by WenMeng-NOAA** [comment]
Alex found the root cause of failure as:

> As I suspect the GFS folks have found, it appears to be excessive u-component wind speed in (if I did my math right) South America. It runs through if I take out the value check (abs(ugm(i,j,k)) has to be <300 in gtg_indices.f90). Would it be safe to just remove the 'call abort' so the time gets skipped but doesn't cause the whole program to die? Or would bad things happen if we ignored the bad windspeed value?

**Comment by WenMeng-NOAA** [comment]
On 06/05/2021, @yangfanglin suggested the temporary fix as:

> I checked winds in the model forecast file gfs.t18z.atmf108.nc.  Indeed there are very strong winds greater than 300 m/s near the model top (~80km altitude) close to the Andes at about 45S.   In Australia winter, winds can get very strong in the upper mesosphere, although reaching 300 m/s is rare.
> 
> I'd suggest either remove this check or use a much larger number, say 400 m/s.   Note that if the model top is further raised up into the ionosphere and thermosphere, winds can even reach thousands of meters per second.

**Comment by WenMeng-NOAA** [comment]
On 06/07/2021, @YaliMao-NOAA reached out the gtg code developer for the fix as:

> Based on the feedback from NCAR,  the fix can be to change the u/v max bound from 300 to 500m/s.
> For the max limits of other fields, the current settings are fine.

**Comment by WenMeng-NOAA** [comment]
On 06/07/2021, Steven Earle commented:

> I'd like to see Alex's questions answered before we move forward to this. On the surface, it seems like an arbitrary number; is there data behind the suggestion to move to 500m/s? Regardless of this, as Alex said, is it the WAFS responsibility to quality control GFS forecast output? Do we really want a hard failure of the GFS post (which has massive impacts downstream because pgrb processing is also in this job) when GFS forecast output goes above certain thresholds? What's the impact if the exceedance of all possible thresholds like this resulted in warnings instead of hard failures?

**Comment by WenMeng-NOAA** [comment]
On 06/07/2021, @HuiyaChuang-NOAA suggested the fix as:

> We corresponded with NCAR and they feel a warning of high wind will help debugging should
> there be an issue with WAFS products.  Thus, we're proposed making the following two-folds changes:
> 
> 1. modify the GTG source code: when there is a high wind (>500 m/s), send out a warning WITHOUT error message
> and let the computation continue;
> 2. modify the script so the WAFS failure will not affect generation of GFS pgb files
> 
> Please let us know what you think.  Yali has started making the above changes.
> 
> We will revisit all these error checking with NCAR when preparing for GFS V17 implementation.

**Comment by YaliMao-NOAA** [comment]
Two types of tests are done for this fix.
1. Submit a job with different task numbers, both results are bit-wise identical to each other.
2. To test the script change, I purposely copied the current operational ncep_post executable file to my local working directory and ran the same case with extreme strong winds. err=134 showed up as expected but didn't crash the entire job.

**Comment by WenMeng-NOAA** [comment]
The fixes were incorporated in GFS V16 implementation branch release/gfs_v16 and will be implemented in GFS V16.1.2.
