### ISSUE TITLE
Port to S4

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UPP#341]
EMC_post should be ported to SSEC's S4 cluster to enable UFS and DA research efforts on that system.

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA No one in EMC UPP group has S4 cluster access. Will you or some one with S4 cluster account work on this? We can  merge the PR into develop branch. Thanks!

**Comment by DavidHuber-NOAA** [comment]
@WenMeng-NOAA Yes, I am currently working on this port.  I am unable to self-assign it, but I'd appreciate it if you would assign it to me.  Thanks!

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA Appreciate your help. You may follow the UPP code contribution procedure at
https://github.com/NOAA-EMC/EMC_post/wiki/UPP-Code-Development#contribute-changes-in-upp-main-development-branch-develop
Please let me know if you need further information from me. Thanks!

**Comment by DavidHuber-NOAA** [comment]
@WenMeng-NOAA Though it's not required for the global workflow, I see that there are [module files](https://github.com/NOAA-EMC/EMC_post/tree/develop/modulefiles/upp) and a [build script](https://github.com/NOAA-EMC/EMC_post/blob/develop/sorc/ncep_post.fd/build_upp_lib.sh) for the UPP library.  The [makefile ](https://github.com/NOAA-EMC/EMC_post/blob/develop/sorc/ncep_post.fd/makefile_lib) for the UPP library seems incomplete, however.  It is missing at least the UPP_PHYSICS.f module and it has at least one extra module listed in it that does not exist (CALCAPE.f).  Thus, it seems that I am unable to test this build on S4 and so I'm not planning on including a module file for S4.  Are there plans to fix these issues or is this a deprecated library?

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA The build script and module files you mentioned are legacy build feature. Now wen use the script in tests/compile_upp.sh to build upp executable or lib via cmake with all dependency modules/libs from the hpc-stack.   The new UPP build procedure can be found at https://github.com/NOAA-EMC/EMC_post/wiki/Building-UPP.  The resource of hpc-stack can be found at https://github.com/NOAA-EMC/hpc-stack.

**Comment by DavidHuber-NOAA** [comment]
@WenMeng-NOAA Alright, thanks for the confirmation.
