### ISSUE TITLE
Add UPP regression tests

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#345]
Add  UPP regression tests in the UPP repository.

**Comment by gspetro-NOAA** [comment]
@WenMeng-NOAA Can this be closed in light of the current RT framework? It seems like specific enhancements could be covered in a new issue, if desired.

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA Yes, we can close it as solved.
