### ISSUE TITLE
bug in creating GOES brightness temperature 

### ISSUE THREAD

**Issue by fanqi203** [NOAA-EMC/UPP#352]
In the file CALRAD_WCLOUD_newcrtm.f.

When ivegsrc==1, the variable snoeqv is assigned to replace sno(i,j) when calculating the snow fraction in the call to SNFRAC.

However, the sno(i,j) was still used, inadvertently, in the call to SNFRAC, which caused the problem.

The solution is to change "SNO(I,J)" to "snoeqv." in the highlighted section.

**Comment by WenMeng-NOAA** [comment]
@fanqi203 Would you please upload a few images of  your verification on the fix? Thanks!

**Comment by fanqi203** [comment]
here is an image of the verification. 
![image](https://user-images.githubusercontent.com/13813022/127870681-1f575a04-d401-4d10-adde-b2eecbe65382.png)

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted. The baseline of GFS V16 will be changed in the dataset *special*. 
The plot of difference of before and after fix in SBTAGR13 is:
![image](https://user-images.githubusercontent.com/48260754/127907905-f301c27f-f042-41e0-b256-d0c812e401d2.png)

**Comment by hertneky** [comment]
@WenMeng-NOAA Is this only for SBTAGR13 or are all GOES-16 bands effected?

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA Is this only for SBTAGR13 or are all GOES-16 bands effected?

@hertneky This would have impact on GOES-16/17 nadir and non-nadir products. @fanqi203 might chime in.

**Comment by WenMeng-NOAA** [comment]
Here is another test from RRFS:
![image](https://user-images.githubusercontent.com/48260754/127913387-34259e57-c137-4978-ac36-c655bdcd3e26.png)

**Comment by fanqi203** [comment]
Tracy,

This affects multiple products (see the attached two screenshots) when UPP
is not run for products from "NCAR" or "RAPR" modes.

Shaowu

[image: image.png]

[image: image.png]
