### ISSUE TITLE
Correction to the effective layer top and bottom calculation

### ISSUE THREAD

**Issue by EdwardColon-NOAA** [NOAA-EMC/UPP#357]
Here is a brief explanation about the code:

The key modifications are constrained to the following subprograms

MISCLN.f
UPP_PHYSICS.f
TTBLEX.f 

and are divided into two user-selectable schemes:

Scheme 1 (default):  Uses the current available routines in UPP as much as possible. It uses CALCAPE to compute the CAPE/CIN for all air parcels on each vertical model level, and do this in a loop from bottom to top of model. So the CAPE/CIN for each air parcel in the 3-D model domain are computed, then check with the criteria of CAPE/CIN to find the base and top of EL. To save memory, actually no 3-D array of CAPE/CIN is used.  Due to the current subroutine CALCAPE is designed to compute the CAPE/CIN for all air parcels in a 2-D plane, so this scheme computes CAPE/CIN for all parcels in 3-D domain.

Scheme 2: Similar to scheme 1. Based on subroutine CALCAPE (which is used for all air parcels in a 2-D plane), a new routine CALCAPE1D which computes CAPE/CIN for all air parcels along 1-D sounding profile, or say, column has been created. With this new routine, one can compute the CAPE/CIN for any given sounding profile easily. And I can output the vertical moist-adiabat profile of the specific air parcel and double check the results. Actually scheme 2 is used to verify the results from scheme 1. Based on my testing case, the bases and tops of EL found by scheme 1 and 2 are almost identical (only about 20 grid points are different). 

Code description::
(1) TTBLEX.f (line 120 ~ 240): a new routine TTBLEX1D was added (specifically used for subroutine CALCAPE1D), based on original routine TTBLEX which is CALCAPE for air parcels in 2-D plane.
(2) UPP_PHYSICS.f (line 2580 ~ 3014): adding a new routine CALCAPE1D
(3) MISCLN.f (line 3419 ~ 3749):
adding code to search for the effective layer.
scheme 1: line 3438 ~ 3491. Using CALCAPE to compute CAPE/CIN for all air parcels level by level
scheme 2: line 3492 ~ 3688. Finding air-parcel with max theta-e along the sounding profile/column on each grid box for sanity check first, then compute cape/cin of the all 1-D air parcels along that each profile if the sanity check is passed for this column/profile.
line 3689 ~ 3749: additional output to print out the profiles, positions of EL, etc for code debugging.

line:3934 ~ 3943:  Array LLOW and LUPP are used to store the base and top of EL for other related variables (like helicity).

!---  IF USSING EL BASE & TOP COMPUTED BY NEW SCHEME FOR THE RELATED VARIABLES
         IF ( EL_SCHEME > 0 ) THEN
!$omp parallel do private(i,j)
           DO J=JSTA,JEND
             DO I=1,IM
                LLOW(I,J) = EL_BASE(I,J)
                LUPP(I,J) = EL_TOPS(I,J)
             ENDDO
           ENDDO
         END IF
So if set EL_SCHEME =1 or 2 in the beginning of code, then the EL found by new scheme is used, otherwise the EL of old scheme is used.

Usage:
In MISCLN.f:
line 199: debugprint = .TRUE.   (if set to .FALSE., then no additional output. Those outputs are in text format and very huge, better turned off after further testing.)
line 200: EL_SCHEME = 1 
            any negative number , or 0-->  OLD scheme;  
            1 -->  scheme 1;  
            2 -->  scheme 2
Note: if set EL_SCHEME =1 or 2 in the beginning of code, then the EL found by new scheme is used, otherwise the EL of old scheme is used.

**Comment by WenMeng-NOAA** [comment]
The rtma WRFTWO dataset will have changed results as:
------------
155:124468303:EFHL:surface:rpn_corr=0.461903:rpn_rms=35.5199
156:124649091:EFSH:level of free convection:rpn_corr=-0.129192:rpn_rms=1820.59
157:124998736:EFSH:equilibrium level:rpn_corr=0.0708612:rpn_rms=1950.37
158:125578517:UESH:level of free convection:rpn_corr=0.112788:rpn_rms=1.96378
159:125665943:VESH:level of free convection:rpn_corr=0.22116:rpn_rms=2.91733
160:125995225:ESHR:level of free convection:rpn_corr=0.474934:rpn_rms=2.57119
