### ISSUE TITLE
Port UPP for GFS V16 to WCOSS2

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#363]
Update the branch release/gfs_v16 to support GFS V16 on WCOSS2.

Related issue:

- https://github.com/NOAA-EMC/global-workflow/issues/398

**Comment by WenMeng-NOAA** [comment]
Wen created a feature branch post_gfsv16_wcoss2 for porting UPP for GFSV16 on WCOSS at
https://github.com/WenMeng-NOAA/UPP/tree/post_gfsv16_wcoss2

**Comment by WenMeng-NOAA** [comment]
**Build an UPP executable for GFSV16 on wcoss2 Cactus:**
```
$ git clone --branch post_gfsv16_wcoss https://github.com/WenMeng-NOAA/UPP.git
$ cd UPP/sorc
$ ./build_ncep_post.sh
```
The executable "ncep_post" will be created under UPP/exec/.

**Comment by WenMeng-NOAA** [comment]
The upp/8.0.11 module for GFSV16 is available on Cactus for testing GFSV16 inline post.
To load it:
```
module use /u/Wen.Meng/noscrub/ncep_post/LIBS/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.4
module load upp/8.0.11
```

**Comment by WenMeng-NOAA** [comment]
@KateFriedman-NOAA I would like to bump up upp lib version to 8.1.0 on wcoss2. You may load a testing upp lib on Cactus as:
```
module use /u/Wen.Meng/noscrub/ncep_post/LIBS/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.4
module load upp/8.1.0
```

**Comment by KateFriedman-NOAA** [comment]
> ```
> module use /u/Wen.Meng/noscrub/ncep_post/LIBS/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.4
> module load upp/8.1.0
> ```

Got it, thanks for the update!

**Comment by WenMeng-NOAA** [comment]
The tag upp_v8.1.0 was created for GFS V16 implementation on WCOSS2.
