### ISSUE TITLE
Transition UPP to use CRTM v2.4 for RRFS implementation

### ISSUE THREAD

**Issue by HuiyaChuang-NOAA** [NOAA-EMC/UPP#365]
Per email exchange with Daryl, DA group is planning to use CRTM V2.4 for RRFS implementation.

Haixia added the following lines to DA CRTM interface to adjust to CRTM V2.4 and recommended UPP does the same:

------------------------------------------------------------------------------------------------------
do ii=1,n_clouds_fwd_wk
           if(cloud_cont(k,ii) > 1.001_r_kind*1.0E-6_r_kind .and. atmosphere(1)%cloud_fraction(k) < 1.001_r_kind*1.0E-12_r_kind) then
                   atmosphere(1)%cloud_fraction(k)=1.001_r_kind*1.0E-12_r_kind
                 end if
              end do
-----------------------------------------------------------------------------------------------------------------

Per Emily: In CRTM 2.3.0.  Users do not have to provide cloud fraction profiles from the model for cloudy radiance calculation.  It is assumed overcast if cloud fraction is not provided.  In CRTM 2.4.0, the cloud fraction profile is required for cloudy radiance calculation

**Comment by HuiyaChuang-NOAA** [comment]
Emily indicated DA should be done with transitioning to crtm c2.4 at the end of Sep.
Huiya organized an Oct 4 meeting with Emily and Haixia to get their help transitioning UPP to use crtm 2.4.
This issue will be put on hold till then.

**Comment by BenjaminTJohnson** [comment]
@WenMeng-NOAA @HuiyaChuang-NOAA @jasonotkin @gthompsnJCSDA     All:  Jason / Curtis Alexander / Geoff Manikin and JCSDA collaborators (me included) have a funded proposal that partly includes the update of UPP to use CRTM v2.4.   We're more than happy to kickstart this process.

**Comment by WenMeng-NOAA** [comment]
This issue was solved with PR #554 merged.
