### ISSUE TITLE
Bug fix release for public-v2/upp_v9.0.0

### ISSUE THREAD

**Issue by fossell** [NOAA-EMC/UPP#368]
A bug fix release will be created to address a few minor bugs in upp_v9.0.0. This will be done in conjunction with a bug fix release by SRW as well.  The UPP bugs to be applied are listed below.  The release tag will be upp_v9.0.1.

**Bug fixes to be cherry-picked from develop branch and applied to public-v2:**

1. Run script bug with fhrs in filename. Described in #356.  Fix has been identified and already in develop branch with commit 199e418 described in #307
2. GOES satellite fix described in #352 and fixed in #353. 

**Documentation update:**

1. Update to UPP grib2 table to include GOES-16/17
https://upp.readthedocs.io/en/upp_v9.0.0/UPP_GRIB2_Table.html

**Comment by fossell** [comment]
There is a significant issue with the GOES bug fix from #353 when merged into the public-v2 branch and tested with SRW output. Further testing indicates unreasonable GOES brightness temps when running SRW app output through the develop branch as well. We suspect an incompatibility issue with the SRW configuration and develop branch and/or this GOES bug fix.  

For the purposes on this upp_v9.0.1 bug fix release, this GOES #353 bug fix will be omitted since it is not confirmed to be needed in this branch.

**Comment by fossell** [comment]
Fixed with #369.

**Comment by fossell** [comment]
Closed wrong issue initially. This will stay open until SRW completes test and new upp_v9.0.1 tag created and released.

**Comment by fossell** [comment]
@jwolff-ncar @mkavulich - We have completed testing for the upp bug fix v9.0.1.  The branch release/public-v2 is ready for your SRW testing. The bug fixes applied can be found in #369, note no code changes ended up being applied.

**Comment by jwolff-ncar** [comment]
Would you like to create a tag and we can update this PR (https://github.com/ufs-community/ufs-srweather-app/pull/166) to include it for testing?

**Comment by fossell** [comment]
@jwolff-ncar - A bug fix release tag upp_v9.0.1 was created and is now available.  Will comment on the srw app PR as well to get that change in the config file for testing.

**Comment by fossell** [comment]
This release is complete.
