### ISSUE TITLE
EMC_post does not depend on iplib

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/UPP#370]
Dependency on iplib should be removed.

**Comment by kgerheiser** [comment]
I came across this before because nothing uses `ip` in the repo, but I think it's used by `gtg` ?

https://github.com/NOAA-EMC/EMC_post/blob/develop/Externals.cfg

**Comment by DusanJovic-NOAA** [comment]
Is there a way to make it conditional dependency if gtg is enabled?

I can not see https://github.com/NCAR/UPP_GTG.git Is it a private repo?

 How do we even compile gtg?

**Comment by kgerheiser** [comment]
This commit is what made me think gtg requires ip:

https://github.com/NOAA-EMC/EMC_post/commit/ff42e0227d6100285d4179a2572b700fd5a959cb

I would say remove the `REQUIRED` from `find_package(ip)` and let it be optional.

**Comment by WenMeng-NOAA** [comment]
@kgerheiser @DusanJovic-NOAA The ip lib is used by gtg code which is at NCAR private repos.

**Comment by DusanJovic-NOAA** [comment]
How do we test that code if we can not see it?

**Comment by WenMeng-NOAA** [comment]
That code is maintained by @YaliMao-NOAA. She can give permission of gtg repos. to specific groups of people. Do you have a list of testing persons?

**Comment by WenMeng-NOAA** [comment]
> This commit is what made me think gtg requires ip:
> 
> [ff42e02](https://github.com/NOAA-EMC/EMC_post/commit/ff42e0227d6100285d4179a2572b700fd5a959cb)
> 
> I would say remove the `REQUIRED` from `find_package(ip)` and let it be optional.

Making finding ip lib to be optional might be good. The gtg code is used by GFS post processing only.
