### ISSUE TITLE
Incomplete/corrupted grib2 outputs from Post-Processing - UPP

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [NOAA-EMC/UPP#374]
The post jobs in the HAFS system, when the UPP convert native model grid (in
netCDF format)  dynf*.nc and phyf*.nc  files to GRIB2 format, occasionally it produces corrupted GRIB2 files on Orion. Rewinding the post jobs normally resolves the issue, but this error occurring frequently on Orion.

The message we get when we try to read the corrupted GRIB2 files using wgrib2 is like this:

*** FATAL ERROR: rd_grib2_msg_seq_file, missing end section ('7777') ***

I have a test case and script on Orion: /work/noaa/hwrf/scrub/bthomas/post_test_7777err

**Comment by kgerheiser** [comment]
Think it could be g2 related? 

If you say it only happens sometimes maybe there's a race condition related to OpenMP/MPI somewhere.

**Comment by BijuThomas-NOAA** [comment]
@kgerheiser, It happens sometimes, something like once in 20-30 trials. Also, we have seen this issue only on Orion.

**Comment by kgerheiser** [comment]
Have you looked at the corrupted file? Is it missing large chunks of data or is there something obviously wrong with it?

**Comment by BijuThomas-NOAA** [comment]
The file size is the same(bad and good GRIB2 files).  The portion of the data in the bad GRIB2 file that can be read(using wgrib2) is identical to the good GRIB2 file.

**Comment by mrinalbiswas** [comment]
@BijuThomas-NOAA Were you able to get a fix. I also got this error running HAFS (with Thompson) on Orion.

**Comment by BijuThomas-NOAA** [comment]
@mrinalbiswas 
I have not seen a fix for this and have already reported it to the UPP group.

**Comment by mrinalbiswas** [comment]
@BijuThomas-NOAA Thanks

**Comment by fossell** [comment]
@FernandoAndrade-NOAA, @gspetro-NOAA - This is a user help question, not sure what the status is now or if it's still an issue. We haven't worked with the HAFS application specifically. Might require a follow up to see if it's still a problem and then asking Wen to help coordinate expertise to help. Lots has changed with libraries and Orion since this ticket was open.

**Comment by WenMeng-NOAA** [comment]
@BijuThomas-NOAA Can the latest version of UPP resolve your issue? If yes, may I close it?

**Comment by BijuThomas-NOAA** [comment]
@WenMeng-NOAA Yes, the latest version of UPP fixed the issue. Please close #374

**Comment by FernandoAndrade-NOAA** [comment]
> @WenMeng-NOAA Yes, the latest version of UPP fixed the issue. Please close #374

Thanks for confirming!
