### ISSUE TITLE
adding some extra surface fields to the model output

### ISSUE THREAD

**Issue by HelinWei-NOAA** [NOAA-EMC/UPP#376]
Some extra surface fields are required to close the offline energy/water budget computation. These fields are listed below and described in [GRIB2 - TABLE 4.2-2-0](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-2-0.shtml)

(1)LAND FRACTION  (#233, LANDFRC)
(2)INST PREC ADVEC HEAT(#235, PAHFLX)
(3)WATER IN AQUIFER (#236, WATERSA)
(4)ACM EIWATER(CANOPY WATER EVAPORATION) (#237, EIWATER)
(5)ACM PLANTTR( PLANT TRANSPIRATION) (#238, PLANTTR)
(6)ACM SOILSE (BARE SOIL EVAPORATION) (#239, SOILSE)
(7)AVE PREC ADVEC HEAT(#235, PAHFLX)

**Comment by HelinWei-NOAA** [comment]
LANDFRC has been added to both master and surface flux file for all forecast lengths including 00Z
The other have been added to surface flux file only

**Comment by WenMeng-NOAA** [comment]
The following changes will be made in GFS baseline with the PR #378:

- Update input gfs model history files from 2019062000 F006.
- Add new grib2 field LANDFRC in gfs master file.
- Add the following new grib2 fields in gfs flux file
   1. instant LANDFRC
   2. instant PAHFLX
   3. averaged PAHFLX
   4. accumulated WATERSA
   5. accumulated EIWATER
   6. accumulated PLANTTR
   7. instant SOILSE

 We will add new fields in PGRB2 file when they are updated in wgrib2 later.
