### ISSUE TITLE
Filenames that only differ in uppercase/lowercase are incompatible with macOS

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/UPP#38]
There are two pairs of files that differ only in their first character being uppercase or lowercase:
```
sorc/ncep_post.fd/Makefile
sorc/ncep_post.fd/makefile
```
and
```
sorc/ncep_post.fd/Makefile_lib
sorc/ncep_post.fd/makefile_lib
```
This is  incompatible with the macOS filesystem, which is semi case-sensitive (it is case preserving, but otherwise doesn't distinguish). Are both versions required for each of those pairs? If so, can one of them be renamed?

**Comment by fossell** [comment]
@climbfuji - Some of this might be taken care of with the new community build structure we're working on implementing.  @mkavulich is working on this and I think he had tested MacOS builds.  We have some other issues with the build that we're working through at the moment, but perhaps @mkavulich can provide a quick answer for this.

**Comment by mkavulich** [comment]
@fossell The tests I have done on MacOS have been on a machine that is built with case-sensitivity enabled. I believe the unified build will still fail to compile on MacOS with the default case-insensitive setting. It should be an easy fix, but it will result in changing some naming conventions for the unified build, so we should probably consult with EMC before committing anything.

**Comment by aerorahul** [comment]
@fossell @WenMeng-NOAA can you please take action on this issue with these files?  
A simple renaming of the unused conflicting file out of the way will do as suggested by @climbfuji.

`develop` is the default branch, and when this repository is cloned on a macOS,  there is no way to change the branch.

**Comment by fossell** [comment]
@aerorahul - Apologies for the delay and difficulties this has brought.  The clean up of the makefiles should be taken care of when we merge release/public-v1 into develop. @mkavulich is working on this as we speak. This should be a simple merge and hopefully doesn't take long.   @mkavulich can you provide an update on your testing and expected time line for submitting a PR?

**Comment by fossell** [comment]
I'll also note that if we need a quick action fix for develop, the decision was made to remove the files Makefile_lib and Makefile. I can work with @WenMeng-NOAA to push this quickly if @mkavulich is delayed in the merge.
