### ISSUE TITLE
Add Jet to fv3gfs_downstream_nems.sh

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UPP#380]
To support the global workflow on Jet, fv3gfs_downstream_nems.sh should allow MPMD srun calls on the system.

This is in reference to NOAA-EMC/global-workflow#357.

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA It seems you have done some tests on jet. Would you like to submit PR for adding MPMD PGRB dataset process on jet? Thanks!

**Comment by DavidHuber-NOAA** [comment]
@WenMeng-NOAA Yes, I will get to that today.  Thanks for the nudge.

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA Thanks for submitting the PR. It looks good to me.  The UPP authoritative repos. was renamed from EMC_post to UPP. Would you rename your fork accordingly? Our announcement can be found at https://github.com/NOAA-EMC/UPP/discussions/372. Please let me know if you have any questions. Thanks!

**Comment by DavidHuber-NOAA** [comment]
@WenMeng-NOAA I have changed the name of my fork.  Thanks!
