### ISSUE TITLE
Himawari-8 fix and add parameters to Grib2 table

### ISSUE THREAD

**Issue by hertneky** [NOAA-EMC/UPP#382]
1. Need to apply a bug fix for Himawari-8 to remove old code that I believe was used for Grib1 output.

2. Need to add the parameters for Himawari-8 band 7-16 to Grib2 table

**Comment by hertneky** [comment]
@WenMeng-NOAA I conducted tests on Hera, which showed diffs in the gfs test for precip and categorical precip vars (both for my branch him8_mods and develop). Is there something I should know about when running the rt_for_developer.sh?

Output can be found here for tests on both branches: scratch1/NCEPDEV/stmp2/Tracy.Hertneky

**Comment by WenMeng-NOAA** [comment]
@hertneky Could you submit your branch as a new PR? It might be easy to look into your changes and conduct tests. The further modifications could be made based on testing and reviewing. Thanks!

**Comment by WenMeng-NOAA** [comment]
@hertneky There should be gfs test script syncing foe developer side testing. Sorry for confusing. Please conduct gfs test again.

**Comment by hertneky** [comment]
@WenMeng-NOAA Thanks - syncing the gfs script created bit-wise results. Question - Does nmmb still need to be tested - is it still used in operations (e.g. nam?). I tested, but checking for future.

**Comment by WenMeng-NOAA** [comment]
@hertneky The nmmb baseline might have discrepancy with the ops. nam due to some updates from UPP refactor in develop branch. But we keep this testing for a reference for RRFS and HAFS development.
