### ISSUE TITLE
Update documentation to remove submodules

### ISSUE THREAD

**Issue by fossell** [NOAA-EMC/UPP#386]
Submodules will be removed with #385.  

Need to update rst documentation to:
- [x] Remove mention of CMakeModules or .gitmodules in directory tree
- [x] Remove  "--recurse-submodules" from clone commands

Wiki Update:
- [x] Remove "git submodule update --init CMakeModules" step from build procedures  or  "--recurse-submodules" from clone commands for develop

**Comment by hertneky** [comment]
@fossell there were no mentions of CMakeModules or .gitmodules in the rst documentation, in particular the directory structure. I have marked the rst updates as complete with the recent PR
