### ISSUE TITLE
Add links to the main page of UPP doxygen documentation

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UPP#391]
The main page of the UPP doxygen based documentation can be see here: https://noaa-emc.github.io/UPP/

The text that appears here is from docs/user_guide.md. This is the landing page for the documentation can should also contain some high-level description of what is in UPP, with links to the utilities and most important library functions, to get the new users started on understanding the UPP package.

**Comment by fossell** [comment]
@edwardhartnett - docs/user_guide.md is essentially a copy of docs/Introduction.rst.  Do you know if it is possible for the doxygen documentation to leverage this existing introduction rst file (or perhaps vice versa) instead of having two separate identical copies to maintain? Or is there inherent incompatibility?

**Comment by edwardhartnett** [comment]
There is no inherent incompatibility. I believe that doxygen can also generate the usethedocs documentation, from the same source.

However, I have not worked that out yet. Also it's not clear that this is as important as it may seem. The readthedocs documentation seems to be more high-level, and the doxygen documentation more code-level, and that's OK. ;-)

So there is some duplication in the docs, for example on UFS_UTILS and NCEPLIBS-bufr, but we just live with it for now.

**Comment by fossell** [comment]
@gspetro-NOAA - This issue was to add more information, helpful links, etc. to the doxygen landing page (https://noaa-emc.github.io/UPP/) which is defined under docs/user_guide.md. Up to you how to enhance this space.

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA Do you think this issue has been solved? if so, can we close it?

**Comment by gspetro-NOAA** [comment]
@WenMeng-NOAA It hasn't yet, but I can put this info in with my upcoming PR.

**Comment by WenMeng-NOAA** [comment]
@gspetro-NOAA Thanks for update.

**Comment by edwardhartnett** [comment]
Can this issue be closed yet?

**Comment by gspetro-NOAA** [comment]
PR #965 added more information, helpful links, etc. to the [Doxygen landing page](https://noaa-emc.github.io/UPP/) defined in doc/user_guide.md.
