### ISSUE TITLE
1000 mb heights for the North American RRFS domain is corrupted

### ISSUE THREAD

**Issue by EricRogers-NOAA** [NOAA-EMC/UPP#393]
After the ufs-weather-model code being run in the LAM parallels was compiled with upp/10.0.9, it was discovered that the 1000 mb heights were corrupted:

132:1297512681:vt=2021092612:1000 mb:60 hour fcst:HGT Geopotential Height [gpm]:
    ndata=15634112:undef=6238409:mean=-2.33694e+15:min=-1.19702e+20:max=1.01562e+14
    grid_template=20:winds(grid):
        polar stereographic grid: (4784 x 3268) input WE:SN output WE:SN res 56
        North pole lat1 -2.500000 lon1 217.500000 latD 60.000000 lonV 260.000000 dx 3170.000000 m dy 3170.000000 m

Sample history files for testing from a RRFS 3 km run can be found on Mars at /gpfs/dell3/ptmp/Eric.Rogers/rrfs3km_forupptest; the contents of this directory are also on HPSS at /NCEPDEV/emc-meso/1year/Eric.Rogers/misc/RRFS3km_upptest.tar

**Comment by WenMeng-NOAA** [comment]
@EricRogers-NOAA This 1000 mg HGT issue occurs in all forecast hours or just particular hour?

**Comment by EricRogers-NOAA** [comment]
This issue occurs for all forecast hours.

**Comment by WenMeng-NOAA** [comment]
Wen set up an UPP standalone test with model history files provided by Eric. This test case can reproduce the failure reported by Eric.

**Comment by WenMeng-NOAA** [comment]
There are no corrupted 1000 mb heights in HAFS dataset though HAFS also has computation domain smaller than output domain.

**Comment by EricRogers-NOAA** [comment]
The problem in the RRFS domain is intermittent; from the 00z 9/27 RRFS DA run:

132:1302734770:vt=2021092903:1000 mb:51 hour fcst:HGT Geopotential Height [gpm]:
    ndata=15634112:undef=6238409:**mean=116.05:min=-156.904:max=269.368**

132:1302823635:vt=2021092904:1000 mb:52 hour fcst:HGT Geopotential Height [gpm]:
    ndata=15634112:undef=6238409:**mean=1.21493e+14:min=-3.74382e+19:max=1.96875e+14**

**Comment by WenMeng-NOAA** [comment]
With the fixes applied, here are the changed results in the failure case 2021092412 F12:
-----
![image](https://user-images.githubusercontent.com/48260754/135119496-c61718b4-6235-4791-a449-943ea4da3745.png)
![image](https://user-images.githubusercontent.com/48260754/135119737-c1510f05-3a9d-43da-a17a-f2958c90ed6f.png)
![image](https://user-images.githubusercontent.com/48260754/135120084-b4a1c9c4-27b2-4a2a-a753-b0879e3506bf.png)

**Comment by WenMeng-NOAA** [comment]
The UPP regression tests were conducted on WCOSS-Dell. The changed results in HAFS are:
```
[Wen.Meng@m71a1 ptmp]$ cat fv3hafs_2020082512/HURPRS09.tm00.diff
632:2436070281:MSLET:mean sea level:rpn_corr=0.999907:rpn_rms=6.13738
633:2442196436:HGT:1000 mb:rpn_corr=0.999909:rpn_rms=0.521143
```
The HAFS has undefined grids in output domain. The changes should be expected.

**Comment by WenMeng-NOAA** [comment]
A new upp lib was built in Wen's account. This upp lib can be run through in ufs-weather-model rt tests, control and regional_quilt which include inline post.
