### ISSUE TITLE
NOAA GSL UPP updates being prepared

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/UPP#404]
NOAA-GSL developers have some UPP updates for our Rapid Refresh Forecast System (RRFS).  We are working to finalize and test the code, and hope to have it ready within 1-2 weeks.   There are a few modifications / new fields in the works:

- Four new fields for model forecasts (exceedance flags for precipitation exceeding reference thresholds):
(1) 1h QPF exceeding Flash Flood Guidance (FFG)
(2) run total accumulated QPF exceeding Flash Flood Guidance (FFG)
(3) 1h QPF exceeding Average Recurrence Intervals (ARIs)
(4) run total accumulated QPF exceeding Average Recurrence Intervals (ARIs)

- Modifications to allow output of 9 soil levels from RUC Land Surface Model

- Bug fix for new name of cloud water mixing ratio in GRIB2 tables (CLMR instead of CLWMR)

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Thanks for the heads-up. Please follow the instructions of UPP code changing at
https://github.com/NOAA-EMC/UPP/wiki/UPP-Code-Development#contribute-changes-in-upp-main-development-branch-develop

I invite @ericaligo-NOAA and @BenjaminBlake-NOAA in this issue so they will be aware of upcoming changes for RRFS.
