### ISSUE TITLE
gdaspostanl and gfspostanl should report failure if files do not show up before job ends

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/UPP#443]
If the loop waiting for output files to show up exhausts all iterations before files are available, the job should register as failed, not succeeded. This issue can be referenced from global-workflow issue 520:
https://github.com/NOAA-EMC/global-workflow/issues/520

**Comment by WenMeng-NOAA** [comment]
@lgannoaa Could you submit a PR for fixing?

**Comment by lgannoaa** [comment]
PR 444 created for fix this issue.
