### ISSUE TITLE
The executable directory needs to be switchable to exec

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/UPP#447]
The current directory for the executable 'upp.x' is 'bin'. However, we need an option for 'exec' to meet the NCO standards.

**Comment by WenMeng-NOAA** [comment]
@chan-hoo Are you building the upp executable "upp.x" on WCOSS1/WCOSS2 for NCEP implementation development?

**Comment by chan-hoo** [comment]
@WenMeng-NOAA, I am updating the UFS SRW App to meet the NCO standards. UPP is one of the external components. Since the external components are built within the integrated cmake system in the UFS SRW App, the directory where upp.x is created should be named to 'exec' from UPP. I've submitted a PR for this (https://github.com/NOAA-EMC/UPP/pull/448). Is there any other way for this?

**Comment by kgerheiser** [comment]
~~How about doing it like UFS_UTILS?~~

~~https://github.com/ufs-community/UFS_UTILS/blob/570ea3966c125ead7e90b4342be2efc22a8b1f41/CMakeLists.txt#L77-L80~~

Edit: Saw your PR, and that looks good.

**Comment by WenMeng-NOAA** [comment]
@chan-hoo We have build script under tests/compile_upp.sh which generates executable upp.x under exec/ on WCOSS1/WCOSS2, Hera, Orion, Jet, s4. Do you think UFS SRW app could use it?

**Comment by WenMeng-NOAA** [comment]
@chan-hoo The build script tests/compile_upp.sh is currently used by GFS, HAFS, 3DRTMA implementation development.  Your PR #448 might have impact on them.

**Comment by chan-hoo** [comment]
@WenMeng-NOAA, My PR #448 should not affect the build script (compile_upp.sh) at all. You don't have to worry about it. The new optional argument `-DEMC_EXEC_DIR=ON` is necessary only when a user wants to create upp.x in the `exec` directory directly. For the `bin` directory, the build commands are the same as before. Apart from the others you listed, UFS SRW App does not use the component's own build scripts such as compile_upp.sh when it builds executables. Instead, it uses its own cmake configuration that integrates all the components into one. Therefore, the PR #448 is a must for that.

**Comment by WenMeng-NOAA** [comment]
@chan-hoo Got it. Thanks for clarification.
