### ISSUE TITLE
Unify read interfaces for FV3 global and regional models in UPP code

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#450]
In UPP code, FV3 global model (GFS) uses read interface INITPOST_GFS_NETCDF_PARA and FV3 regional models (RRFS/HAFS) use read interface INITPOST_NETCDF. With unified diag table (proposed by Huiya) implemented at UFS, it is time to unify read interface for FV3 based models.

**Comment by WenMeng-NOAA** [comment]
Per @yangfanglin 's recommendation, UPP output column PWAT read from FV3 based models instead of calculated in UPP. 
The changes in PWAT is not outstanding. 
---------------------------
RRFS:
PRSLEV06.tm00.diff: 896:1242380352:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.991155:rpn_rms=2.00101

HAFS:
HURPRS09.tm00.diff: 657:2537029294:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.991889:rpn_rms=1.65827

GFS:
gfs.t00z.master.grb2f006.diff: 891:2395425478:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.999712:rpn_rms=0.42454
gfs.t00z.sfluxgrbf006.grib2.diff: 75:155581696:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.999712:rpn_rms=0.42454

**Comment by HuiyaChuang-NOAA** [comment]
> ## Per @yangfanglin 's recommendation, UPP output column PWAT read from FV3 based models instead of calculated in UPP.
> The changes in PWAT is not outstanding.
> RRFS: PRSLEV06.tm00.diff: 896:1242380352:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.991155:rpn_rms=2.00101
> 
> HAFS: HURPRS09.tm00.diff: 657:2537029294:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.991889:rpn_rms=1.65827
> 
> GFS: gfs.t00z.master.grb2f006.diff: 891:2395425478:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.999712:rpn_rms=0.42454 gfs.t00z.sfluxgrbf006.grib2.diff: 75:155581696:PWAT:entire atmosphere (considered as a single layer):rpn_corr=0.999712:rpn_rms=0.42454

@WenMeng-NOAA @yangfanglin Good to know model computed PWAT and UPP computed PWAT are similar.

**Comment by WenMeng-NOAA** [comment]
By 03/28/2022:

- Huiya provided the unified FV3 model diag table to the GFS, RRFS and HAFS team.
- Eric ran RRFS with the unified diag table and provided Wen new RRFS history files.
- Lin ran HAFS with the unified diag table and provided Wen new HAFS history files.
- Fanglin ran GFS with the unified diag table and provided Wen new HGS history files.
- Wen ran UPP standalone test with UPP branch post_fv3_unify and new RRFS history files. Eric verified new RRFS grib2 files.
- Wen ran UPP standalone test with UPP branch post_fv3_unify and new HAFS history files. Lin verified new HAFS grib2 files.
- Wen ran UPP standalone test with UPP branch post_fv3_unify and found out modification might be needed in some computation of GFS related fields, e.g. radar reflectivity (UPP has no capability to calculate radar radar reflectivity with Thompson MP outputs from GFS).
- Ruiyu indicated he would working on outputting 3D radar reflectivity from GFS and modify relevant changes in UPP.

**Comment by WenMeng-NOAA** [comment]
@HuiyaChuang-NOAA Here are my proposal for merging branch post_fv3_unify:

- Update the UPP RT baseline for RRFS with new RRFS model outputs generated with the unified diag table.
- Update the UPP RT baseline for HAFS with new HAFS model outputs generated with the unified diag table.
- Keep the UPP RT baseline for GFS unchanged. The unified FV3 read interface is configurated with reading GFS outputs  generated with un-unified diag table. This interface will be updated when new GFS radar reflectivity algorithms is ready.
-
Please let me know your thoughts. Thanks!

**Comment by HuiyaChuang-NOAA** [comment]
> @HuiyaChuang-NOAA Here are my proposal for merging branch post_fv3_unify:
> 
> * Update the UPP RT baseline for RRFS with new RRFS model outputs generated with the unified diag table.
> * Update the UPP RT baseline for HAFS with new HAFS model outputs generated with the unified diag table.
> * Keep the UPP RT baseline for GFS unchanged. The unified FV3 read interface is configurated with reading GFS outputs  generated with un-unified diag table. This interface will be updated when new GFS radar reflectivity algorithms is ready.
> 
> Please let me know your thoughts. Thanks!

@WenMeng-NOAA your proposal sounds good.  Should I still ask all three new diag tables including GFS one to be committed to UFS repo?

**Comment by WenMeng-NOAA** [comment]
> > @HuiyaChuang-NOAA Here are my proposal for merging branch post_fv3_unify:
> > 
> > * Update the UPP RT baseline for RRFS with new RRFS model outputs generated with the unified diag table.
> > * Update the UPP RT baseline for HAFS with new HAFS model outputs generated with the unified diag table.
> > * Keep the UPP RT baseline for GFS unchanged. The unified FV3 read interface is configurated with reading GFS outputs  generated with un-unified diag table. This interface will be updated when new GFS radar reflectivity algorithms is ready.
> > 
> > Please let me know your thoughts. Thanks!
> 
> @WenMeng-NOAA your proposal sounds good. Should I still ask all three new diag tables including GFS one to be committed to UFS repo?

I would think RRFS and HAFS are fine. You might ask @junwang-noaa, @yangfanglin and @JessicaMeixner-NOAA for GFS.

**Comment by HuiyaChuang-NOAA** [comment]
> > > @HuiyaChuang-NOAA Here are my proposal for merging branch post_fv3_unify:
> > > 
> > > * Update the UPP RT baseline for RRFS with new RRFS model outputs generated with the unified diag table.
> > > * Update the UPP RT baseline for HAFS with new HAFS model outputs generated with the unified diag table.
> > > * Keep the UPP RT baseline for GFS unchanged. The unified FV3 read interface is configurated with reading GFS outputs  generated with un-unified diag table. This interface will be updated when new GFS radar reflectivity algorithms is ready.
> > > 
> > > Please let me know your thoughts. Thanks!
> > 
> > 
> > @WenMeng-NOAA your proposal sounds good. Should I still ask all three new diag tables including GFS one to be committed to UFS repo?
> 
> I would think RRFS and HAFS are fine. You might ask @junwang-noaa, @yangfanglin and @JessicaMeixner-NOAA for GFS.

@WenMeng-NOAA I'd like to push for commit of all three tables.  I think it's easier logiscally.  If you don't have objection, I will contact Jun on how to proceed

**Comment by WenMeng-NOAA** [comment]
@HuiyaChuang-NOAA If you are talking about updating the diag tables at ufs
https://github.com/ufs-community/ufs-weather-model/tree/develop/tests/parm/diag_table

I would defer the question to @junwang-noaa. From inline post perspective, the read interface unifying has been applied.  I might concern about unexpected changes in UFS RT tests. Jun should know about more than me. Thanks!
