### ISSUE TITLE
Output "wgne" files from GFS (instead of verf_precip)

### ISSUE THREAD

**Issue by AliciaBentley-NOAA** [NOAA-EMC/UPP#462]
The operational version of verf_precip currently creates 3-hourly GFS accumulated precipitation forecast files and sends them to NOMADS as part of the WGNE agreement between international centers. The WGNE files look like this: **wgnegfs_YYYYMMDDHH_starttime_endtime.grb2**, where starttime is always 000 (initialization) and endtime is the length of the forecast in 3 digits (003 through 180). Here is the path to these files on NOMADS:
https://nomads.ncep.noaa.gov/pub/data1/nccf/com/verf/prod/

We would like GFSv16.3 to output the WGNE files instead of verf_precip. A change in the filenames and location on NOMADS would be possible with an SCN if 1) the forecast file resolution stays the same and 2) "wgne" still appears somewhere in the new filename for our international partners to locate (e.g., gfs.t{CC}.wgne.f{FFF}.grib2). We hope that this is possible! Thank you!

**Comment by WenMeng-NOAA** [comment]
@AliciaBentley-NOAA I added the changes for generating wgne product from f000 to f180 at 3-hour interval in gfs post processing workflow. The sample data files can be accessed on WCOSS2 Cactus /u/Wen.Meng/noscrub/ncep_post/gfsv16/wen_gfsv16/wgnegfs_data:

- data files pull from NOMADS: wgnegfs_2022041800_000_???.grb2
- data files generated from post process workflow: gfs.t00z.wgne.f???

Can you verify them? Thanks!

**Comment by AliciaBentley-NOAA** [comment]
@WenMeng-NOAA I examined the output from your test and the output that you downloaded from NOMADS. The output looks identical (see example comparison below), which is great. Thank you for your help with this!

[Alicia.Bentley@clogin01 wgnegfs_data] wgrib2 -V wgnegfs_2022041800_000_060.grb2
1:0:vt=2022042012:surface:0-60 hour acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=1038240:undef=0:mean=5.92986:min=0:max=466.562
    grid_template=0:winds(N/S):
        lat-lon grid:(1440 x 721) units 1e-06 input WE:NS output WE:SN res 48
        lat 90.000000 to -90.000000 by 0.250000
        lon 0.000000 to 359.750000 by 0.250000 #points=1038240

[Alicia.Bentley@clogin01 wgnegfs_data] wgrib2 -V gfs.t00z.wgne.f060
1:0:vt=2022042012:surface:0-60 hour acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=1038240:undef=0:mean=5.92986:min=0:max=466.562
    grid_template=0:winds(N/S):
        lat-lon grid:(1440 x 721) units 1e-06 input WE:NS output WE:SN res 48
        lat 90.000000 to -90.000000 by 0.250000
        lon 0.000000 to 359.750000 by 0.250000 #points=1038240

[Alicia.Bentley@clogin01 wgnegfs_data] ls -lath wgnegfs_2022041800_000_060.grb2
-rw-r--r-- 1 Wen.Meng vpppg 618K Apr 19 06:10 wgnegfs_2022041800_000_060.grb2
[Alicia.Bentley@clogin01 wgnegfs_data] ls -lath gfs.t00z.wgne.f060
-rw-r--r-- 1 Wen.Meng vpppg 618K Apr 20 19:50 gfs.t00z.wgne.f060

**Comment by WenMeng-NOAA** [comment]
@AliciaBentley-NOAA Thanks for verifying. I will commit the changes in the UPP for GFS V16 branch for the upcoming  GFS V16.2 implementation.
