### ISSUE TITLE
Capability of detect gaussian grid scanning mode north2south vs. south2north

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#47]
Add a a fix from Dusan Javic for  scanning mode in POST for gaussian grid to detect north2south vs. south2north based on latstart vs latlast.
The change in sorc/ncep_post.fd/grib2_module.f as:
-------------------
@@ -1389,6 +1389,11 @@
        ifield3(16) = lonlast
        ifield3(17) = NINT(360./(IM)*1000000.)
        ifield3(18) = NINT(JM/2.0)
+       if( latstart < latlast ) then
+        ifield3(19) = 64      !for SN scan  
+       else
+        ifield3(19) = 0       !for NS scan
+       endif
 !
 !** Latlon grid
       ELSE IF(MAPTYPE == 0 ) THEN
-----------------------

This change will be committed to branch "ufs_public_release".

**Comment by WenMeng-NOAA** [comment]
The pull request was created at https://github.com/NOAA-EMC/EMC_post/pull/48.

**Comment by WenMeng-NOAA** [comment]
The PR was viewed and approved by Dusan.

**Comment by climbfuji** [comment]
Merged into ufs_public_release (https://github.com/NOAA-EMC/EMC_post/pull/48). Will there be a corresponding PR for develop/master?

**Comment by WenMeng-NOAA** [comment]
@climbfuji Thanks for merging. I will create another PR for branch develop update. The UPP branch
develop and ufs_public_release are not unified. I would expect both of you and Kate to take care of maintaining ufs_public_release branch. I will maintain branch develop. Please let me know if you have comments/suggestions. Thanks!

**Comment by climbfuji** [comment]
This sounds good to me, thanks!

**Comment by WenMeng-NOAA** [comment]
This new feature was committed in branch develop at 927708e on 01/16/19.
