### ISSUE TITLE
updating UPP for GEFS-Aerosols v12.3 implementation

### ISSUE THREAD

**Issue by lipan-NOAA** [NOAA-EMC/UPP#483]
There are two updates in the UPP for the GEFS-Aerosols v12.3 implementation. The first is a bug fix when calculating aerosol AOD. The second is to add a new variable, Surface Dust PM10, to the UPP output.

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA I would like to know if the changes in PR #484 should be included in GFSV17/GEFSV13 implementation? If yes, could you submit another PR aiming for the UPP develop branch?

**Comment by lipan-NOAA** [comment]
@WenMeng-NOAA I will submit a PR for UPP develop branch

**Comment by WenMeng-NOAA** [comment]
@lipan-NOAA Thanks for clarifying.
