### ISSUE TITLE
MRW updates

### ISSUE THREAD

**Issue by fossell** [NOAA-EMC/UPP#494]
A few remaining questions for MRW use cases:

- [x] 1. What is the file format of the model output so we can make sure run_upp script can be leveraged for offline applications.
- [ ] 2. Which postxconfig-Nt.txt(s) file does MRW expect to use in global workflow so we can document list of output fields.

**Comment by fossell** [comment]
@hertneky - Someone from MRW team pointed me to a run on Hera to look at for these questions. From what I can decipher so far, I believe that the for 1) the filenames are gfs.t00z.atmf024.nc and gfs.t00z.sfcf024.nc.  As for 2) I _think_ they use just postxconfig-NT-GFS-TWO.txt (plus the one for FHR 00) and that produces two output files from the model running inline post, GFSPRS.GrbF09 and GFSFLX.GrbF09 which are called gfs.t00z.master.grb2f009 and gfs.t00z.sfluxgrbf009.grib2  in the final output directory.

**Comment by fossell** [comment]
@WenMeng-NOAA - Would you mind taking a look at my previous comment and let me know if this makes sense and is similar to any experience you have dealing the global workflow?  I have never used it, so just trying to piece this together.  If you have any insights, we'd appreciate it!

**Comment by WenMeng-NOAA** [comment]
@fossell Your comments are right.

**Comment by fossell** [comment]
@WenMeng-NOAA - Thanks for confirming Wen, that's very helpful!

**Comment by fossell** [comment]
The run_upp script was updated with new MRW naming convention for model output names in PR #504

**Comment by hertneky** [comment]
@fossell Question - is the MRW output still on a gaussian grid? Can you look at the run on Hera you were pointed to to confirm?

**Comment by fossell** [comment]
No longer relevant.
