### ISSUE TITLE
Cheyenne hpc-stack module update

### ISSUE THREAD

**Issue by jkbk2004** [NOAA-EMC/UPP#500]
Description:
1. UFS-WM hpc-stack modules on Cheynne were migrated to /glade/work/epicufsrt/GMTB/tools for both gnu and Intel
2. intel2022.1 upgrade is on-going UFS-WM repo
3. Need to combine the issues of the new hpc-stack location and compiler update and stack lib package options of g2/libpng/w3emc
4. Additional PRs are expected to cover other RDHPCs

**Comment by fossell** [comment]
@jkbk2004 - The goal is to have these mods in the UPP release branch (i.e. release/public-v3) for the upcoming SRW release, correct? We have already branched off develop.

**Comment by jkbk2004** [comment]
> @jkbk2004 - The goal is to have these mods in the UPP release branch (i.e. release/public-v3) for the upcoming SRW release, correct? We have already branched off develop.

@fossell @WenMeng-NOAA not for srw release. code freeze for srw release will be around May16. I don't expect hpc-stack sync case can be completed before then since it involves with other repos and platforms. So, we may take time to merge in develop branch.

**Comment by fossell** [comment]
@jkbk2004 - Sounds good, thanks for clarifying!

**Comment by fossell** [comment]
@camshe - This will be one you'll want to monitor since it relates to building/running UPP on cheyenne.
