### ISSUE TITLE
Runtime issue on Cheyenne with GNU

### ISSUE THREAD

**Issue by fossell** [NOAA-EMC/UPP#505]
Executable is failing for offline runs built on Cheyenne with GNU compiler. Some environment mismatches suspected.

**Comment by hertneky** [comment]
The main issue was running UPP in the batch system on Cheyenne for the GNU compiler (non-default compiler). Running outside of the batch system worked.

@kayeekayee can you try running again with these lines added to your run.sh script for cheyenne gnu:

source /glade/u/apps/ch/modulefiles/default/localinit/localinit.csh

module purge

module use /glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/modulefiles/stack
module load hpc/1.2.0
module load hpc-gnu/10.1.0
module load hpc-mpt/2.22

module load ncarenv/1.3
module load ncarcompilers/0.5.0

Let me know how it goes - this worked for me. I tried without sourcing the localinit.csh file and the library issue occurred. When adding that line in, it ran fine.

**Comment by kayeekayee** [comment]
@hertneky I tried your suggestion in run.sh and run_mpi.pbs but I am still unable to run the cases. May I look at your run and see what is the difference between mine and yours?

**Comment by hertneky** [comment]
@kayeekayee Sorry, I meant to say add those lines to the batch script.
You can find my build here: /glade/work/hertneky/upp/builds/UPPv10.1.0. My run is here /glade/work/hertneky/upp/testing/postprd where I used:
script: run_upp
batch script: run_mpi_gfs.pbs
run log: upp.f006.out

**Comment by fossell** [comment]
@kayeekayee - change the localinit script to be a .sh instead of a .csh. That should allow it to be sourced properly and then upp should start to run. It's still failing for me so there is probably another issue, but at least with this script upp.x can run.  We'll need to understand this script and behavior better and identify a long term solution for users.

**Comment by fossell** [comment]
@kayeekayee @hertneky - I've been having success in running case4 when sourcing the localinit.sh script in the job script.  I've been playing around with the resources and wallclock time to get a full run complete, but for the fhrs that complete the output looks ok. I'm going to email CISL regarding the localinit.sh script and see what they advise for a long term solution.

**Comment by kayeekayee** [comment]
@fossell @hertneky Thank you so much for your info. I am able to run UFFDA with GNU now with sourcing the localinit.sh script!
