### ISSUE TITLE
gefs_v12.3.0 crashed in post_hr_p${mem}

### ISSUE THREAD

**Issue by lipan-NOAA** [NOAA-EMC/UPP#524]
The tag for gefs_v12.3.0 was created for the GEFS-Aerosols v12.3 implementation (see PR#[484](https://github.com/NOAA-EMC/UPP/pull/484)).

In the final test, the "chem_post" succeeded as we expected, but the post processing of the atmospheric ensemble member failed.

The bug has been found and fixed. With the newly fixed version, all tasks in the GEFS package have been completed successfully.

This issue was created to include the latest update in the gefs_v12.3.0 tag.

**Comment by WenMeng-NOAA** [comment]
The PR #525 was merged.
