### ISSUE TITLE
Updraft helicity and SRH in the Southern Hemisphere

### ISSUE THREAD

**Issue by gabrielcassol** [NOAA-EMC/UPP#532]
Hello everybody,

Is it possible to update the post-processing codes used to calculate the storm relative helicity (SRH) and updraft helicity (UH) for the Southern Hemisphere?

/sorc/ncep_post.fd/**CALHEL.f**
/sorc/ncep_post.fd/**CALUPDHEL.f**

From what I saw in the SRH code, the left movement of the average wind is not taken into account, and in the code to calculate the UH I did not find adaptations to find the negative ascending helicity, so I should look for the minimum values of UH, in Southern Hemisphere cases.

**Comment by WenMeng-NOAA** [comment]
@gabrielcassol Thanks for bring our attention on this issue. Could you follow the procedure [here](https://github.com/NOAA-EMC/UPP/wiki/UPP-Code-Development#contribute-changes-in-upp-main-development-branch-develop) to submit a PR with your proposal?

**Comment by gabrielcassol** [comment]
> @gabrielcassol Thanks for bring our attention on this issue. Could you follow the procedure [here](https://github.com/NOAA-EMC/UPP/wiki/UPP-Code-Development#contribute-changes-in-upp-main-development-branch-develop) to submit a PR with your proposal?

I'm not familiar with tinkering with fortran code, so I wouldn't know how to make these changes to contribute the updated code for South America. Isn't there someone from support who has knowledge of fortran to help us make these changes?

**Comment by WenMeng-NOAA** [comment]
@fossell Would DTC/EPIC has resources assisting @gabrielcassol with this UPP enhancement? Thanks!

**Comment by gabrielcassol** [comment]
Is there anyone else who can help on this matter?

**Comment by fossell** [comment]
@gabrielcassol - Unfortunately we have very limited resources. We'll try to take a look soon to see if this is something we can help with and will get back to you. In the meantime, it sounds like you've at least looked into the relevant routines to see what's going on and how things should change. Can you provide some more detail about what sort of algorithm and changes you want to see implemented?

**Comment by hertneky** [comment]
@gabrielcassol - I have started looking at this and will have something for you to test next week as I am out of the office the remainder of this week.

**Comment by hertneky** [comment]
@gabrielcassol I created a draft PR #545  for testing storm relative helicity. I do not have data for the SH to test, only coarse global data. Can you please look at the changes and also test to see if it is what you would expect as I am not an expert on SRH.

As for updraft helicity, I do not believe that modifications are needed for the SH. For the SH, rising cyclonic (anti-cyclonic) rotation will have negative (positive) values. The algorithm remains the same.

**Comment by gabrielcassol** [comment]
@hertneky thank you very much for your help, I will test the SRH fix for the Southern Hemisphere in the next few days and I will give you feedback in the next few days.

Regarding the updraft helicity, I agree, it doesn't need correction, it would just set to plot the negative values. But I would like to suggest one thing: is it possible to change the code to generate the updraft helicity **accumulated** in 1 hour and not the instantaneous updraft helicity as it is generated? Because the accumulated UH data is more useful in the operational area.

**Comment by hertneky** [comment]
@gabrielcassol If the model output you are working with has 1-hour accumulated UH, then this variable can be added to UPP for output, otherwise UPP is unable to compute averages/accumulations over a time period, as it only processes a single forecast file at a time.

**Comment by hertneky** [comment]
@gabrielcassol Have you had a chance to review the code changes and test the changes yet?

**Comment by hertneky** [comment]
@WenMeng-NOAA Checking in on this issue since we have not heard from @gabrielcassol. Is there anyone available that can review and test this change?
I can also close the draft PR for now and keep this issue active as well as keep the branch with the changes for possible future implementation.
What are your thoughts?

**Comment by WenMeng-NOAA** [comment]
@hertneky Can you sync your branch with the UPP develop? I could run some test cases with GFS and might find developers from EMC to review the changes for GFS development.

**Comment by hertneky** [comment]
@WenMeng-NOAA Done. And thanks for trying to move this one forward. It's not high priority so if you can't find anyone to review, we can always reassess.

**Comment by gabrielcassol** [comment]
Hi, I apologize for the delay, I was very busy and I didn't have enough time before to do the necessary tests.

I used the new adaptations made in CALHEL.f with the data from the WRF 4 km that I run operationally here and the results were very good, I can say that the adaptation for the Southern Hemisphere worked.

I have attached below the tests of the verification I did: the figure on the left is the SRH 0-3 km that I calculated manually, and the figure on the right is the SRH 0-3 km generated directly through the UPP. The values are practically identical, very close to each other.

Thank you so much for your help @hertneky !

![srh03km_verification](https://user-images.githubusercontent.com/43749970/193982156-5ebdd0ff-8aae-49a9-a055-94cef1f85343.png)

**Comment by WenMeng-NOAA** [comment]
The UPP RT tests were conducted on Hera. The following applications have impact:
```
RAP:
 [Wen.Meng@hfe02 ~/stmp2]$ cat rap_2020072316/WRFPRS.GrbF16.diff
712:196882714:HLCY:3000-0 m above ground:rpn_corr=0.971321:rpn_rms=12.8134
713:197407665:HLCY:1000-0 m above ground:rpn_corr=0.980911:rpn_rms=7.43498
714:197901510:USTM:0-6000 m above ground:rpn_corr=0.967445:rpn_rms=1.88453
715:198410180:VSTM:0-6000 m above ground:rpn_corr=0.964277:rpn_rms=1.90134

NMMB:
[Wen.Meng@hfe02 ~/stmp2]$ cat post_nmmb_meso_2014120818_Grib2/BGRD3D03.tm00.Grib2.diff
1391:432841532:HLCY:3000-0 m above ground:rpn_corr=0.998099:rpn_rms=6.58001
1392:433354834:HLCY:1000-0 m above ground:rpn_corr=0.996865:rpn_rms=5.55079
1393:433843144:USTM:6000-0 m above ground:rpn_corr=0.992757:rpn_rms=1.06151
1394:434536140:VSTM:6000-0 m above ground:rpn_corr=0.989431:rpn_rms=1.46078
[Wen.Meng@hfe02 ~/stmp2]$ cat post_nmmb_meso_2014120818_Grib2/BGDAWP03.tm00.Grib2.diff
992:378228796:HLCY:3000-0 m above ground:rpn_corr=0.998099:rpn_rms=6.58001
993:378742098:HLCY:1000-0 m above ground:rpn_corr=0.996865:rpn_rms=5.55079
994:379230408:USTM:6000-0 m above ground:rpn_corr=0.992757:rpn_rms=1.06151
995:379923404:VSTM:6000-0 m above ground:rpn_corr=0.989431:rpn_rms=1.46078

HAFS:
[Wen.Meng@hfe02 ~/stmp2]$ cat fv3hafs_2021082706/HURPRS09.tm00.diff
677:880929530:HLCY:3000-0 m above ground:rpn_corr=0.62436:rpn_rms=53.6653

GFS:
[Wen.Meng@hfe02 ~/stmp2]$ cat gfs.20210216/gfs.t00z.master.grb2f006.diff
927:2524113570:HLCY:3000-0 m above ground:rpn_corr=0.766661:rpn_rms=85.4926
928:2526690477:USTM:6000-0 m above ground:rpn_corr=0.72597:rpn_rms=6.71188
929:2530417333:VSTM:6000-0 m above ground:rpn_corr=0.553041:rpn_rms=8.21284
```

**Comment by hertneky** [comment]
Changes to storm motion and helicity are expected, but only in the SH, so this looks okay to me, since these model grids all extend into SH. Thank you for conducting these tests.

**Comment by WenMeng-NOAA** [comment]
@gabrielcassol and @hertneky Thanks for contributing UPP enhancement.
