### ISSUE TITLE
GFS Total Cloud Fraction on Isobaric levels

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#539]
The total cloud fraction on isobaric levels are computed in UPP with cloud fraction on hybrid levels which are read from model outputs. @junwang-noaa reported GFS cloud fraction on isobaric levels have non-undefined values when cloud fraction on hybrid levels are not written out in mode outputs.

**Comment by WenMeng-NOAA** [comment]
@junwang-noaa and @HuiyaChuang-NOAA I think there is a bug in UPP code for rounding upper bound and lower bound of cloud fraction on isobaric levels at
https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/MDL2P.f#L1319
The points with undefined values should be restricted. I conducted a test with model history files from Jun's test and saw all cloud fraction on isobaric levels are in undefined values since no 3D cloud faction outputs in Jun's test.
The test without the fix is  gfs.t00z.master.grb2f003 at /scratch2/NCEPDEV/ovp/Wen.Meng/ncep_post/develop/jun.
The test with fix is gfs.t00z.master.grb2f003 at /scratch1/NCEPDEV/stmp2/Wen.Meng/gfs.2013040100

**Comment by HuiyaChuang-NOAA** [comment]
@WenMeng-NOAA thanks.  good find.  Are you moving max/min cap to after line 1321?
