### ISSUE TITLE
 Implement the capability to process chemical model NETCDF output and UFS-Aerosols model output

### ISSUE THREAD

**Issue by zhanglikate** [NOAA-EMC/UPP#560]
The previous UPP can only process the NEMSIO format for chemical output of GEFS-Aerosols. The updates has implemented the capability to read the chemical model NETCDF output for both GEFS-Aerosols (by turning on gocart_on) and UFS-Aerosols (by turning on nasa_on).

**Comment by WenMeng-NOAA** [comment]
Wen ran the UPP standalone test and verified the fix re-assigned MERRA aerosol fields working well.
