### ISSUE TITLE
Unify visibility at GFS V17

### ISSUE THREAD

**Issue by HuiyaChuang-NOAA** [NOAA-EMC/UPP#564]
EMC and GSL reached agreement to use GSL visibility as the unified visibility.
MEG group's evaluation showed GSL's visibility algorithm performed slightly better:
https://docs.google.com/presentation/d/1VVZqU45qRZPXu8oC_7eAOGhEB-bZxe5K/edit?usp=sharing&ouid=108525369416162436558&rtpof=true&sd=true

RRFS V1 will use GSL visibility.  This ticket will target to change GFS post control file to 
use GSL visibility for GFS V17 implementation.

**Comment by WenMeng-NOAA** [comment]
From the UPP RT tests, the following changes are expected:
GFS: master dataset: field "VIS:surface"
before: 
  ```
10:15917939:ndata=4718592:undef=0:mean=19526.9:min=14.62:max=24135:cos_wt_mean=21212.9:d=2021021600:VIS:surface:6 hour fcst:
```
after:
```
10:15917939:ndata=4718592:undef=0:mean=20505.4:min=10.8788:max=89999.7:cos_wt_mean=23029.5:d=2021021600:VIS:surface:6 hour fcst:
```
