### ISSUE TITLE
Transition two SLR algorithms to UPP

### ISSUE THREAD

**Issue by JesseMeng-NOAA** [NOAA-EMC/UPP#566]
Transition Snow-to-Solid-Ratio (SLR) algorithms to UPP for enhanced winter precipitation product.

- Spin up on Roebber and Alcott-Steenburgh SLR algorithms
- Start working on adding both SLR algorithms to UPP
- Finish adding both SLR algorithms to UPP
- Sanity check on two new SLR algorithms
- Run UPP regression tests to ensure the new algorithms pass the tests

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA To generate SLR, are there any changes of UPP configuration for GFS and RRFS at runtime? If yes, can you provide me the instructions? I would think some or all new fix files in your PR are needed at runtime? Thanks!

**Comment by JesseMeng-NOAA** [comment]
Variable SDEN is added to these three configure files to generate SLR,
postxconfig-NT-GFS.txt
postxconfig-NT-fv3lam.txt
postxconfig-NT-fv3lam_rrfs.txt

The run script needs to copy the files fix/Breadboard/Breadboard*.nsw to the run directory.
