### ISSUE TITLE
Empty user_guide link in doxygen documentation

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UPP#569]
When I look at the documentation for UPP on the gh-pages branch I see an empty page called user_guide.

The contents from the user_guide.md are already correctly displayed on the main page of the documentation.

So the empty page which is labeled "user_guide" should just be removed.

![image](https://user-images.githubusercontent.com/38856240/194549198-59454883-bed1-45b5-a0dd-9e88c5182bc7.png)

**Comment by fossell** [comment]
@camshe - this should be addressed to clean up the technical documentation. Let me know if you need help.

**Comment by fossell** [comment]
@edwardhartnett - Thanks for noticing and putting in the issue!

**Comment by fossell** [comment]
@gspetro-NOAA - Please note this issue as it pertains to the Doxygen documentation and Cam was not able to address it. We can discuss if you have questions. Thanks!

**Comment by gspetro-NOAA** [comment]
This issue was resolved by PR #1006.
