### ISSUE TITLE
Add RAP/HRRR like smoothing capability for RRFS

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/UPP#574]
At NOAA GSL we have been running with RAP/HRRR like smoothing for some fields.  Smoothing is carried out for the following isobaric fields:

HGT
TMP
RH
VVEL
UGRD
VGRD
ABSV

And also for sea level pressure.  We would like to get the capability into the authoritative repository, even if we decide not to do any smoothing with RRFS.

**Comment by yangfanglin** [comment]
@EricJames-NOAA Eric, can you explain or point to any documents you have how the smoothing is carried out ?

**Comment by EricJames-NOAA** [comment]
@yangfanglin I will share with you a slide deck that describes the smoothing and provides examples with and without smoothing.  The filter is based on a paper: Shapiro (1970): Smoothing, filtering, and boundary effects.  Published in Rev. Geophys. Sp. Phys.  The filter is supposed to damp 2dx waves completely but leave 4dx and longer with little damping.

**Comment by HuiyaChuang-NOAA** [comment]
@EricJames-NOAA at this morning's post processing meeting, Andrew reported Curtis and Jacob have recently decided not to do smoothing in UPP for any RRFS output.  I know you opened this issue almost a month ago and am curious whether you will still move forward with adding smoothing option to UPP?  Andrew will also bring this up at his Friday meeting with you.  I thought I document our discussions on this in the ticket.

**Comment by EricJames-NOAA** [comment]
@HuiyaChuang-NOAA thanks for bringing this up.  Yes, I'm thinking of getting rid of this issue completely.  I don't think we need to have the code in the authoritative repository.  If, for some reason, we decide to explore smoothing again in the future, we will be able to find the code in older versions of our GSL RRFS_dev branch.  Does that sound like a good approach?

**Comment by HuiyaChuang-NOAA** [comment]
> @HuiyaChuang-NOAA thanks for bringing this up. Yes, I'm thinking of getting rid of this issue completely. I don't think we need to have the code in the authoritative repository. If, for some reason, we decide to explore smoothing again in the future, we will be able to find the code in older versions of our GSL RRFS_dev branch. Does that sound like a good approach?

@EricJames-NOAA thanks for quick reply.  Your plan sounds good to me if @WenMeng-NOAA is also ok with the plan

**Comment by WenMeng-NOAA** [comment]
Eric's plan is working for me. @HuiyaChuang-NOAA and @EricJames-NOAA Could I close this issue? We might reopen it when the smoothing changes are needed in the future. Thanks!

**Comment by HuiyaChuang-NOAA** [comment]
@WenMeng-NOAA sounds good to me.

Thank you all for coordination!

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA I agree with closing this issue!  Thanks.
