### ISSUE TITLE
Add AOD  at 550 nm from MERRA2/GOCART as GFS V17 products

### ISSUE THREAD

**Issue by AnningCheng-NOAA** [NOAA-EMC/UPP#580]
Total, dust, sulfate, sea salt, organic carbon, and black carbon aerosol optical depth (AOD) at 550nm  have been outputted from UFS directly through netcdf files.  The AODs are either from MERRA2 or GOCART with cplchm=.true. The AODs are 2 dimensional, light weighted, and can be compared with aeronet, ground-based,  and satellite observations and are very useful for model evaluations and tuning purposes.

**Comment by WenMeng-NOAA** [comment]
@AnningCheng-NOAA and @yangfanglin I have been working on this request. Do you have sample GFS V17 model history files which include MERRA2 aerosol output for my UPP standalone test?

**Comment by AnningCheng-NOAA** [comment]
HI, Wen:

I have just made a new run. The files are located at:
/scratch1/NCEPDEV/stmp2/Anning.Cheng/FV3_RT/rt_309018/merra2_thompson

Please let me know if you have any questions,

Anning

**Comment by WenMeng-NOAA** [comment]
@AnningCheng-NOAA The model files you provided are in low resolution. Do you have any data from GFS V17 development? Thanks!

**Comment by AnningCheng-NOAA** [comment]
Wen:
How are those files (1536 by 3072)?:
/scratch1/NCEPDEV/global/Anning.Cheng/archive/mraero% ls *nc
gfs.t00z.sfcf2d_190601_mn.nc  gfs.t00z.sfcf2d_190701_mn.nc
gfs.t00z.sfcf2d_190805_mn.nc  gfsgfs.t00z.sfcf2d_1906.nc

**Comment by WenMeng-NOAA** [comment]
@AnningCheng-NOAA I need gfs forecast data files gfs*.atmf*nc and gfs*.sfc*nc.

**Comment by AnningCheng-NOAA** [comment]
Wen:
Here you are (120 hours forecasts). please let me know if they are what you
needed:
/scratch1/NCEPDEV/stmp2/Anning.Cheng/ROTDIRS/mraero/gfs.20190830/00/atmos%
ls *nc

**Comment by WenMeng-NOAA** [comment]
@AnningCheng-NOAA These are what I need. Thanks!
