### ISSUE TITLE
ERROR WHEN COMPILING UPP V11

### ISSUE THREAD

**Issue by Darivo-cmd** [NOAA-EMC/UPP#594]
Hi!
I'm new in UPP. I want to use it to post-process my WRF output. 
I try to install UPP over the last days but faced several chanllenge (MPI, NCEPLib-bacio, Netcdf ...). Now, requirements seems OK. 
But when I compile it (./compile_upp.sh ../ based on my location), I got the following >> 
(My SYSTEM = UBUNTU 22.04 LTS)
**************************
/home/darivo/WRF/UPP-V11.0.0/sorc/ncep_post.fd/WRFPOST.f:407:31:

  407 |                    ncid3d,comm=**_mpi_comm_world,info=mpi_info_null_**)
      |                               1
Error: Keyword argument ‘comm’ at (1) is not in the procedure
/home/darivo/WRF/UPP-V11.0.0/sorc/ncep_post.fd/WRFPOST.f:413:31:

  413 |                    ncid2d,comm=mpi_comm_world,info=mpi_info_null)
      |                               1
_**Error: Keyword argument ‘comm’ at (1) is not in the procedure**_
/home/darivo/WRF/UPP-V11.0.0/sorc/ncep_post.fd/WRFPOST.f:521:25:

  515 |           CALL mpi_bcast(im,   1,MPI_INTEGER,0, mpi_comm_comp,status)
      |                         2
......
  521 |           call mpi_bcast(global,1,MPI_LOGICAL,0,mpi_comm_comp,status)
      |                         1
Warning: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
[ 97%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.x.dir/INITPOST.F.o
make[2]: *** [sorc/ncep_post.fd/CMakeFiles/upp.x.dir/build.make:166: sorc/ncep_post.fd/CMakeFiles/upp.x.dir/WRFPOST.f.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/darivo/WRF/UPP-V11.0.0/sorc/ncep_post.fd/INITPOST.F:794:59:

  253 |       call getVariable(fileName,DateStr,DataHandle,VarName,DUM3D,       &
      |                                                           2
......
  794 |       call getVariable(fileName,DateStr,DataHandle,VarName,PT,           &
      |                                                           1
Warning: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
/home/darivo/WRF/UPP-V11.0.0/sorc/ncep_post.fd/INITPOST.F:2898:61:

 2746 |       call getIVariableN(fileName,DateStr,DataHandle,'IVGTYP',IDUMMY,    &
      |                                                              2
......
 2898 |       call getIVariableN(fileName,DateStr,DataHandle,VarName,NPHS,       &
      |                                                             1
Warning: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
make[1]: *** [CMakeFiles/Makefile2:159: sorc/ncep_post.fd/CMakeFiles/upp.x.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by WenMeng-NOAA** [comment]
@camshe and @fossell Would the UPP support be provided from EPIC/DTC end?

**Comment by fossell** [comment]
Unfortunately we currently lack resources and expertise to help with this type of error beyond a few suggestions. 

@Darivo-cmd - v11 is largely dependent on [HPC-stack](https://github.com/NOAA-EMC/hpc-stack) for installing all of the pre-req libraries. And, the provided compile_upp.sh script works as-is for supported platforms on which HPC-stack is already installed and corresponding modulefiles exist in the UPP repository. To install on other machines with the compile_upp.sh script, modifications need to made to scripts and modulefiles need to be added. If you're confident you have manually installed all of the pre-req libraries manually, you could try to manually run the commands in the compile_upp.sh to build it on the command line.

**Comment by fossell** [comment]
@FernandoAndrade-NOAA, @gspetro-NOAA - This was a user question we answered to the best of our ability. Closing the issue but it would make sense to copy this question/answer to the Q&A section of Discussions.
