### ISSUE TITLE
Update the read the docs user guide with GitHub Discussions link

### ISSUE THREAD

**Issue by camshe** [NOAA-EMC/UPP#596]
The [user guide](https://upp.readthedocs.io/en/latest/) needs to be updated to reflect the change from using the UFS forum to GitHub Discussions

The changes can be seen [here](https://upp-camshe.readthedocs.io/en/update-ug-github/CodeOverview.html)

PR: #605

**Comment by camshe** [comment]
#597

**Comment by hertneky** [comment]
@camshe Thank you for providing the link to the documentation for this PR. It allowed me to catch an oversite on our end. It appears that documentation for develop is behind release/upp_v11.0.0. i.e. changes made to v11.0.0 never got merged back to develop. So develop (and therefore your PR) does not include the documentation changes for the 2D decomp. Can you try merging release/upp_v11.0.0 documentation changes into your fork for this PR? Hopefully there are no conflicts! This [comparison](https://github.com/NOAA-EMC/UPP/compare/develop...release/upp_v11.0.0) shows the changes that need to be included in develop.
