### ISSUE TITLE
Enable GSL precip type algorithm for RRFS

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/UPP#607]
The GSL precip type algorithm (used in RAP/HRRR) is not yet working in RRFS.  We need to switch it on and make sure it works.

**Comment by yangfanglin** [comment]
Eric J,  I thought Eric Aligo's work has this covered already.  @ericaligo-NOAA Eric, do you know what is missing from your PR ?

**Comment by ericaligo-NOAA** [comment]
My PR writes out the freezing rain, snowfall and sleet/graupel and reads them into the UPP. Not sure if the ptype algorithm is something different.

**Comment by EricJames-NOAA** [comment]
I think the GSL precip type algorithm will try to use the explicit model precip variables that Eric Aligo is going to write out.  I still need to dig into the code a bit more...I am not too familiar with the algorithm.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Are you still planning to submit a PR for this issue?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Are you still planning to submit a PR for this issue?

Yes!  I have put it off until we sync GSL's RRFS_dev with EMC develop branch.  I need to touch base with Curtis about our approach, but yes I still plan to submit a PR.  Probably in a couple of weeks or so.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Thanks for clarifying. That timeline works for me.
