### ISSUE TITLE
Synchronize parm configure files for GEFSv12 to UPP develop branch for GEFSv13

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/UPP#623]
This issue is to Synchronize part configure files in release/gefs_v12 to develop branch for GEFSv13.

The files in release/gefs_v12 branch are listed below:

https://github.com/NOAA-EMC/UPP/blob/release/gefs_v12/parm/postcntrl_gefs.xml
https://github.com/NOAA-EMC/UPP/blob/release/gefs_v12/parm/postxconfig-NT-GEFS.txt

https://github.com/NOAA-EMC/UPP/blob/release/gefs_v12/parm/postcntrl_gefs_f00.xml
https://github.com/NOAA-EMC/UPP/blob/release/gefs_v12/parm/postxconfig-NT-GEFS-F00.txt

**Comment by WenMeng-NOAA** [comment]
@XianwuXue-NOAA Can you provide me the sample model history files from the GEFS V13 experiment?

**Comment by XianwuXue-NOAA** [comment]
@WenMeng-NOAA /lfs/h2/emc/ens/noscrub/xianwu.xue/UPP/z_data/sample_gefs_v13/dev/com/gefs/v12.3/gefs.20220121/12. c00 and p01.

**Comment by WenMeng-NOAA** [comment]
@XianwuXue-NOAA There is only one line difference in postcntrl_gefs.xml and postcntrl_gefs_f00.xml between  develop branch and release/gefs_v12 branch:
```
<        <shortname>CLMR_ON_ISOBARIC_SFC</shortname>
---
>        <shortname>CLWMR_ON_ISOBARIC_SFC</shortname>
```
The update in CLMR is intentional. So I would think no more syncing is needed.

**Comment by XianwuXue-NOAA** [comment]
@WenMeng-NOAA I think the xml is not the final version, if you compare the txt files, then you can find more differences

**Comment by XianwuXue-NOAA** [comment]
@WenMeng-NOAA 

For postxconfig-NT-GEFS.txt

GEFSV12 --> GEFSv13 in develop branch

- 174 --> 172
- CLWMR_ON_ISOBARIC_SFC --> CLMR_ON_ISOBARIC_SFC
- CLWMR --> CLMR
- ICIP_ON_ISOBARIC_SFC & ICSEV_ON_ISOBARIC_SFC --> missing
- PRES --> PRMSL in **PRES_ON_MEAN_SEA_LVL**
- TCDC-->HCDC, MCDC and LCDC
- entire_atmos --> entire_atmos_single_lyr. for **AVE_TCDC_ON_ENTIRE_ATMOS**


For For postxconfig-NT-GEFS-F00.txt

GEFSv12 --> GEFSv13

- 130 --> 128
- CLWMR_ON_ISOBARIC_SFC --> CLMR_ON_ISOBARIC_SFC
- CLWMR -- > CLMR
- ICIP_ON_ISOBARIC_SFC & ICSEV_ON_ISOBARIC_SFC --> missing
- PRES --> PRMSL in "PRES_ON_MEAN_SEA_LVL" ??

**Comment by WenMeng-NOAA** [comment]
@XianwuXue-NOAA All changes you list above are intended for upcoming all application implementation except missing two icing products. Yali updated their definitions and calculations in UPP.  I will consult with her . Thanks!

**Comment by WenMeng-NOAA** [comment]
I ran the UPP standalone test with GEFS V13 model files provided by @XianwuXue-NOAA. The master file has 576 fields. Comparing with the master file from GEFS V12, the following fields are missing:
```
1) 166:124072130:d=2023020200:ICIP:300 mb:6 hour fcst:ENS=low-res ctl
188:139064948:d=2023020200:ICIP:400 mb:6 hour fcst:ENS=low-res ctl
210:153981132:d=2023020200:ICIP:500 mb:6 hour fcst:ENS=low-res ctl
230:169079243:d=2023020200:ICIP:600 mb:6 hour fcst:ENS=low-res ctl
250:183771152:d=2023020200:ICIP:700 mb:6 hour fcst:ENS=low-res ctl
270:199018531:d=2023020200:ICIP:800 mb:6 hour fcst:ENS=low-res ctl

2) 167:124083983:d=2023020200:ICSEV:300 mb:6 hour fcst:ENS=low-res ctl
189:139234612:d=2023020200:ICSEV:400 mb:6 hour fcst:ENS=low-res ctl
211:154301638:d=2023020200:ICSEV:500 mb:6 hour fcst:ENS=low-res ctl
231:169403269:d=2023020200:ICSEV:600 mb:6 hour fcst:ENS=low-res ctl
251:184091231:d=2023020200:ICSEV:700 mb:6 hour fcst:ENS=low-res ctl
271:199368079:d=2023020200:ICSEV:800 mb:6 hour fcst:ENS=low-res ctl

3) 589:445342265:d=2023020200:PRMSL:mean sea level:6 hour fcst:ENS=low-res ctl
590:445933319:d=2023020200:5WAVH:500 mb:6 hour fcst:ENS=low-res ctl
```
The fields from item 1) and 2) will not be generated from the UPP develop branch. @HuiyaChuang-NOAA and @YaliMao-NOAA may decide how to generate replacement products in GEFS V13 later. 

Two fields from item 3) were removed from GFS V16 implementation. So they should be removed in GEFS V13 development.

Overall, the GEFS control files in the UPP develop branch look good for me. We may proceed to set up off-line and in-line post for GEFS V13 development. @XianwuXue-NOAA @bingfu-NOAA

**Comment by XianwuXue-NOAA** [comment]
Thanks @WenMeng-NOAA I also find first missing variables of your two items. @YaliMao-NOAA I submitted my changes to my branch. Please feel free to send me your comments.

**Comment by WenMeng-NOAA** [comment]
Wen will submit an UPP PR for updating gefs control files for gefs v13 development.

**Comment by XianwuXue-NOAA** [comment]
Thanks Wen. I will let @EricSinsky-NOAA know and follow it.

**Comment by WenMeng-NOAA** [comment]
@XianwuXue-NOAA Thanks for your follow-up information. 
@bingfu-NOAA Would it be appropriate to add @EricSinsky-NOAA as UPP collaborator for gefs v13 development?

**Comment by bingfu-NOAA** [comment]
@WenMeng-NOAA Yes, please add Eric  @EricSinsky-NOAA

**Comment by WenMeng-NOAA** [comment]
I had a discussion with @YaliMao-NOAA this morning. The decision is removing fields ICIP and ICSEV from the gefs control files which are inherited from gefsv12. A new field ICESEV(icing severity) might be added after testing in the future. @HuiyaChuang-NOAA and @bingfu-NOAA Please let me know your thoughts.

**Comment by HuiyaChuang-NOAA** [comment]
> I had a discussion with @YaliMao-NOAA this morning. The decision is removing fields ICIP and ICSEV from the gefs control files which are inherited from gefsv12. A new field ICESEV(icing severity) might be added after testing in the future. @HuiyaChuang-NOAA and @bingfu-NOAA Please let me know your thoughts.

@WenMeng-NOAA thank you for coordinating.

All, Wen, Yali, and I had a discussion in my office this morning.  Given Yali will separate WAFS from GFS for WAFS to
become an independent package, we plan to have this independent WAFS package generate icing severity from all
GEFS members too.  Thus decision to withdraw ICIP and ICSEV from all GEFS members for now.
