### ISSUE TITLE
UPP ID conflict

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#624]
It is found that UPP ID 743 is used to output instant clear-sky upward SW in CLDRAD.f and dust at isobaric in MDL2P.f; UPP ID 742 is used to output instant clear-sky downward SW in CLDRAD.f and dust at hybrid level in MDLFLD.f.

**Comment by WenMeng-NOAA** [comment]
Both instant clear-sky upward/downward SW variables are used for processing RAP/HRRR model only. @hu5970 and @EricJames-NOAA Do you think we need keep these GSL specified fields in UPP? If yes, we might reassign new UPP ID to them.

**Comment by WenMeng-NOAA** [comment]
An example of UPP ID 742 conflict can be found at GSL RRFS test at /scratch1/NCEPDEV/stmp2/Wen.Meng/post_rrfs_2022102713 on Hera.
```
1235:1020293941:d=2022102713:MASSDEN:65 hybrid level:3 hour fcst:aerosol=Dust Dry::
1433:1210237332:d=2022102713:MASSDEN:0 hybrid level:3 hour fcst:aerosol=Dust Dry::
```
The weird vertical level label in record 1433.

**Comment by hu5970** [comment]
Do we still has "instant clear-sky upward SW" "output instant clear-sky downward SW" in post_avblflds.xml?
I cannot find any UPP ID for those two variables. 
Also, in RAP/HRRR NT files, I cannot find 742/743 is used.

**Comment by WenMeng-NOAA** [comment]
> Do we still has "instant clear-sky upward SW" "output instant clear-sky downward SW" in post_avblflds.xml? I cannot find any UPP ID for those two variables. Also, in RAP/HRRR NT files, I cannot find 742/743 is used.

@hu5970 They are not defined in post_avblfld.xml,  and only read in the read interface INITPOST.F but are not generated as rap/hrrr products.

**Comment by hu5970** [comment]
I don't know if we still need those two variables. Maybe Eric can find out where those two came fom?

**Comment by EricJames-NOAA** [comment]
@hu5970 @WenMeng-NOAA I do not know the origin of those fields.  In a PR in late Nov 2022, I noticed there was an index conflict for those two variables, so I changed them to 764 and 765...they are still under those indices in post_avblflds.xml.  But it appears the indices got changed again in CLDRAD.f.  

I am fine with getting rid of these variables...if it is found we need them again, we can add them back without much difficulty since it is a simple pass through UPP without any calculations.

**Comment by WenMeng-NOAA** [comment]
@hu5970 @EricJames-NOAA Thanks for comments. I would propose to remove the blocks of writing out grib2 data in CLDRAD.f and keep reading part in INITPOST.F. Please let me know your thoughts.

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA that sounds fine to me.  Thanks.

**Comment by WenMeng-NOAA** [comment]
@hu5970 @EricJames-NOAA I will work on the PR and have both of you to review it.

**Comment by hu5970** [comment]
Thanks. Removing them sounds good.
