### ISSUE TITLE
Standalone UPP failed to generate master file if compiling in debug mode

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/UPP#627]
The standalone UPP running failed to generate master file if compiling UPP in debug mode, by modifying tests/compile_upp.sh:
1) add line: debug_opt=" -DCMAKE_BUILD_TYPE=Debug"
2) modify cmake_opts to: cmake_opts=" -DCMAKE_INSTALL_PREFIX=$prefix"${wrfio_opt}${gtg_opt}${ifi_opt}${debug_opt}

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA Would you like to submit a PR for this issue? Thanks!

**Comment by YaliMao-NOAA** [comment]
I don't have a solution yet.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA I mean adding a debug option in the build script compile_upp.sh.

**Comment by YaliMao-NOAA** [comment]
I modified compile_upp.sh more to enable the option on the  compiling command line. I made a PR.
As a heads up, wafs has no runtime error! But wafs grib2 files are not bit-wise consistent for different compiling options, debug and release.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA 

> But wafs grib2 files are not bit-wise consistent for different compiling options, debug and release.
Did you compare values of each field? Any changed values?

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA This would be a separate PR from your delivery of wafs changes for GFS V17. After your branch  "v17" is merged to the develop, do not recycle it for your wafs changes. You may open a new branch.

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA I would not expect bitwise identical results from different compiling options as long as field values are in reasonable range.

**Comment by YaliMao-NOAA** [comment]
> Did you compare values of each field? Any changed values?
I figured out the issue late yesterday and didn't have time to compare the values. Cactus is down today.

**Comment by YaliMao-NOAA** [comment]
> @YaliMao-NOAA This would be a separate PR from your delivery of wafs changes for GFS V17. After your branch "v17" is merged to the develop, do not recycle it for your wafs changes. You may open a new branch.

After you merge my branch 'v17' to your develop branch, can I delete my 'v17' branch, checkout your develop branch and create branch and recycle the name 'v17'?
