### ISSUE TITLE
Gust wind weaker than mean wind in GFS

### ISSUE THREAD

**Issue by wzzheng90** [NOAA-EMC/UPP#636]
It was reported from the weather centers that sometimes the GFS model wind gusts in GRIB files are weaker than the mean wind, especially in weak wind situations. And in general, the gusts of wind are often underestimated compared to other models.

I checked the real-time Ops GFS and also my outputs from GFS.v16.3.4 tests (ICs: 2020082300).
I did see that sometimes the GFS model wind gusts in GRIB files (GUST 180) are weaker than
the mean wind, especially during daytime.

I checked the code, "gfs_ncep_post.fd" and "CALGUST.f", which computes surface wind gust by mixing
down momentum from the level at the PBL height. My understanding is that the GUST is derived
from the winds at the PBL height, U & V(I, J, LPBL). So, sometimes, GUST is smaller than the Wind@10m.

Solution:  
We are trying one solution and using the GSL algorithm for GUST calculation in GFS (UPP).  And if this solution works well, we will also update the GUST in HAFS and RRFS.

**Comment by wzzheng90** [comment]
We tried to employ the GSL RAP algorithm to calculate GFS GUST.  Since GFS's PBL scheme does not provide "PBLHGUST", this algorithm can not be applied directly.  Nevertheless, it can still use Ri PBL height and part of GSL RAP algorithm, and GUST is derived by the whole PBL layers. 

GUST calculation for HAFS or RRFS is revised with the same approach.

**Comment by wzzheng90** [comment]
Attached please find some descriptions and results from the experiments.
[GUSTwinds_GFS_HAFS_RRFS_UPP.pptx](https://github.com/NOAA-EMC/UPP/files/10794275/GUSTwinds_GFS_HAFS_RRFS_UPP.pptx)

**Comment by WenMeng-NOAA** [comment]
@wzzheng90 You may follow the procedures at https://github.com/NOAA-EMC/UPP/wiki/UPP-Code-Development#contribute-changes-in-upp-main-development-branch-develop for submit an UPP PR.
