### ISSUE TITLE
Update branch name to release/public-v4 for public release

### ISSUE THREAD

**Issue by fossell** [NOAA-EMC/UPP#64]
It was decided to retain DTC's versions from community releases for the UFS branches and tags.  DTC's UPP is working on release V4.1 at the moment.  As such, need to change branch name that ufs uses for develop to release/public-v4.  I will create this new branch from the existing release/public-v1 when confirmed it is ok to do so.  Development will need to be done in the release/public-v4 branch after this is complete.  Note that the naming convention agreed upon for tags will be  v4.1.0.beta01 when we are ready.  @climbfuji @mark-a-potts @kgerheiser @DusanJovic-NOAA Please let me know if you are actively working on release/public-v1 branch and want me to wait, otherwise I will plan to do this today.

**Comment by climbfuji** [comment]
@fossell Hey Kate, as long as all open PRs have been merged that's fine with us. We committed an update earlier today (https://github.com/NOAA-EMC/EMC_post/pull/63) to release/public-v1. As long as that is included we are ok. Just let us know, please, and we will update the NCEPLIBS. Thanks!

**Comment by climbfuji** [comment]
@fossell now would be a great time. If you don't mind I do this right away, because I need to commit something to the NCEPLIBS umbrella build anyway.

**Comment by climbfuji** [comment]
Done. Link to PR for NCEPLIBS umbrella: https://github.com/NOAA-EMC/NCEPLIBS/pull/34

**Comment by fossell** [comment]
@climbfuji I'm in meetings until 3pm, can't get to it until then.

**Comment by climbfuji** [comment]
No worries, I created the branch. Thanks!

**Comment by fossell** [comment]
Thanks @climbfuji !!
