### ISSUE TITLE
CI failures - 'Cache not found for input keys'

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/UPP#641]
I'm creating this issue to track CI errors reported by @WenMeng-NOAA @wzzheng90. They manifest as `/opt/intel/oneapi/setvars.sh: No such file or directory` but appear to be caused by a missed cache hit in the previous step: `Cache not found for input keys:`

So far, clearing the cache and trying a modified cache key have not resolved the problem.

WW3 (@JessicaMeixner-NOAA @MatthewMasarik-NOAA) have been running into what appears to be the same issue: https://github.com/NOAA-EMC/WW3/actions/runs/4262723840/jobs/7419335683#step:4:28

**Comment by JessicaMeixner-NOAA** [comment]
Can also confirm cleaning cache does not help.  Our GNU tests are still running fine, but intel is the problem.  We do run the setvars.sh in other parts of the ci testing, so I'm not quite sure why it bails in one part and not another.

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA Thanks for helping us on this UPP CI issue. Do you suggest the UPP PR merging process wait for it solved, or we could procced with a workaround suck as temporally disable the intel build?

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA - an idea from @MatthewMasarik-NOAA : has anyone tried not using ubuntu-latest? (we'll try on our end, just wanted to ask if others had already tried).

**Comment by AlexanderRichert-NOAA** [comment]
Argh, yep, that seems to do the trick. I'll put in a bug report for GitHub Actions, meanwhile I guess just go back to ubuntu-20.04... Let's leave this issue open until that's resolved.

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA and @JessicaMeixner-NOAA Thanks for helping us this UPP CI issue.
Would you like to combine change of ubuntu version in the upcoming UPP PR #640 or submit a separate PR? @AlexanderRichert-NOAA

**Comment by AlexanderRichert-NOAA** [comment]
@WenMeng-NOAA That's up to UPP maintainers, I don't know what their policies are as far as multiple changes per PR.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA That's up to UPP maintainers, I don't know what their policies are as far as multiple changes per PR.

I am the code manager in UPP repository. Since this change is minor, I could convince the developer to combine and ask you for reviewing. Please let me know if this plan is working for you. Thanks!

**Comment by AlexanderRichert-NOAA** [comment]
Sorry I misunderstood what you meant. Yes that's fine by me!

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA saw the following warning message from CI which revert ubuntu to 20.04:
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
The CI was successful in his PR #646.
