### ISSUE TITLE
Update RRFS control file with removing some legacy fields 

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#642]
The RRFS_A and RRFS_B parallel runs have been using UPP control file postxconfig-NT-fv3lam_rrfs.txt from UPP/parm.  It indicates that the following fields are written in GRIB2 files from UPP with all missing values due to no output from model files in netcdf:
```
dataset: NATLEV:
AKHS:surface:2-3 hour ave fcst
AKMS:surface:2-3 hour ave fcst
PRES:surfacee:2-3 hour ave fcst
TMP:10 m above ground:2-3 hour ave fcst
TMP:10 m above ground:3 hour fcst
PRES:1-21 hybrid layer
PRES:1-61 hybrid layer

dataset: PRSLEV
RIME:1 hybrid level
LRGHR:entire atmosphere (considered as a single layer):0-3 hour ave fcst:
```
If no downstream applications will use them, can we remove from the UPP control file for RRFS?

**Comment by MatthewPyle-NOAA** [comment]
Of these, I'm only seeing these in current RRFS parallel output, but don't see a need to produce fields that are completely undefined.  I will make mention of this proposed removal at the RRFS developers meeting tomorrow to make sure nobody sees a reason to object.

AKHS (ave fcst)
AKMS (ave fcst)
PRES (ave fcst)
RIME
LRGHR

**Comment by JianpingHuang-NOAA** [comment]
We do not use them for AQM 7.

**Comment by WenMeng-NOAA** [comment]
@MatthewPyle-NOAA and @JianpingHuang-NOAA Thanks for comments. I also see the following two fields are in all missing values in NATLEV dataset:
```
1394:1186551131:d=2022102713:PRES:1-21 hybrid layer:3 hour fcst:
1395:1186551319:d=2022102713:PRES:1-61 hybrid layer:3 hour fcst:
```
Can you also check that?

**Comment by JianpingHuang-NOAA** [comment]
We do not need these two parameters for AQM v7.

**Comment by MatthewPyle-NOAA** [comment]
I've added those additional PRES fields to my list.  I have no idea what they are supposed to be used for.

**Comment by WenMeng-NOAA** [comment]
> I've added those additional PRES fields to my list. I have no idea what they are supposed to be used for.

@MatthewPyle-NOAA I would think they were used by CMAQ. @JianpingHuang-NOAA they are not needed by AQM v7.

**Comment by MatthewPyle-NOAA** [comment]
@WenMeng-NOAA I ran this by the RRFS developers group, and everyone was good with removing them.  Thanks for finding these fields.

**Comment by WenMeng-NOAA** [comment]
@MatthewPyle-NOAA Thanks for the coordination. This RRFS control file update would be combined with the upcoming one of RRFS PRs.

**Comment by WenMeng-NOAA** [comment]
@MatthewPyle-NOAA The removal of legacy fields in RRFS control file fv3lam_rrfs.xml will be made in the PR #640.
