### ISSUE TITLE
Restrict undefined grids in UPP computation

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#653]
It is found that the following code might have undefined grids involved in computation:
https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/INITPOST_NETCDF.f#L2863
https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/INITPOST_NETCDF.f#L2875

@EricJames-NOAA Do you think the changes of restricting undefined grids in computation should be added?

**Comment by EricJames-NOAA** [comment]
> It is found that the following code might have undefined grids involved in computation: https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/INITPOST_NETCDF.f#L2863 https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/INITPOST_NETCDF.f#L2875
> 
> @EricJames-NOAA Do you think the changes of restricting undefined grids in computation should be added?

@WenMeng-NOAA yes I think that's a good idea.  Let me know if you would like me to help with this.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA I am not sure how the values of grids on ice for "accswe_land" and the values of grids on land for "accswe_ice" on land are set. I might think the changes such as:
```
if (a==spval .and. b/=spval) then
  c=b
elseif(a/=spval .and. b==spval) then
  c=a
elseif(a/=spval .and. b/=spval) then !!might not occur ?
  c=a+b
endif
```
Please let me know your thoughts.
