### ISSUE TITLE
Add snow level variables in UPP

### ISSUE THREAD

**Issue by HuiyaChuang-NOAA** [NOAA-EMC/UPP#657]
Yuejian received a request from OWP to add snow level variables for GEFS V13.  UPP does not currently output these variables.
Jason indicated either Andrew or Gwen will work on this.  

I am opening an UPP issue now so we don't lose track of this request.
----------------------------------------------------------------------------------------------------------------------------------------------
On Thu, Mar 2, 2023 at 9:02 AM Yuejian Zhu - NOAA Federal <[yuejian.zhu@noaa.gov](mailto:yuejian.zhu@noaa.gov)> wrote:
Wen,
      We are asked from stakeholders (OWP) to provide in the GEFSv13 products (and reforecast):
snow level
freezing level
      This is the same question as Hong asked, Please let us know if we these already, or we need to generate.
      Thanks.
Yuejian

**Comment by WenMeng-NOAA** [comment]
@HongGuan-NOAA Can you confirm this new capabilities in UPP are:

- snow level HGT
- snow level RH

**Comment by HongGuan-NOAA** [comment]
I confirm this capabilities in UPP. Thanks! -Hong

**Comment by HuiyaChuang-NOAA** [comment]
Found the following NWS paper on snow level definition:

https://www.weather.gov/media/wrh/online_publications/TAs/TA1901.pdf

"The snow level is the elevation above which snow will fall, and below which rain will fall.
A mix of rain and snow may be observed at elevations within a few hundred feet of the
snow level. Snow will not accumulate on the ground below the snow level and may not
even accumulate at elevations above the snow level."

To add snow level variable, one needs to update UPP to search upward for the elevation when
qqs (suspended snow) > qqr (suspended rain)

and record the height of this elevation.

**Comment by HuiyaChuang-NOAA** [comment]
Both Jason and Huiya reached out to OWP deputy director a few weeks ago but didn't hear back from him.
Jason and Huiya discussed and decided to close this request until we hear back from OWP.

**Comment by HuiyaChuang-NOAA** [comment]
Both Jason and Huiya reached out to OWP deputy director a few weeks ago but didn't hear back from him.
Jason and Huiya discussed and decided to close this request until we hear back from OWP.
