### ISSUE TITLE
remove GTG output from RRFS parallel temporarily until UPP GTG modules are upgraded to GTG4

### ISSUE THREAD

**Issue by HuiyaChuang-NOAA** [NOAA-EMC/UPP#667]
I would like to work with @EricJames-NOAA @hu5970 at GSL to remove GTG output from RRFS parallel temporarily until UPP GTG modules are upgraded to GTG4. Current GTG3 in UPP are specifically tuned to RAP 13 km output and don't work well with RRFS 3 km output.
In addition, generating GTG is computationally expensive so let's wait to output this variable until we have properly
upgraded GTG modules.

**Comment by HuiyaChuang-NOAA** [comment]
@EricJames-NOAA @hu5970 if you can point me at your UPP control file for running RRFS parallel, I will be happy to update it to remove GTG.  If you prefer to do this yourself and merge it with your other changes, that's fine with me too.
Thanks.

**Comment by EricJames-NOAA** [comment]
@HuiyaChuang-NOAA feel free to help with this!  The UPP control files are parm/fv3lam_rrfs.xml, and parm/post_avblflds.xml.  The resulting fix file is parm/postxconfig-NT-fv3lam_rrfs.txt

**Comment by HuiyaChuang-NOAA** [comment]
@EricJames-NOAA @hu5970
As it turned out, we had a a misunderstanding about Andrew's RRFS product list.  
to make long story short, the GTG are not generated in RRFS parallels.  That's a relief.
I will go ahead and close this ticket.  

Sorry for the confusion.
