### ISSUE TITLE
soil moisture and soil temperature  outputs from RRFS (layer vs. levels below surface?)

### ISSUE THREAD

**Issue by JunDu-NOAA** [NOAA-EMC/UPP#685]
There is inconsistency between the current production and the rrfs development products for soil moisture and soil temperature. The current ones in the href are for a layer such as 0-0.1m below surface:

SOILW Volumetric Soil Moisture Content [Fraction]:0-0.1 m below ground:48 hour fcst:wt ens mean

TSOIL Soil Temperature [K]:0-0.1 m below ground:48 hour fcst:wt ens mean

However, the ones produced by the RRFS is for various levels (not layers), e.g.
677:508552449:vt=2022050602:0-0 m below ground:26 hour fcst:TSOIL Soil Temperature [K]:
678:510079807:vt=2022050602:0-0 m below ground:26 hour fcst:SOILW Volumetric Soil Moisture Content [Fraction]:
679:511266893:vt=2022050602:0.01-0.01 m below ground:26 hour fcst:TSOIL Soil Temperature [K]:
680:512795086:vt=2022050602:0.01-0.01 m below ground:26 hour fcst:SOILW Volumetric Soil Moisture Content [Fraction]:
681:513946427:vt=2022050602:0.04-0.04 m below ground:26 hour fcst:TSOIL Soil Temperature [K]:
682:515491872:vt=2022050602:0.04-0.04 m below ground:26 hour fcst:SOILW Volumetric Soil Moisture Content [Fraction]:
683:516634306:vt=2022050602:0.1-0.1 m below ground:26 hour fcst:TSOIL Soil Temperature [K]:
684:518207402:vt=2022050602:0.1-0.1 m below ground:26 hour fcst:SOILW Volumetric Soil Moisture Content [Fraction]:
685:519353098:vt=2022050602:0.3-0.3 m below ground:26 hour fcst:TSOIL Soil Temperature [K]:
686:520865929:vt=2022050602:0.3-0.3 m below ground:26 hour fcst:SOILW Volumetric Soil Moisture Content [Fraction]:
687:521989638:vt=2022050602:0.6-0.6 m below ground:26 hour fcst:TSOIL Soil Temperature [K]:
688:523475284:vt=2022050602:0.6-0.6 m below ground:26 hour fcst:SOILW Volumetric Soil Moisture Content [Fraction]:
689:524575689:vt=2022050602:1-1 m below ground:26 hour fcst:TSOIL Soil Temperature [K]:
690:526005715:vt=2022050602:1-1 m below ground:26 hour fcst:SOILW Volumetric Soil Moisture Content [Fraction]:
691:527038595:vt=2022050602:1.6-1.6 m below ground:26 hour fcst:TSOIL Soil Temperature [K]:
692:528433198:vt=2022050602:1.6-1.6 m below ground:26 hour fcst:SOILW Volumetric Soil Moisture Content [Fraction]:
693:529486773:vt=2022050602:3-3 m below ground:26 hour fcst:TSOIL Soil Temperature [K]:
694:530099686:vt=2022050602:3-3 m below ground:26 hour fcst:SOILW Volumetric Soil Moisture Content [Fraction]:

**Comment by WenMeng-NOAA** [comment]
It appears to me that the soil fields are added in RRFS control file as:

 ```
       <param>
       <shortname>TSOIL_ON_DEPTH_BEL_LAND_SFC</shortname>
       <pname>TSOIL</pname>
       <scale_fact_fixed_sfc1>2</scale_fact_fixed_sfc1>
       <level>0. 1. 4. 10. 30. 60. 100. 160. 300.</level>
       <scale_fact_fixed_sfc2>2</scale_fact_fixed_sfc2>
       <level2>0. 1. 4. 10. 30. 60. 100. 160. 300.</level2>
       <scale>4.0</scale>
       </param>

 <param>
       <shortname>SOILW_ON_DEPTH_BEL_LAND_SFC</shortname>
       <pname>SOILW</pname> 
       <scale_fact_fixed_sfc1>2</scale_fact_fixed_sfc1>
       <level>0. 1. 4. 10. 30. 60. 100. 160. 300.</level>
       <scale_fact_fixed_sfc2>2</scale_fact_fixed_sfc2>
       <level2>0. 1. 4. 10. 30. 60. 100. 160. 300.</level2>
       <scale>3.0</scale>
       </param>
```
@EricJames-NOAA Do you think the setting of level should modified? e.g.
<level>0.</level>
<level2>1.</level2>
Thanks!

**Comment by WenMeng-NOAA** [comment]
According to @MatthewPyle-NOAA:

>  Sorry to jump in a bit late, but I think this is purely a consequence of using the RUC LSM in RRFS.  One difference is that the RUC LSM defines soil output at a fixed depth rather than over a layer like the NOAH LSM.   It also has more layers than NOAH, which combined with the differences described in the previous sentence makes a 1:1 matchup with legacy systems using NOAH impossible.  I'm not sure anything is mislabeled - it is just describing output from a different LSM.

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA I think @MatthewPyle-NOAA is right...the RAP / HRRR are also labeled like this (same depths for level and level2) because those models use RUC LSM.  So I think we can leave this as is.

**Comment by WenMeng-NOAA** [comment]
I do see the rap products as:
```
1009:260334040:d=2020072316:TSOIL:0-0 m below ground:16 hour fcst:
1010:261006803:d=2020072316:SOILW:0-0 m below ground:16 hour fcst:
1011:261323991:d=2020072316:TSOIL:0.01-0.01 m below ground:16 hour fcst:
1012:261999770:d=2020072316:SOILW:0.01-0.01 m below ground:16 hour fcst:
1013:262315388:d=2020072316:TSOIL:0.04-0.04 m below ground:16 hour fcst:
1014:262729882:d=2020072316:SOILW:0.04-0.04 m below ground:16 hour fcst:
1015:263045727:d=2020072316:TSOIL:0.1-0.1 m below ground:16 hour fcst:
1016:263722062:d=2020072316:SOILW:0.1-0.1 m below ground:16 hour fcst:
1017:264037798:d=2020072316:TSOIL:0.3-0.3 m below ground:16 hour fcst:
1018:264715991:d=2020072316:SOILW:0.3-0.3 m below ground:16 hour fcst:
1019:265029935:d=2020072316:TSOIL:0.6-0.6 m below ground:16 hour fcst:
1020:265709041:d=2020072316:SOILW:0.6-0.6 m below ground:16 hour fcst:
1021:266022340:d=2020072316:TSOIL:1-1 m below ground:16 hour fcst:
1022:266692963:d=2020072316:SOILW:1-1 m below ground:16 hour fcst:
1023:267005619:d=2020072316:TSOIL:1.6-1.6 m below ground:16 hour fcst:
1024:267679294:d=2020072316:SOILW:1.6-1.6 m below ground:16 hour fcst:
1025:267995339:d=2020072316:TSOIL:3-3 m below ground:16 hour fcst:
1026:268632229:d=2020072316:SOILW:3-3 m below ground:16 hour fcst:
```
So I would think no action is needed for this issue, right? @JunDu-NOAA, @EricJames-NOAA @MatthewPyle-NOAA

**Comment by JunDu-NOAA** [comment]
If so, leave as is. On Apr 5, 2023, at 5:51 PM, WenMeng-NOAA ***@***.***> wrote:﻿
I do see the rap products as:
1009:260334040:d=2020072316:TSOIL:0-0 m below ground:16 hour fcst:
1010:261006803:d=2020072316:SOILW:0-0 m below ground:16 hour fcst:
1011:261323991:d=2020072316:TSOIL:0.01-0.01 m below ground:16 hour fcst:
1012:261999770:d=2020072316:SOILW:0.01-0.01 m below ground:16 hour fcst:
1013:262315388:d=2020072316:TSOIL:0.04-0.04 m below ground:16 hour fcst:
1014:262729882:d=2020072316:SOILW:0.04-0.04 m below ground:16 hour fcst:
1015:263045727:d=2020072316:TSOIL:0.1-0.1 m below ground:16 hour fcst:
1016:263722062:d=2020072316:SOILW:0.1-0.1 m below ground:16 hour fcst:
1017:264037798:d=2020072316:TSOIL:0.3-0.3 m below ground:16 hour fcst:
1018:264715991:d=2020072316:SOILW:0.3-0.3 m below ground:16 hour fcst:
1019:265029935:d=2020072316:TSOIL:0.6-0.6 m below ground:16 hour fcst:
1020:265709041:d=2020072316:SOILW:0.6-0.6 m below ground:16 hour fcst:
1021:266022340:d=2020072316:TSOIL:1-1 m below ground:16 hour fcst:
1022:266692963:d=2020072316:SOILW:1-1 m below ground:16 hour fcst:
1023:267005619:d=2020072316:TSOIL:1.6-1.6 m below ground:16 hour fcst:
1024:267679294:d=2020072316:SOILW:1.6-1.6 m below ground:16 hour fcst:
1025:267995339:d=2020072316:TSOIL:3-3 m below ground:16 hour fcst:
1026:268632229:d=2020072316:SOILW:3-3 m below ground:16 hour fcst:

So I would think no action is needed for this issue, right? @JunDu-NOAA, @EricJames-NOAA @MatthewPyle-NOAA

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA @JunDu-NOAA @MatthewPyle-NOAA Thanks for your quick responses. I will close this issue now.
