### ISSUE TITLE
How to use UPP-v11 to postprocess wrfout to grib2?

### ISSUE THREAD

**Issue by minglinz** [NOAA-EMC/UPP#710]
I have compiled UPP-v11 with NCEPLIBS-wrf_io and I set wrfio_opt=" -DBUILD_WITH_WRFIO=OFF". (It means set "build without WRF-IO"= False?) 
But I can't find any scripts or options that provide the method to process wrfout* ncfiles. I only find an example "run_upp" in the subdirectory "scripts", but it seems only support for 'GFS' or 'LAM'.

**Comment by gspetro-NOAA** [comment]
Hello @SiriusDanica666,

It seems like your question is most appropriate to the GitHub Discussion Q & A forum, so I am going to convert this from an issue to a discussion and post there. 

Best,
Gillian Petro | Advanced User Support (AUS) Team
