### ISSUE TITLE
How to use UPP-v11 to post-processes the NETCDF files from the wrfout to grib2 

### ISSUE THREAD

**Issue by minglinz** [NOAA-EMC/UPP#711]
It seems that there is not any scripts or options for wrfout in UPP-v11/scripts?
And I didn't find options for WRF in run_upp.
I have compiled UPP-v11 with NCEPLIBS_WRF_io, and I have set wrfio_opt=" -DBUILD_WITH_WRFIO=OFF".

**Comment by gspetro-NOAA** [comment]
Hello @SiriusDanica666,

It seems like your question is most appropriate to the UPP Discussions Q & A forum, so I am going to convert this from an issue to a discussion. 

As I mentioned in your other post (Discussion #712 ), Support for WRF ended a few years ago, and we unfortunately don’t have the resources to dig into WRF-related issues. That said, you may find some useful information in [this post](https://github.com/NOAA-EMC/UPP/discussions/679), which talks about some of the changes that are required for running WRF with UPP v11.0.0. You may also find support on the [WRF/MPAS forum](https://forum.mmm.ucar.edu/forums/wrf-upp.133/). 

As to `-DBUILD_WITH_WRFIO=OFF`, it seems from the name it would set build _**WITH**_ WRF-IO to False, but that is merely an educated guess on my part. Adding the -w option to build _without_ WRF-IO seems to set `wrfio_opt=" -DBUILD_WITH_WRFIO=OFF”` on line 42 of `compile.sh`. My guess is that you would need to leave it `ON`, which is the default.

Not sure what your current WRF work entails, but it might be worth switching to the Unified Forecast System (UFS). There is a lot more support available for the UFS, and the UPP is included in certain application workflows, like the [Short-Range Weather (SRW) Application](https://github.com/ufs-community/ufs-srweather-app) workflow. 

Best,
Gillian Petro | Advanced User Support (AUS) Team
