### ISSUE TITLE
Duplicate UPP ID 689

### ISSUE THREAD

**Issue by gspetro-NOAA** [NOAA-EMC/UPP#718]
In `post_avblflds.xml`, 689 is used twice as a `post_avblfldidx` attribute, once for `NH4_ON_HYBRID_LVL` and once for `SU_AER_SFC_MASS_CON`. Since `post_avblfldidx` corresponds to the UPP ID, which is a unique ID, this needs to be fixed so that each variable in fact has its own unique ID.

**Comment by WenMeng-NOAA** [comment]
@zhanglikate It appears to me that output of NH4_ON_HYBRID_LVL is in MDLFLD.f. Do you know where output of SU_AER_SFC_MASS_CON is? Do you think it is needed in UPP? If yes, we might assign a new ID for it. Thanks!

**Comment by zhanglikate** [comment]
> @zhanglikate It appears to me that output of NH4_ON_HYBRID_LVL is in MDLFLD.f. Do you know where output of SU_AER_SFC_MASS_CON is? Do you think it is needed in UPP? If yes, we might assign a new ID for it. Thanks!

@WenMeng-NOAA I don't think we are still using 689-698 outputs now (includes SU_AER_SFC_MASS_CON ), which are in the old NGAC version's output. But we can save these for future chemical output. Thanks.

**Comment by WenMeng-NOAA** [comment]
@zhanglikate Thanks for clarifying. In that case, I will comment out definition of SU_AER_SFC_MASS_CON (689) and keep 690-698 in post_avblflds.xml. Please let me know if this solution is working for you.

**Comment by zhanglikate** [comment]
@WenMeng-NOAA That sounds good to me. Thanks.

**Comment by WenMeng-NOAA** [comment]
@zhanglikate and @gspetro-NOAA The change was combined in the PR #721. Please review it.
