### ISSUE TITLE
A confusion in your installation guide

### ISSUE THREAD

**Issue by stephentjemkes** [NOAA-EMC/UPP#723]
Hi,

I am trying to install the UPP on my ubuntu system and try to follow your installation guide systematically as the first attempt to install UPP failed.

The systematic use of cmake utility throughout the EMC stack makes it very clean. Thank you for that. 
I encountered a confusing item though. In the prerequisites the following library is listed: 

**https://github.com/NOAA-EMC/NCEPLIBS-w3nco**

the installation guide of this library indicates that 

*This library is deprecated and will not be in the next release of NCEPLIBS. All code will be migrated to the [NCEPLIBS-w3emc](https://github.com/NOAA-EMC/NCEPLIBS-w3emc) library will full backward compatibility maintained.*

to me this reads that for a new installation there is no need to have w3nco library as the most recent w3emc library (which has been updated a few months ago, and has been compiled successfullly with the optional bufr library on my system) has all the code which is embedded in the w3nco library. 

If confirmed by you can you add a note onto your installation guide for future reference?

many thanks
stephen

**Comment by gspetro-NOAA** [comment]
Hi Stephen,

Could you link to the part of the installation guide where you are seeing this message? I'm not sure that it appears in the UPP User's Guide itself, but I could be wrong. If it's in a different installation guide (e.g., NCEPLIBS), you would need to post the issue in that repository. That said, current practice is to install bundled prerequisites, including NCEPLIBS, via [HPC-Stack](https://github.com/noaa-emc/hpc-stack) or [spack-stack](https://github.com/JCSDA/spack-stack), and if you're taking that approach, the update would need to go into those UGs. Currently, HPC-Stack is being deprecated, and spack-stack is in the process of being validated by the WM, so things are in flux. Regardless, I do think it's a good idea to add a specific list of prerequisites to the UPP User's Guide, so I am going to try to do that in the next few days. 

Best,
Gillian Petro

**Comment by stephentjemkes** [comment]
Dear Gillian,
To be precise the https://github.com/NOAA-EMC/UPP repository has on the home page a list of packages. 
this is also in the README.md file (as the homepage just displays this md file)

## Prerequisites

The UPP requires certain NCEPLIB packages to be installed via
the HPC-Stack project.  

- [NCEPLIBS-g2](https://github.com/NOAA-EMC/NCEPLIBS-g2)
- [NCEPLIBS-g2tmpl](https://github.com/NOAA-EMC/NCEPLIBS-g2tmpl)
- [NCEPLIBS-sp](https://github.com/NOAA-EMC/NCEPLIBS-sp)
- [NCEPLIBS-ip](https://github.com/NOAA-EMC/NCEPLIBS-ip)
- [NCEPLIBS-bacio](https://github.com/NOAA-EMC/NCEPLIBS-bacio)
- [NCEPLIBS-w3emc](https://github.com/NOAA-EMC/NCEPLIBS-w3emc)
- [NCEPLIBS-w3nco](https://github.com/NOAA-EMC/NCEPLIBS-w3nco)
- [CRTM](https://github.com/noaa-emc/emc_crtm)

and if you would follow the **[NCEPLIBS-w3nco](https://github.com/NOAA-EMC/NCEPLIBS-w3nco)** link it is indicated that this package is embedded in the w3emc package since release 2.8 of w3emc. 

Current release of w3emc is 2.10 so there is no need to have w3nco listed as pre-requisite (provided user is using latest w3emc)

Indeed it would be very good to have a note upfront that hpc-stack is deprecated. 

please also read my other two issues open. as i can close them 
-jasper 2.0.25 is supported a more recent version of jasper is causing confusion
and the CMakeList.txt in 

sorc/ncep_post.fd/CMakeLists.txt

has a reference to bacio_4 which is not build under the current stack. bacio.a is build hence the CMakeList.txt might need an update

my current building order is 
bacio bufr w3emc g2
g2tmpl
sp ip sigio sfcio nemsio gfsio
and finally 
crtm



and with the update in the CMakeList it compiles successfully


thanks to the consistent use of cmake, installation through a script is very convenient. Thank you for the effort

**Comment by FernandoAndrade-NOAA** [comment]
Hi Stephen, to clear up some confusion, the epic hpc-stack does utilize the NCEPLIBS-w3emc library version 2.9.2. Thanks for the catch with w3nco

**Comment by FernandoAndrade-NOAA** [comment]
UPP prerequisites have been clarified in PR #722 with updates to the README
