### ISSUE TITLE
Cmake throws some errors

### ISSUE THREAD

**Issue by stephentjemkes** [NOAA-EMC/UPP#724]
Hi,

After installing the prerequisites for UPP from scratch i ran into the same error as i had with my first attempt
the error message indicates that bacio is not installed although this library is found (see the bold)
so what is missing here?

the second error message indicates that a *g2c* library is missing. A Google search indicates that this is a fix for f77 compilers 

*Even after 13 years this 64-bit library can be installed by direct [download](https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/) using commands below*

Apparently it seems important to include this library, can you confirm and add a note to the installation guide that this is a pre-requisite?

many thanks for your feedback

stephen

===============================================================
./compile_upp.sh -p ${HOME}/local -w -v -d
Machine:  unknown
-- The Fortran compiler identification is GNU 11.3.0
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /bin/f95 - skipped
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_C: /home/stephen/local/lib/libmpi.so (found version "4.0") 
-- Found MPI_CXX: /home/stephen/local/lib/libmpicxx.so (found version "4.0") 
-- Found MPI_Fortran: /home/stephen/local/lib/libmpifort.so (found version "4.0") 
-- Found MPI: TRUE (found version "4.0")  
-- Found NetCDF: /home/stephen/local/include (found version "4.8.1") found components: Fortran 
-- FindNetCDF defines targets:
--   - NetCDF_VERSION [4.8.1]
--   - NetCDF_PARALLEL [FALSE]
--   - NetCDF_C_CONFIG_EXECUTABLE [/home/stephen/local/bin/nc-config]
--   - NetCDF::NetCDF_C [SHARED] [Root: /home/stephen/local] Lib: /home/stephen/local/lib/libnetcdf.so 
--   - NetCDF_Fortran_CONFIG_EXECUTABLE [/home/stephen/local/bin/nf-config]
--   - NetCDF::NetCDF_Fortran [SHARED] [Root: /home/stephen/local] Lib: /home/stephen/local/lib/libnetcdff.so 
-- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components: Fortran 
**-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")**
-- Found crtm: /home/stephen/local/lib/libcrtm.a (found version "2.3.0")
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")
-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")
-- Found bufr: /home/stephen/local/lib/libbufr_4.a (found version "12.0.0")
-- Found w3emc: /home/stephen/local/lib/libw3emc_4.a (found version "2.10.0")
-- Found g2: /home/stephen/local/lib/libg2_4.a (found version "3.5.0")
-- Found g2tmpl: /home/stephen/local/lib/libg2tmpl.a (found version "1.10.2")
-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")
-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")
-- Found bufr: /home/stephen/local/lib/libbufr_4.a (found version "12.0.0")
-- Found w3emc: /home/stephen/local/lib/libw3emc_4.a (found version "2.10.0")
-- Found MPI: TRUE (found version "4.0") found components: Fortran 
-- Found nemsio: /home/stephen/local/lib/libnemsio.a (found version "2.5.4")
-- Found sfcio: /home/stephen/local/lib/libsfcio.a (found version "1.4.1")
-- Found sigio: /home/stephen/local/lib/libsigio.a (found version "2.3.2")
-- Found sp: /home/stephen/local/lib/libsp_4.a (found version "2.4.0")
**-- Found bacio: /home/stephen/local/lib/libbacio.a (found version "2.6.0")**
-- Found bufr: /home/stephen/local/lib/libbufr_4.a (found version "12.0.0")
-- Found w3emc: /home/stephen/local/lib/libw3emc_4.a (found version "2.10.0")
-- Configuring done
CMake Error at sorc/ncep_post.fd/CMakeLists.txt:190 (add_library):
  **Target "upp" links to target "bacio::bacio_4" but the target was not found.**
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at sorc/ncep_post.fd/CMakeLists.txt:190 (add_library):
  **Target "upp" links to target "g2c::g2c" but the target was not found.**
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at sorc/ncep_post.fd/CMakeLists.txt:229 (add_executable):
  Target "upp.x" links to target "bacio::bacio_4" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at sorc/ncep_post.fd/CMakeLists.txt:229 (add_executable):
  Target "upp.x" links to target "g2c::g2c" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by stephentjemkes** [comment]
Hi,

just a short update to this issue which can be closed. 
the use of jasper v2.0.25 seems to resolve the g2c issue. 
and a modification in
sorc/ncep_post.fd/CMakeLists.txt
is needed to point to the installed bacio library
currently the CMakeList.txt file points to a bacio_4 library and needs to point to bacio

after these modifications compilation concluded successfully

**Comment by FernandoAndrade-NOAA** [comment]
Hi Stephen,

Thanks for posting an update here, I'll go ahead and close this out and we can continue in #725
