### ISSUE TITLE
Sea Salt Scavenging Flux Input

### ISSUE THREAD

**Issue by gspetro-NOAA** [NOAA-EMC/UPP#726]
In lines 3501-3511 of INITPOST_NETCDF.f, seas1wtc is getting assigned to VarName in each line. In other similar code blocks, seas1wtc would be assigned when K == 1, seas2wtc where K == 2, and so on. Currently, the code reads:

```
! retrieve seasalt scavenging fluxes
      do K = 1, nbin_ss
       if ( K == 1) VarName='seas1wtc'
       if ( K == 2) VarName='seas1wtc'
       if ( K == 3) VarName='seas1wtc'
       if ( K == 4) VarName='seas1wtc'
       if ( K == 5) VarName='seas1wtc'
      call read_netcdf_2d_para(ncid2d,ista,ista_2l,iend,iend_2u,jsta,jsta_2l,jend,jend_2u,&
      spval,VarName,chem_2d)
      sssv(1:im,jsta_2l:jend_2u,K)=chem_2d(1:im,jsta_2l:jend_2u)
       enddo
```

It seems like it should be:
```
! retrieve seasalt scavenging fluxes
      do K = 1, nbin_ss
       if ( K == 1) VarName='seas1wtc'
       if ( K == 2) VarName='seas2wtc'
       if ( K == 3) VarName='seas3wtc'
       if ( K == 4) VarName='seas4wtc'
       if ( K == 5) VarName='seas5wtc'
      call read_netcdf_2d_para(ncid2d,ista,ista_2l,iend,iend_2u,jsta,jsta_2l,jend,jend_2u,&
      spval,VarName,chem_2d)
      sssv(1:im,jsta_2l:jend_2u,K)=chem_2d(1:im,jsta_2l:jend_2u)
       enddo
```

Thanks to @hertneky for noticing this! :)

**Comment by WenMeng-NOAA** [comment]
@hertneky @gspetro-NOAA Thanks for addressing this issue in UPP code.

**Comment by WenMeng-NOAA** [comment]
@zhanglikate You may see seas*wtc configuration in offine post interface at
https://github.com/NOAA-EMC/UPP/blob/develop/sorc/ncep_post.fd/INITPOST_NETCDF.f#L3503

The inline post interface look good to me:
https://github.com/NOAA-EMC/fv3atm/blob/develop/io/post_fv3.F90#L2619

Could you confirm the bug? I can submit the quick fix for it.

**Comment by zhanglikate** [comment]
Yes. You are right, can you help to quickly fix it? Thanks.

Kate

**Comment by WenMeng-NOAA** [comment]
@zhanglikate Thanks for confirming. I will submit a PR for the fix and have you to review.
