### ISSUE TITLE
Transition GFS to use GSL P-type

### ISSUE THREAD

**Issue by HuiyaChuang-NOAA** [NOAA-EMC/UPP#735]
Eric J. from GSL updated UPP to support output of GSL P-type for RRFS v1.

Huiya emailed Fanglin and RRFS project managers about switching GFS v17 to use GSL Ptype.
Fanglin asked Ruiyu to investigate this.  Wen indicated GFS model output may need to be updated
to provide UPP with input it needs to derive GSL Ptype such as instantaneous rates of rain, snow graupel.

Additionally, Fanglin asked whether GSL Ptype will work for other MP schemes.  Wen confirmed the
test case provided by Eric J. was for Thompson MP scheme.  Huiya suggested to add an if statement in
UPP to only use GSL Ptype when Thompson MP is used until GSL Ptype has been tested for other MP schemes.

**Comment by WenMeng-NOAA** [comment]
@HuiyaChuang-NOAA In UPP code, GSL P-type and non-GSL P-type do not share the same ID. We can update UPP control file to switch to GSL P-type.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA  Did GSL side test GSL P-type with non Thompson MP?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Did GSL side test GSL P-type with non Thompson MP?

No.  It would take some thought...for one thing, I don't think GFS has a 1-h precip bucket, which is used in the GSL p-type diagnosis.

**Comment by HuiyaChuang-NOAA** [comment]
> > @EricJames-NOAA Did GSL side test GSL P-type with non Thompson MP?
> 
> No. It would take some thought...for one thing, I don't think GFS has a 1-h precip bucket, which is used in the GSL p-type diagnosis.

Thank you, Eric for confirming this.  Would it be much work for GFS to output 1 hour precip bucket?

**Comment by EricJames-NOAA** [comment]
> > > @EricJames-NOAA Did GSL side test GSL P-type with non Thompson MP?
> > 
> > 
> > No. It would take some thought...for one thing, I don't think GFS has a 1-h precip bucket, which is used in the GSL p-type diagnosis.
> 
> Thank you, Eric for confirming this. Would it be much work for GFS to output 1 hour precip bucket?

@HuiyaChuang-NOAA I'm not sure!  I have no experience with GFS.  Maybe it wouldn't be too hard.

**Comment by yangfanglin** [comment]
@HuiyaChuang-NOAA I don't think we can change GFS precip bucket for products, but hourly precip can definitely be derived from accumulated precip with a 6-hr bucket as long as the output frequency is hourly.   Note though, in operation, GFS output frequency is hourly up to 120 hours of forecast, then 3 hourly.  Running UPP offline will not be able to get hourly precip after 120 hours of forecast.

@EricJames-NOAA Eric, has the GSL P-Type been tested for NSSL Microphysics within the RRFS ?   I thought  RRFS will use NSSL MP in a few of the ensemble members.

**Comment by EricJames-NOAA** [comment]
> @HuiyaChuang-NOAA I don't think we can change GFS precip bucket for products, but hourly precip can definitely be derived from accumulated precip with a 6-hr bucket as long as the output frequency is hourly. Note though, in operation, GFS output frequency is hourly up to 120 hours of forecast, then 3 hourly. Running UPP offline will not be able to get hourly precip after 120 hours of forecast.
> 
> @EricJames-NOAA Eric, has the GSL P-Type been tested for NSSL Microphysics within the RRFS ? I thought RRFS will use NSSL MP in a few of the ensemble members.

@yangfanglin no we have not yet tested the GSL p-type with NSSL microphysics!  That is probably something that should be examined if it is decided to have multiple MP schemes in the ensemble.

**Comment by HuiyaChuang-NOAA** [comment]
> @HuiyaChuang-NOAA I don't think we can change GFS precip bucket for products, but hourly precip can definitely be derived from accumulated precip with a 6-hr bucket as long as the output frequency is hourly. Note though, in operation, GFS output frequency is hourly up to 120 hours of forecast, then 3 hourly. Running UPP offline will not be able to get hourly precip after 120 hours of forecast.
> 
> @EricJames-NOAA Eric, has the GSL P-Type been tested for NSSL Microphysics within the RRFS ? I thought RRFS will use NSSL MP in a few of the ensemble members.

@yangfanglin I am not suggesting changing GFS precip bucket to 1 hour but rather to see we can use the bucket code in place for RRFS to also output hourly bucket precip in model output

**Comment by WenMeng-NOAA** [comment]
Non-GSL P-type definitions in UPP(see post_avblflds.xml) :

GRIB2_NMAE    |  UPP_ID  |
------------------|----------
CRAIN                | 160
CSNOW             | 551
CICEP                 |552
CFRZR                |553


GSL P-type definitions in UPP:
GRIB2_NMAE   |   UPP_ID
-----------------|----------
CRAIN      |          407
CSNOW     |        559
CICEP        |         560
CFRZR       |         561

@RuiyuSun You might refer the above UPP IDs for your evaluation of generating GSL instant P-type for GFS V17 from UPP.

**Comment by WenMeng-NOAA** [comment]
@RuiyuSun For your reference, there were two PRs submitted by @EricJames-NOAA for outputting GSL P-type for RRFS:

- #695 
- #730

**Comment by WenMeng-NOAA** [comment]
Adding some comments from the previous discussion.
----------------------------------------------------------------
From Fanglin:

> Thanks for the note.   Using the GSL P-type algorithm to create instantaneous precip types is fine.   My understanding is that  time averaged rain, snow, ice,  graupel, freezing rain etc  from the microphysics/LSM that  Eric Aligo added to the UFS will also be included in the output. 
> 
> Ruiyu,  could you please run a gfsv17 case to test the GSL P-types?  Both RRFS and GFS are using the same Thompson MP but aerosol awareness　is turned off in GFSv17.
> 
> Has Eric James tested the P-type for NSSL MP which will be used in A few members of the RRFS ensemble?
> 
> Will the P-Type work for GFDL MP?  HAFS-A is using GFDL MP.

From Geoff:

> What does "time-averaged" rain, snow...  mean?      I know that Eric is adding the accumulations of the different precip 
>types, which is awesome.    Is that what you meant?


> 
> Since we're discussing precip type, this would be a good opportunity to discuss the GFS output.   Right now, the GFS has instantaneous precip type (rain, snow, freezing rain, ice pellets) and "averaged" precip type (the same 4 types).   The averaged field causes a LOT of confusion in the field.     The definition suggests that some sort of averaging of the occurrence of the different types is performed over the defined time period, but it's really just computing an instantaneous precip type at any point that had precip occur during the recent period (usually 3 or 6 hours).    The original thought behind computing it this way was to account for the model potentially having spatial errors in the instantaneous location - it was a nice idea, but computing precip type at points where the model has dried out the column and is no longer precipitating leads to answers that are somewhat unscientific.   
> 
> The "averaged" approach was done in the GFS until GFSv15, when I successfully lobbied to have the instantaneous precip type fields added.    I wanted a pure replacement, but the (understandable) decision was to have both versions in the model for a while to allow users to make the transition and then eventually remove the averaged values.    I think that GFSv17 would be a good time to remove the averaged values, especially if we're switching to the microphysics-based precip type approach.   I think we'll run into problems trying to compute precip type with microphysical output at points where no hydrometeors are falling.

**Comment by WenMeng-NOAA** [comment]
@RuiyuSun has some preliminary results. Could you share in this issue for discussion?

**Comment by WenMeng-NOAA** [comment]
I looked into GFS model output files Ruiyu provided. It seems to me the following variables are not in GFS output:

- time step snow fall "snow"
- time step graupel "graupel"
- bucket snow fall "tsnowp"

**Comment by RuiyuSun** [comment]
> @RuiyuSun has some preliminary results. Could you share in this issue for discussion?
This is [the link](https://docs.google.com/presentation/d/13FY1s0uohr6r9njLRm9DOeNlrzgAVjM5/edit#slide=id.p1) to the preliminary results

**Comment by yangfanglin** [comment]
@HuiyaChuang-NOAA @GeoffManikin-NOAA Hui-ya and Geoff, I'd suggest we only provide GFS instantaneous precip types (after the [average precip types](https://github.com/NOAA-EMC/UPP/issues/738) are removed).   Implementing the "GSL P-Type" in GFS/GEFS may not be that straightforward because 1) GSL P-require hourly precip but GFS output frequency is usually 3-hourly in experimental runs and hourly up to 120 hours then 3 hourly in operation.  GEFS has even less frequent output.  It is impossible to write hourly output for global MRW/S2S aplications, no matter the accumulation bucket is hourly or six hourly.  Adding a new forecast file to only save hourly precip is cumbersome, let alone to say more model code changes are required.  2) The "GSL P-Type" decision tree may require much more scrutiny at locations outside of the CONUS, especially over open water and the polar regions.

**Comment by GeoffManikin-NOAA** [comment]
@Fanglin Yang - NOAA Federal ***@***.***>  @Hui-Ya Chuang -
NOAA Federal ***@***.***>

   1)    I spoke with Curtis of GSL about not having hourly GFS output
through the length of the forecast, and his thought is that while it's not
ideal, we should still be ok for the GFS.   We won't need to try to
generate hourly output at the longer ranges.   6-hourly output later in the
GEFS is more complicated, but even then, he thinks that the code will work
and look reasonable (we might have p-type computed at a bunch of additional
points, but that's ok).

    2)    I don't agree that we should be concerned that the GSL p-type
scheme might break down over polar or open water regions.  The HRRR is run
over Alaska with no p-type issues.   Recall also that this scheme also runs
in the RAP which covers a full North American domain that includes polar
regions and plenty of open water.   Ultimately, if the microphysics is
generating reasonable information about the hydrometeors, the p-type code
will respond appropriately.

                              -Geoff

----------------------------------------------------
*Geoff Manikin*
Verification and Validation Project and Model Evaluation Group Lead
Verification, Post-Processing, and Product Generation Branch
NOAA/NWS/NCEP/Environmental Modeling Center
College Park, MD 20740

**Comment by RuiyuSun** [comment]
> > @RuiyuSun has some preliminary results. Could you share in this issue for discussion?
> > This is [the link](https://docs.google.com/presentation/d/13FY1s0uohr6r9njLRm9DOeNlrzgAVjM5/edit#slide=id.p1) to the preliminary results

It turned out that some of the variables needed by the algorithm are not in the GFS current history files. Correct inputs to the algorithm are required in the GFS history file and used in the algorithm.

**Comment by RuiyuSun** [comment]
Update: [Most updated](https://docs.google.com/presentation/d/1U-ooGn7NYaF8bmyayUoSmd7BKgxMjn7G/edit#slide=id.p1) results were discussed. A major discussion is if it is possible to write out the hourly bucket from GFS. It is possible but will take some effort to change the code and convince the users to use the hourly bucket instead of the 6 hourly bucket. Given the amount of work, the decision is that this update will not be included in this GFSV17 and will be considered in the later version of the GFS. But the testing will be continued.

**Comment by WenMeng-NOAA** [comment]
@HuiyaChuang-NOAA @yangfanglin @GeoffManikin-NOAA Please let me know if you have more comments. If not, may I close this issue?
