### ISSUE TITLE
Remove time averaged P-type products for GFS V17

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#738]
Per EMC MEG team's suggestion, time averaged P-type products should be removed for GFS V17.

**Comment by yangfanglin** [comment]
Wen, can you remind us how the following instantaneous and averaged P-types are computed in GFSv17/GFSv16 ? Are they all based on the CALPRECIP algorithm but computed with instantaneous precip and time averaged precip, respectively ? 

865:2393279670:d=2023070400:CSNOW Categorical Snow [-]:surface:120 hour fcst:
866:2393366312:d=2023070400:CICEP Categorical Ice Pellets [-]:surface:120 hour fcst:
867:2393366534:d=2023070400:CFRZR Categorical Freezing Rain [-]:surface:120 hour fcst:
868:2393370124:d=2023070400:CRAIN Categorical Rain [-]:surface:120 hour fcst:
869:2393812156:d=2023070400:CSNOW Categorical Snow [-]:surface:114-120 hour ave fcst:
870:2393870101:d=2023070400:CICEP Categorical Ice Pellets [-]:surface:114-120 hour ave fcst:
871:2393870354:d=2023070400:CFRZR Categorical Freezing Rain [-]:surface:114-120 hour ave fcst:
872:2393873818:d=2023070400:CRAIN Categorical Rain [-]:surface:114-120 hour ave fcst:

**Comment by WenMeng-NOAA** [comment]
@yangfanglin That's right. The only difference of calculation is that one using instant precp. rate and another using time averaged precip. rate.

**Comment by WenMeng-NOAA** [comment]
Note some comments from @GeoffManikin-NOAA @HuiyaChuang-NOAA and Jason Levit:
Geoff:
> Wen,      Thank you for starting a UPP issue to hopefully begin the process of removing the time-averaged GFS precip type products!!     As we discussed today, I am excited and hopeful that we won't get pushback from the field.
> 
>        I can certainly reach out directly to WPC, since they argued against removing those products last time.   (Aside to Jason:  the person at WPC who asked to retain these products has since retired.)    That said, I assume that we will have to create some sort of PNS about the proposed change to make sure that we reach all GFS stakeholders.     Jason and Huiya, do you see it this way?

Jason:
> Hi Geoff, yes, a PNS with the proposed product removal and MDC/public approval is needed before we can formally remove these products.

Huiya:

> Jason, as I've mentioned to Geoff and wen at our meeting yesterday, I tried to remove time averaged P-type
> at GFS v15 but Mike from WPC pushed back as they used this variable to compute snow liquid ratio (SLR).
> Now that WPC is turning off generating SLR in favor of EMC generating it, I am hoping they will have no
> issues with us retiring time averaged P-type.

**Comment by WenMeng-NOAA** [comment]
@HuiyaChuang-NOAA The removal of time averaged p-type from the product list of GFS atmosphere component will be implemented in HR4.

**Comment by HuiyaChuang-NOAA** [comment]
> @HuiyaChuang-NOAA The removal of time averaged p-type from the product list of GFS atmosphere component will be implemented in HR4.

Thank you @WenMeng-NOAA that sounds good.  I do have this removal documented in my google doc:
https://docs.google.com/document/d/15OwstwqQ25A3Id9xZjwt31PRhu2dzKQd-DKWR5WZFBA/edit
