### ISSUE TITLE
Add / fix some land surface related fields in RRFS

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/UPP#739]
RRFS needs to have the following changes:

MSTAV needs to be encoded as 0 m underground instead of over deeper layer (to be consistent with HRRR).
RRFS needs SOILL output in addition to SOILW and TSOIL (on 9 soil levels).
RRFS needs LAI, SOILM, and WILT output added.

Identifying these changes came out of a meeting between GSL and EMC on 14 June 2023 (led by Andrew Benjamin).

**Comment by WenMeng-NOAA** [comment]
> MSTAV needs to be encoded as 0 m underground instead of over deeper layer (to be consistent with HRRR).
It appears to me that labeling MSTAV in ops. nam and rap/hrrr are not consistent.
```
ops. nam v4.2:
wen.meng@dlogin02 nam.20230707$ pwd
/lfs/h1/ops/prod/com/nam/v4.2/nam.20230707
wen.meng@dlogin02 nam.20230707$ wgrib2 nam.t18z.bgdawp00.tm05 -match MSTAV
874:322907289:d=2023070713:MSTAV:0-1 m below ground:anl:

ops. rap v5.1"
wen.meng@dlogin01 rap.20230707$ pwd
/lfs/h1/ops/prod/com/rap/v5.1/rap.20230707
wen.meng@dlogin01 rap.20230707$ wgrib2 rap.t16z.wrfprsf02.grib2 -match MSTAV
647:175538498:d=2023070716:MSTAV:0 m underground:2 hour fcst:

ops. hrrr v4.1:
wen.meng@dlogin05 conus$ pwd
/lfs/h1/ops/prod/com/hrrr/v4.1/hrrr.20230707/conus
wen.meng@dlogin05 conus$ wgrib2 hrrr.t05z.wrfnatf16.grib2 -match MSTAV
1036:690179899:d=2023070705:MSTAV:0 m underground:16 hour fcst:
```
Should we get clarification of this soil moisture availability in top soil layer from UFS developers?

**Comment by AndrewBenjamin-NOAA** [comment]
@WenMeng-NOAA 

I brought this up to the LSM team and @EricJames-NOAA is going to be working on changing the vertical layer from 0-1m to 0m (to match the HRRR as you pointed out)

**Comment by WenMeng-NOAA** [comment]
@AndrewBenjamin-NOAA @EricJames-NOAA I would like to get some clarifications from LSM developers if this soil moisture availability should be labeled as "0 m underground" or "0-1 m underground" for RRFS.

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA I think the labeling may be a difference between the land surface models used in HRRR/RRFS vs. NAM.  Tanya Smirnova confirmed in our meeting that the MSTAV from RUC LSM should be labeled as 0 m underground.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA I think the labeling may be a difference between the land surface models used in HRRR/RRFS vs. NAM. Tanya Smirnova confirmed in our meeting that the MSTAV from RUC LSM should be labeled as 0 m underground.

@EricJames-NOAA Thanks for clarifying. I will note the label "MSTVA:0 m underground" for RUC LSM only.
