### ISSUE TITLE
Upgrade to ip/4.1.0

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/UPP#741]
The NCEPLIBS team wants to update codes to use ip v4.1.0. This version will be in the next release of spack-stack, so if we can test with 4.1.0 in the meantime, then we can switch to spack-stack and update ip version in one hopefully swift move.

**Comment by WenMeng-NOAA** [comment]
Which platform would you like to test UPP with ip v4.1.0?

**Comment by AlexanderRichert-NOAA** [comment]
Assuming you have no preference, let's say Orion.

**Comment by WenMeng-NOAA** [comment]
Orion is fine for me.

**Comment by AlexanderRichert-NOAA** [comment]
Apart from successfully compiling, what do you consider to be a successful test?

**Comment by WenMeng-NOAA** [comment]
We have a UPP standalone testing for gtg generation. If you provide me your spack-stack location, I can test it.

**Comment by AlexanderRichert-NOAA** [comment]
Thanks- the installation can be accessed through `module use /work/noaa/nems/arichert/spack-stack-ip-4.1.0/envs/test/install/modulefiles/Core` then `module load stack-gcc stack-openmpi' or 'module load stack-intel stack-intel-oneapi-mpi'

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA I have been testing IP V4.1.0 with UPP. Building UPP executable is successful. The following modules are needed for runtime:
```
prod-util
grib_util

```
Please let me know how to load them with your spack-stack.

**Comment by AlexanderRichert-NOAA** [comment]
They're installed in 1.4.1, so once you've got the spack-stack modules loaded, you should be able to do `module load prod-util grib-util`

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA I still have an issue to load prod-util and grib-util at runtime:
```
module purge
module use /work/noaa/nems/arichert/spack-stack-ip-4.1.0/envs/test/install/modulefiles/Core
module load stack-intel/2022.0.2
module load stack-intel-oneapi-mpi/2021.5.1
module use -a /work/noaa/epic/role-epic/spack-stack/spack-stack-1.4.1/envs/unified-env/install/modulefiles/Core
module use -a /work/noaa/da/role-da/spack-stack/modulefiles
module load stack-intel/2022.0.2
module load stack-intel-oneapi-mpi/2021.5.1
module load grib-util/1.2.3
module load prod-util/1.2.2
```

**Comment by AlexanderRichert-NOAA** [comment]
Yeah on second thought I think that's not the best approach. It looks like grib-util will need to be updated to use the more recent versions of ip, so let me get back to you once I know what's going on there.

**Comment by AlexanderRichert-NOAA** [comment]
@WenMeng-NOAA I have the environment in /work/noaa/nems/arichert/spack-stack-ip-4.1.0/envs/test built with a test version of grib-util that I'm calling version 1.2.5 that's built with ip 4.1.0. Can you take another crack at the UPP tests, this time just using that test environment and not the main spack-stack? Thanks.

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA From my testing on Orion, there are no changed results of UPP gtg generation with ip v4.1.0 upgrade.

**Comment by AlexanderRichert-NOAA** [comment]
That's great news, thanks! We can put ip@4.1.0 in the next spack-stack release then.

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA So if you don't have further inquiry, can I close this issue?

**Comment by AlexanderRichert-NOAA** [comment]
Is it okay if we leave it open until ip 4.1.0 is used? Alternatively I can create a new issue in a few weeks.

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA Sure, I can leave it opened. Will the ip 4.1.0 be included in the spack-stack environment installed by EPIC on R&D platforms like Orion and Hera?

**Comment by AlexanderRichert-NOAA** [comment]
Yes exactly, it'll be in the upcoming 1.5.0 release and will be on all the HPC platforms.

**Comment by natalie-perlin** [comment]
@AlexanderRichert-NOAA  @WenMeng-NOAA - 
ip/4.1.0 is installed on Hera for the two sets of stacks, netcdf/4.7.4-based and netcdf/4.9.2-based. Please feel free to test it.

Hera intel: 
```
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/intel-2022.1.2
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/intel-2022.1.2_ncdf492
```

Hera gnu:
```
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2
/scratch1/NCEPDEV/nems/role.epic/hpc-stack/libs/gnu-9.2_ncdf492

```
Orion is still on maintenance since yesterday. I'll install the ip/4.1.0 as soon as it's back

**Comment by natalie-perlin** [comment]
Built ip/4.1.0 on Orion:
```
/work/noaa/epic/role-epic/contrib/orion/hpc-stack/intel-2022.1.2
/work/noaa/epic/role-epic/contrib/orion/hpc-stack/intel-2022.1.2_ncdf492
```

**Comment by FernandoAndrade-NOAA** [comment]
ip was upgraded to 4.3.0 with the transition to spack-stack 1.5.0 on Hera, Orion, and Hercules.
