### ISSUE TITLE
Configuring grib2 discipline/parameterCategory/parameterNumber of an output variable.

### ISSUE THREAD

**Issue by parro-it** [NOAA-EMC/UPP#754]
I need to change the discipline/parameterCategory/parameterNumber of one output variable from 0/1/13 to 0/1/12. 
Is this possible by changing some configuration of UPP? 
I didn't find any mention in the documentation, but maybe I'm missing something.

The output variable I need to customize is ACM_WEASD_ON_SURFACE
Input dataset is generated with WRF version 3.9.1.1
UPP version is 2.2

**Comment by FernandoAndrade-NOAA** [comment]
Hi @parro-it, discipline, parameter category, and numbers are adjusted in the `parm/params_grib2_tbl_new` with detailed instructions on adjusting your local UPP copy available [here](https://upp.readthedocs.io/en/latest/AddNewVariable.html). Please note that these user guide instructions are for the latest version of UPP. I do see that you are using an older version of UPP alongside WRF which unfortunately is no longer supported. Please see #614 for a bit more information as well as a link to the WRF [forum ](https://forum.mmm.ucar.edu/forums/wrf-upp.133/) where you may find support. #679 may also be useful in potentially running WRF on a newer version of UPP if that's a practical solution, I'm not sure if those versions are a requirement for your application.

-Fernando Andrade

**Comment by parro-it** [comment]
Hi @FernandoAndrade-NOAA and thank you for your quick answer.

The use of UPP is required by our civil protection agencies, but not specifically the version we use now. 

I'll try to follow the instructions you linked for 4.1 and I'll see if I can solve #755 this way, too.

@WenMeng-NOAA , I sincerely appreciated the "epic" label 😆

**Comment by FernandoAndrade-NOAA** [comment]
Thanks for your reply! I'll go ahead and close this out alongside #755 as they both pertain to WRF. I hope those links provide a potential fix.

-Fernando
