### ISSUE TITLE
change the grid step unit of measure of the output file from m to mm.

### ISSUE THREAD

**Issue by parro-it** [NOAA-EMC/UPP#755]
I need to change the unit of the grid step of the output file from m to mm. Is this possible by changing some configuration of UPP?

The output variable I need to customize is ACM_WEASD_ON_SURFACE
Input dataset is generated with WRF version 3.9.1.1
UPP version is 2.2

**Comment by FernandoAndrade-NOAA** [comment]
Closed as WRF is no longer supported. Potential solutions to utilizing UPP with WRF have been linked in the accompanying issue #754 [here](https://github.com/NOAA-EMC/UPP/issues/754#issuecomment-1662828292)

-Fernando Andrade
