### ISSUE TITLE
OPEN() iostat=29, referring to STATUS identifier issue

### ISSUE THREAD

**Issue by alexkorner** [NOAA-EMC/UPP#761]
This particular line (167): 
OPEN(unit=10,file=cfname(1:nfname),status='old',form='formatted',iostat=ios,err=100)
from Dogwood: /lfs/h1/awc/awc/noscrub/Alex.Korner/UPP/sorc/ncep_post.fd/post_gtg.fd/gtg_ReadSetupParams.F90
gives iostat error 29, which to my knowledge refers to the status identifier being incorrect. The file, cfname(1:nfname), does in fact exist in the directory, so 'old' SHOULD be used. Any idea why OPEN isn't working here?

**Comment by YaliMao-NOAA** [comment]
IOSTAT=29 always means "file not found"

Did you follow the instruction that I wrote in an email? The email title is 'Please modify your script to copy an extra parm file to your work folder', the instruction is also updated on GTG wiki page: 
https://github.com/NCAR/UPP_GTG/wiki/Integrate-GTG-into-UPP-for-different-models

**Copy the right model version of gtg.input from your_UPP_GTG_folder to work folder (GTG repo)**
