### ISSUE TITLE
GTG4 upgrade related

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/UPP#763]
For RRFS, GTG4 is an upgrade version with the following features:
1. A new interface with UPP. To be compatible with GTG4, gtg_algo() in MDLFLD needs to be updated.
2. CMakeLists is updated for new GTG4 source code files
3. A new GTG field, convectively-induced turbulence (CIT), is introduced in GTG4.
4. tke is used for RRFS
5. In MISCLN.f, synchronizing the update of the interpolation to flight levels in general UPP for RRFS GTG related fields
6. To prepare separation of WAFS from GFS, new scripts are added
> scripts/exwafs_atmos_nceppost.sh
> ush/wafs_nceppost.sh
7. Add gtg_on option to the namelist 'NAMPGB'

**Comment by WenMeng-NOAA** [comment]
@YaliMao-NOAA All changes are implemented for GFS V17 only, or other applications such as GEFS V13, RRFS?

**Comment by YaliMao-NOAA** [comment]
GFS, GEFS, and RRFS will use the same copy of GTG code, but the parm files will be different. Do I answer your question? @WenMeng-NOAA
