### ISSUE TITLE
Remove several ice products from UPP output for GFS V17

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#767]
It is decided that following ice products will be generated from the Ocean/Ice component for GFS V17:

- ICEC (ice cover or sea ice concentration)
- ICETK (ice thickness)
- ICETMP (ice temperature)

Therefore, these variables will be removed from the UPP GFS control files and related pgrb2 product list for GFS V17.

**Comment by WenMeng-NOAA** [comment]
Updates from Gwen on 09/15/2023:

>Hi all,

> I have confirmed this proposed change with Jason.  We will keep ice cover and ice thickness in GFSv17/GEFSv13 atmos pgrb2 files, and remove ice temperature and ice growth rate from GFSv17 atmos pgrb2 files.  Ice temperature and ice growth rate are not outputted in GEFSv12, and ice temperature will be outputted in GFSv17/GEFSv13 ice files.  Thanks for all your inputs and suggestions on this topic!
> 
> Gwen

**Comment by WenMeng-NOAA** [comment]
The final decision is removing the following products from GFS master file generation:

- ICETMP: ice temperature

- ICEG: ice growth rate

**Comment by WenMeng-NOAA** [comment]
@GwenChen-NOAA @HuiyaChuang-NOAA The removal of ice temperature and ice growth from the product list of GFS atmosphere component will be implemented in GFS HR4.

**Comment by GwenChen-NOAA** [comment]
Thank you, Wen!  This change has been added to
https://docs.google.com/document/d/15OwstwqQ25A3Id9xZjwt31PRhu2dzKQd-DKWR5WZFBA/edit?pli=1
