### ISSUE TITLE
Enable 15-min QPF output in RRFS

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/UPP#772]
We need to get 15-min APCP output in RRFS since it is available in HRRR.  This will require some modifications to FV3.  Currently, it sounds like FV3 can only output a precipitation bucket that is the same length as the output frequency.  But the operational RRFS will likely have 15-min output frequency for the beginning of the forecast, then 1-h output frequency later in the forecast.  We will need both 1-h and 15-min APCP output for the first part of the forecast.

**Comment by MatthewPyle-NOAA** [comment]
@EricJames-NOAA To update this issue, the plan is to utilize hourly buckets, and have a side code to generate 15 minute buckets.   But seeing some interesting time labels for the sub-hourly output in an RRFS prototype with 15 minute output - may be a workflow issue, so have posted an issue there as well.

 wgrib2 rrfs.t12z.prslev.f003.pr.grib2 -match APCP
820:737929943:d=2024040212:APCP:surface:2-3 hour acc fcst: (max 29.375)
821:738016911:d=2024040212:APCP:surface:0-3 hour acc fcst: (max 41.9375)

wgrib2 rrfs.t12z.prslev.f003-15-00.pr.grib2 -match APCP
820:59191477:d=2024040212:APCP:surface:10815--2147472656 min acc fcst: (max 626.188)
821:59199007:d=2024040212:APCP:surface:15-18 min acc fcst: (max 38.6875)

wgrib2 rrfs.t12z.prslev.f003-30-00.pr.grib2 -match APCP
820:59587233:d=2024040212:APCP:surface:10830--2147472641 min acc fcst: (max 842.375)
821:59596225:d=2024040212:APCP:surface:30-33 min acc fcst: (max 44.5)

10815 = 3 hours + 15 seconds?
10830 = 3 hours + 30 seconds?

**Comment by EricJames-NOAA** [comment]
@MatthewPyle-NOAA thanks for the update.  I recall seeing something like this in RRFS-B before.  I'll look at it, but I'm taking some time off over the next few days so may not be able to focus on it until next week.  It can be a high priority when I return from leave.
