### ISSUE TITLE
Enable output of land surface model fields (LAI, SOILM, WILT) in RRFS

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/UPP#773]
These LSM fields are output in predecessor models, so we will need them in RRFS.

**Comment by JacobCarley-NOAA** [comment]
Does anyone have an update on this?

**Comment by HuiyaChuang-NOAA** [comment]
@EricJames-NOAA 
Do you have updates on this?

**Comment by EricJames-NOAA** [comment]
@JacobCarley-NOAA @HuiyaChuang-NOAA Yes, I plan to include these fields in an upcoming PR which will also include the fields mentioned in issue #770.  There is one more model PR needed to output the fields required for issue #770: https://github.com/ufs-community/ufs-weather-model/pull/2107

**Comment by HuiyaChuang-NOAA** [comment]
> @JacobCarley-NOAA @HuiyaChuang-NOAA Yes, I plan to include these fields in an upcoming PR which will also include the fields mentioned in issue #770. There is one more model PR needed to output the fields required for issue #770: [ufs-community/ufs-weather-model#2107](https://github.com/ufs-community/ufs-weather-model/pull/2107)

@EricJames-NOAA 
Thank you very much for your updates!
