### ISSUE TITLE
Enable output of convective and non-convective precip in RRFS

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/UPP#776]
Since RRFS will likely use the GF convective parameterization, we need to enable output of resolved scale and convective precipitation, and ensure they are all working correctly.

**Comment by EricJames-NOAA** [comment]
@AndrewBenjamin-NOAA @JacobCarley-NOAA is there a requirement for us to have this in RRFS?  Obviously if we are just concerned with products in HRRR, we don't need to worry about this.  Just wondering since we now have a convective parameterization in RRFS.

**Comment by EricJames-NOAA** [comment]
Just got confirmation in the RRFS developers meeting that we don't need any additional fields for this.  We already have grid scale (non-convective) precipitation output, from which one can deduce convective precipitation.  However, in RRFS-A, grid-scale precipitation is all zero.  So there is still an issue here that needs to be addressed.  This can be assigned to me.

**Comment by ericaligo-NOAA** [comment]
I'm running with the 12-14-2023 version of ufs-weather-model and using the inline UPP, and I get non-zero values for grid-scale precip. What version of the UPP is RRFS using? Was a parameter removed from the history file or from the /parm/*xml files?

For example in my RRFS run:
853:957572518:vt=2020070818:surface:39-42 hour acc fcst:NCPCP Large-Scale Precipitation (non-convective) [kg/m^2]:
    ndata=2628551:undef=772624:mean=0.276947:min=0:max=241.188
    grid_template=0:winds(N/S):
        lat-lon grid:(2501 x 1051) units 1e-06 input WE:SN output WE:SN res 48
        lat 22.000000 to 53.500000 by 0.029999
        lon 225.000000 to 300.000000 by 0.029999 #points=2628551

851:955656085:vt=2020070818:surface:39-42 hour acc fcst:APCP Total Precipitation [kg/m^2]:
    ndata=2628551:undef=772624:mean=0.327708:min=0:max=244.625
    grid_template=0:winds(N/S):
        lat-lon grid:(2501 x 1051) units 1e-06 input WE:SN output WE:SN res 48
        lat 22.000000 to 53.500000 by 0.029999
        lon 225.000000 to 300.000000 by 0.029999 #points=2628551

Upper right animation at this link shows the convective component, upper middle, the total precip:
https://www.emc.ncep.noaa.gov/mmb/ea/tmp/REFC_CTL_EXPFACTOR/Prcp_refl/index.html

**Comment by EricJames-NOAA** [comment]
@ericaligo-NOAA thanks for sharing that.  I believe we are using a more recent version of ufs-weather-model (17 Jan 2024), and a version of UPP from last Friday.  We have the NCPCP fields in the GRIB2 files, they are just all set to zero.  

Maybe we should check if RRFS-A has the required fields in its history files.  For example, I don't see cprateb_ave in the history files for RRFS-A or RRFS-B.

**Comment by JiliDong-NOAA** [comment]
> @ericaligo-NOAA thanks for sharing that. I believe we are using a more recent version of ufs-weather-model (17 Jan 2024), and a version of UPP from last Friday. We have the NCPCP fields in the GRIB2 files, they are just all set to zero.
> 
> Maybe we should check if RRFS-A has the required fields in its history files. For example, I don't see cprateb_ave in the history files for RRFS-A or RRFS-B.

Interestingly, these two lines are commented out in diag_table of rrfs-workflow:

#"gfs_phys",  "cnvprcp_ave",   "cprat_ave",   "fv3_history2d",         "all",  .false.,  "none",  2
#"gfs_phys",  "cnvprcpb_ave",  "cpratb_ave",  "fv3_history2d",         "all",  .false.,  "none",  2

https://github.com/NOAA-EMC/rrfs-workflow/blob/dev-sci/parm/diag_table.FV3_HRRR_gf (line 137-138)

**Comment by ericaligo-NOAA** [comment]
> > @ericaligo-NOAA thanks for sharing that. I believe we are using a more recent version of ufs-weather-model (17 Jan 2024), and a version of UPP from last Friday. We have the NCPCP fields in the GRIB2 files, they are just all set to zero.
> > Maybe we should check if RRFS-A has the required fields in its history files. For example, I don't see cprateb_ave in the history files for RRFS-A or RRFS-B.
> 
> Interestingly, these two lines are commented out in diag_table of rrfs-workflow:
> 
> #"gfs_phys", "cnvprcp_ave", "cprat_ave", "fv3_history2d", "all", .false., "none", 2 #"gfs_phys", "cnvprcpb_ave", "cpratb_ave", "fv3_history2d", "all", .false., "none", 2
> 
> https://github.com/NOAA-EMC/rrfs-workflow/blob/dev-sci/parm/diag_table.FV3_HRRR_gf (line 137-138)

Ah, they shouldn't be commented out.

**Comment by EricJames-NOAA** [comment]
@WenMeng-NOAA this issue is resolved now with the above rrfs-workflow change and the latest UPP.

**Comment by WenMeng-NOAA** [comment]
@EricJames-NOAA Thanks for clarifying. I will close this issue.
