### ISSUE TITLE
Miscellaneous new outputs for RRFS

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/UPP#777]
We need to enable output of EFHL, RHPW, and TCDC on boundary layer in RRFS, to match legacy modeling systems.

**Comment by jaymes-kenyon** [comment]
> We need to enable output of EFHL, RHPW, and TCDC on boundary layer in RRFS, to match legacy modeling systems.

Based on discussion with @AndrewBenjamin-NOAA and @EricJames-NOAA, four additional fields can be added to this list:
- RH_ON_HGHST_TROP_FRZ_LVL, 
- HGT_ON_HGHST_TROP_-20C_LVL, 
- HGT_ON_EQUIL_LVL, and 
- CRITICAL_ANGLE

PR #795 adds these fields (seven total) to RRFS output
