### ISSUE TITLE
Pressure-level interpolation may produce artificial supercooled rain water

### ISSUE THREAD

**Issue by jaymes-kenyon** [NOAA-EMC/UPP#778]
When a GRIB2 pressure level is located near a melting level, the interpolated values of temperature and rain-water mixing ratio may result in supercooled rain water on the pressure level, even when the adjacent model levels do not contain supercooled rain. A simple situation in which this may occur is illustrated in the linked figure [isobaric_interpolation.pdf]. This situation has been described in correspondence with Greg Thompson and Dan Adriaansen (NCAR), who have received feedback on this issue from HRRR model users. Because supercooled rain water is a hazard to aviation, a fix may be worth considering—either for RRFS alone, or other models as well.  A draft PR #771 is available (now being tested).
(https://github.com/NOAA-EMC/UPP/files/12542447/isobaric_interpolation.pdf)

**Comment by WenMeng-NOAA** [comment]
Per @jaymes-kenyon 's question:
> Here is a draft PR intended to prevent spurious supercooled rain water from appearing on pressure levels. Testing is still ongoing, but feedback / ideas are welcome. Should this new code only be used for RRFS (i.e., if MODELNAME = FV3R ...)? Thanks!

**Comment by WenMeng-NOAA** [comment]
@yangfanglin Please see Jaymes's question above, any comments on the changes implemented for GFS?

**Comment by yangfanglin** [comment]
@WenMeng-NOAA  I agree the interpolated pressure-level supercooled rain water can be misleading.  The updates can be applied to all models.   @RuiyuSun please chime in if you want

**Comment by WenMeng-NOAA** [comment]
@yangfanglin Thanks for clarifying.
@jaymes-kenyon You may incorporate the changes for all UFS models (modelname==FV3R .or. modelname==GFS). Thanks!

**Comment by RuiyuSun** [comment]
> @WenMeng-NOAA I agree the interpolated pressure-level supercooled rain water can be misleading. The updates can be applied to all models. @RuiyuSun please chime in if you want

I agree.
