### ISSUE TITLE
Rename UFS release branch (again)

### ISSUE THREAD

**Issue by fossell** [NOAA-EMC/UPP#79]
Further discussion and decisions have been made to use EMC's version numbers for ufs branches/tags.  Need to rename release/public-v4 to release/public-v8.  I can do this after current PRs are complete #76 #77 #78 .
@climbfuji Please let me know when ready for new branch to be created.  Updates to submodule pointers will be needed as well.  No immediate rush as I will not be available to make the new branch until this evening.

**Comment by fossell** [comment]
Branch release/public-v8 has been created.  
@climbfuji @kgerheiser @DusanJovic-NOAA @mark-a-potts  - I will delete old public release branches by 4pm today unless told to keep them.  Submodule pointers should be updated to point to release/public-v8 for EMC_post repository.  Please let me know if you need more time to make the change in all necessary places.

**Comment by climbfuji** [comment]
Thanks. I quickly updated the .gitmodules file in NCEPLIBS, see here: https://github.com/NOAA-EMC/NCEPLIBS/pull/45 - I checked the code, the hash before/after is the same.

**Comment by fossell** [comment]
@climbfuji Thanks for the quick turnaround Dom!
