### ISSUE TITLE
fv3atm using current fae617b hash of upp

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/UPP#804]
I'm trying to update branches in my fv3atm fork and I keep getting a conflict : 
``modified:   parm/postxconfig-NT-gefs-aerosol.txt``

The UPP hash was updated yesterday to fae617b for UPP.

If I try to check out the UPP (this repo) locally, I get:

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'parm/postxconfig-NT-GEFS-aerosol.txt'
  'parm/postxconfig-NT-gefs-aerosol.txt'

Then I see

```
~/GitHub/UPP/parm % git status
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   postxconfig-NT-GEFS-aerosol.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

I get the lower case gefs when I checkout the fv3atm repo. But this file shows differences with the lower case gefs file from the UPP repo.

**Comment by DeniseWorthen** [comment]
I keep editing the description, apologies. What I see is that both UPP and fv3atm/upp checkout a lower-case 'gefs' file. But they are not the same.

**Comment by DeniseWorthen** [comment]
If I look at the code directly on github for UPP, I see both upper and lower case "gefs" files present in the parm directory.


<img width="284" alt="Screenshot 2023-10-18 at 9 02 06 AM" src="https://github.com/NOAA-EMC/UPP/assets/40498404/f8dc7a0c-9a8d-4ceb-a48e-49d58252acdc">

**Comment by WenMeng-NOAA** [comment]
@DeniseWorthen The files postxconfig.-NT-gefs-aerosol.txt and postxconfig.-NT-GEFS-aerosol.txt are two different UPP control files. Are there any settings of your github for handling file name case-sensitive?

**Comment by DeniseWorthen** [comment]
@WenMeng-NOAA Thanks, I think the issue is that I'm doing a lot of my github work locally and that is not allowing me to check-out both GEF and gefs. I think this an OS issue actually, but it has gotten me very confused! 

If I compare my FV3 feature branch to the current develop, I don't see any files in UPP which are not in sync. But when I 'merge develop' locally to update my FV3 feature branch, it keeps telling me that my upp is modified. I guess that is because I can't check out both the gefs and GEFS file locally so whichever one gets checked is getting compared to the wrong file.

**Comment by WenMeng-NOAA** [comment]
@DeniseWorthen We will remove the legacy file postxconfig-NT-gefs*txt to prevent this kind of issue in the future.

**Comment by WenMeng-NOAA** [comment]
The update of removing legacy file postxconfig-NT-gefs*txt was combined in the PR #800.
