### ISSUE TITLE
issue with land surface type

### ISSUE THREAD

**Issue by welewis69** [NOAA-EMC/UPP#806]
Recently, while using UPP (the latest version from the developer's branch) to simulate RRFS GOES-16 brightness temperatures, we noticed that there were scattered NaN values in the BT field (mostly along the land/sea interface). Looking a bit closer at the UPP output revealed numerous errors of the type:

 CRTM_LandSurface_IsValid(INFORMATION) : Invalid Land Surface type
 CRTM_Forward(FAILURE) : Input data check failed for profile #1

Investigating further, we noticed that in the CALRAD_WCLOUD subroutine, land surface types 15 and 17 (URBAN_CONCRETE and BROADLEAF_BRUSH) are reassigned to the INVALID_LAND category. This occurs at approximately line 250 of the subroutine where the variable model_to_crtm is populated when ivegsrc=1. I ran a test restoring the original land surface types and this eliminates the CRTM error messages as well as the NaNs.

We aren't sure why this reassignment is being done, but it does degrade the simulation of brightness temperatures and we presume it is impacting others' work as well.

**Comment by WenMeng-NOAA** [comment]
@welewis69 and @EricJames-NOAA I have noticed this invalid land type issue for a long. but there are no additional resources for debugging. I appreciate both of you working on it. Thanks!
