### ISSUE TITLE
Upate s4 modulefiles to fix failing global workflow postanal tasks on S4 when using spack-stack

### ISSUE THREAD

**Issue by souopgui** [NOAA-EMC/UPP#830]
In prep of moving to spack-stack, there is need to update s4 modulefiles.

**Comment by WenMeng-NOAA** [comment]
@souopgui I would think this issue was solved in the PR #828. Can we close it?

**Comment by FernandoAndrade-NOAA** [comment]
@souopgui, just checking in on this issue. Are the changes proposed in this issue separate from PR #828? Are there additional issues after the transition to spack stack on s4?

**Comment by souopgui** [comment]
> @souopgui, just checking in on this issue. Are the changes proposed in this issue separate from PR #828? Are there additional issues after the transition to spack stack on s4?

They are similar, each single one is enough. Any other s4 issue related to upp has been reported.

**Comment by gspetro-NOAA** [comment]
@souopgui Can this issue be closed? It seems we are now several versions of spack-stack beyond when this issue was created. Has the required S4 modulefile update occurred?

**Comment by souopgui** [comment]
Yes, let's close it.
I will re-open one when spack-stack 1.8.0 is ready on S4.
