### ISSUE TITLE
Fix CI Intel Tests

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UPP#832]
The failing Intel CI tests is because the newest version of the Intel compilers does not include `ifort`.  It has been replaced with `ifx`.  The short term fix is to use the last available version of Intel compilers that include `ifort` (2023.2.1).  See https://github.com/NOAA-EMC/GSI-utils/pull/19 for a recipe.  The longer term fix is to move to `ifx` and `icx`.

**Comment by WenMeng-NOAA** [comment]
The fix is working in my branch and will be incorporated in PR #836. @DavidHuber-NOAA and @AlexanderRichert-NOAA Thanks for your help!
