### ISSUE TITLE
Hera RT errors

### ISSUE THREAD

**Issue by FernandoAndrade-NOAA** [NOAA-EMC/UPP#834]
Several `No such file or directory` errors were observed in out.post.fv3gfs  during testing on Hera for #823. The errors occurred within ush/ncep_post.sh 404 (pgbfile), scripts/exgfs_atmos_nceppost.sh 389 (pgbfile.grib2), and ush/gfs_nceppost.sh 404 (fluxfile). 

Test results and logs are available at `/scratch2/NAGAPE/epic/Fernando.Andrade-maldonado/regression-tests/upp/823/UPP/ci/` within work and rundir directories.

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA FYI for tracking

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA Please see my updates in job cards for gfs testing run_post_fv3gfs_HERA.sh and run_post_fv3gfs_pe_test_HERA.sh at /scratch2/NCEPDEV/ovp/Wen.Meng/ncep_post/post_regression_test_new/jobs

**Comment by FernandoAndrade-NOAA** [comment]
Hi Wen, I'm seeing that the primary difference is the update to loading the grib-util to 1.3.0 from the current 1.2.4 correct?

**Comment by FernandoAndrade-NOAA** [comment]
I also see that your script contains a moduleshome/init/sh not present in the epic test suite scripts, omitting this had not caused any issues on Hera in the past, but I don't want to discount it as a potential cause.

**Comment by WenMeng-NOAA** [comment]
> Hi Wen, I'm seeing that the primary difference is the update to loading the grib-util to 1.3.0 from the current 1.2.4 correct?

That's right.

**Comment by FernandoAndrade-NOAA** [comment]
> > Hi Wen, I'm seeing that the primary difference is the update to loading the grib-util to 1.3.0 from the current 1.2.4 correct?
> 
> That's right.

I've retested with updates to the fv3gfs/fv3gfs_pe run scripts. I'm not seeing any more errors regarding this issue if you'd like to verify in `/scratch2/NAGAPE/epic/Fernando.Andrade-maldonado/regression-tests/upp/gfs-fix-jan2024/UPP/ci` I've gone ahead and updated the EPIC baseline file for gfs from this test run.

**Comment by FernandoAndrade-NOAA** [comment]
Closing as issue has been resolved, Hera GFS baselines were updated and errors are no longer present in test logs.
