### ISSUE TITLE
Warning: Extension: Unary operator following arithmetic operator

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/UPP#84]
```
[ 86%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/nceppost.dir/INITPOST_GFS_NEMS_MPIIO.f.o
/home/dusan/simple-ufs/src/post/sorc/ncep_post.fd/INITPOST_GFS_NEMS_MPIIO.f:1159:44:

 1159 |             npass = npass + nint(0.5*(jtem--j))
      |                                            1
Warning: Extension: Unary operator following arithmetic operator (use parentheses) at (1)
```

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA Thanks for catching this bug. Can you submit a change so that I can integrate into the branch develop and the branch for ufs public release?

**Comment by climbfuji** [comment]
Whoever does that please make sure to do the same for the public release branch (if applicable) ... thank you!

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA and @climbfuji I just contact with the UPP developer. The "--" is a typo. The correct one would be "npass = npass + nint(0.5*(jtem-j))". Actually this block will not be processed with FV3 output. BTW, I will create a PR and make available in branch develop and release/public-v8.

**Comment by climbfuji** [comment]
Thanks, @WenMeng-NOAA!

**Comment by DusanJovic-NOAA** [comment]
Fixed in https://github.com/NOAA-EMC/EMC_post/commit/3f8a4b888f00f4e1576fb91f5697b225f8d9434c
