### ISSUE TITLE
Compile failed on Hera/Jet with IFI

### ISSUE THREAD

**Issue by hu5970** [NOAA-EMC/UPP#842]
When compile current UPP with IFI on:

./compile_upp.sh -I

It gives the following error information:

Enabling USE_IFI in the post.

```
CMake Error at cmake/FindNetCDF.cmake:210 (message):

  Unable to properly find NetCDF.  Found static libraries at:

  /scratch1/BMC/wrfruc/mhu/rrfs/v0.7.6/rrfs-workflow/sorc/UPP/sorc/libIFI.fd/NetCDF_CXX_LIBRARY-NOTFOUND

  but could not run nc-config:

Call Stack (most recent call first):

  sorc/libIFI.fd/CMakeLists.txt:18 (find_package)





CMake Error at /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env-noavx512/install/intel/2021.5.0/cmake-3.23.1-dhmfjoa/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):

  Could NOT find NetCDF (missing: CXX) (found version "4.9.2")

Call Stack (most recent call first):

  /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env-noavx512/install/intel/2021.5.0/cmake-3.23.1-dhmfjoa/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)

  cmake/FindNetCDF.cmake:284 (find_package_handle_standard_args)

  sorc/libIFI.fd/CMakeLists.txt:18 (find_package)




```

**Comment by SamuelTrahanNOAA** [comment]
This means the current UPP libraries lack the NetCDF C++ wrappers.

**Comment by SamuelTrahanNOAA** [comment]
I checked a few NetCDF modules on wcoss2 and they all lack the C++ wrappers.

This used to build on WCOSS, right?

When was the last time someone successfully built it there?

**Comment by SamuelTrahanNOAA** [comment]
Try removing this line from `sorc/libIFI.fd/CMakeLists.txt`:

```cmake
find_package(NetCDF REQUIRED COMPONENTS CXX Fortran)
```

**Comment by SamuelTrahanNOAA** [comment]
@hu5970 confirmed to me by email that this fixes his problem

> > Please try this version and tell me if it works for you:
> >
> > https://github.com/NOAA-EMC/UPP/pull/843
> >
> > All I did was update the libIFI.fd hash to df7b97c. That is now the head of the libIFI main branch.

> Sam,
>
> It works.
>
> Thanks,
> Ming

**Comment by WenMeng-NOAA** [comment]
@hu5970 Thanks for verifying.

**Comment by WenMeng-NOAA** [comment]
The UPP build test with IFI code was successfully completed on Hera.

**Comment by WenMeng-NOAA** [comment]
The UPP RT were completed on WCOSS2 and Hera without changed results. This PR is ready for merging.
