### ISSUE TITLE
Setup SFS UPP control files

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#845]
Setup SFS UPP control files (xml and txt) based on GEFS v13 UPP control files.

**Comment by KarinaAsmar-NOAA** [comment]
SFS control files have been setup from the GEFS v13 baseline in my UPP fork. The new additions are: 

- postcntrl_sfs.xml
- postxconfig-NT-SFS.txt
- postxconfig-NT-SFS.txt entry in makefile

The standalone case in Hera produced the SFS grib2 file with the same variables and number of records as the GEFSv13 grib2.

Where can I find the rt_for_developer.sh file in Hera for the UPP regression test? I can't find the /work/noaa/epic/UPP directory.

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA 

> Where can I find the rt_for_developer.sh file in Hera for the UPP regression test? I can't find the /work/noaa/epic/UPP directory.
That's the path on Orion. You might try /scratch2/NAGAPE/epic/UPP/test_suite on Hera.

**Comment by KarinaAsmar-NOAA** [comment]
what is the best way to copy SFS data files from Hera to WCOSS2?

**Comment by WenMeng-NOAA** [comment]
> what is the best way to copy SFS data files from Hera to WCOSS2?

Scp.

**Comment by KarinaAsmar-NOAA** [comment]
> > what is the best way to copy SFS data files from Hera to WCOSS2?
> 
> Scp.

Thanks. Data transfer queues are closed on wcoss2, will try when they are back up.

**Comment by KarinaAsmar-NOAA** [comment]
Standalone test case results are in:
* **Hera**: /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone
* **WCOSS2**: /lfs/h2/emc/ptmp/karina.asmar/sfs_standalone

**Comment by KarinaAsmar-NOAA** [comment]
Hera regression tests are in /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests. 
* RT with UPP develop branch latest version: /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp
* RT with UPP fork version with SFS control files: /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp_sfs

Both regression tests show GFS differences:

![image](https://github.com/NOAA-EMC/UPP/assets/148993962/9b2a4a47-9c68-44d9-a7ab-618d4fa551b3)

**Comment by KarinaAsmar-NOAA** [comment]
WCOSS2 (Cactus) regression tests are in /lfs/h2/emc/ptmp/karina.asmar/regression_tests. Lines 141 and 144 in rt_for_developer.sh had to be edited, it seemed like an error where $workdir should be $homedir to access and copy the driver scripts.

* RT with UPP develop branch latest version: /lfs/h2/emc/ptmp/karina.asmar/regression_tests/rt_upp
* RT with UPP fork version with SFS control files: /lfs/h2/emc/ptmp/karina.asmar/regression_tests/rt_upp_sfs

Both regression tests show failed GEFS master files. Currently checking GEFS driver scripts.

![image](https://github.com/NOAA-EMC/UPP/assets/148993962/3a8631f2-02bb-49c7-9236-e460a84bb772)

**Comment by KarinaAsmar-NOAA** [comment]
In run_post_fv3gefs_WCOSS2.sh:

* What are lines 88-92 being used for? These lines seem to copy UPP/parm/optics_luts_xxxx.dat files, but I do not see those files in the UPP develop branch.

* What is "pgbfile" in line 95: export PGBOUT=pgbfile?

**Comment by WenMeng-NOAA** [comment]
> Hera regression tests are in /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests.
> 
> * RT with UPP develop branch latest version: /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp
> * RT with UPP fork version with SFS control files: /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp_sfs
> 
> Both regression tests show GFS differences:
> 
> ![image](https://private-user-images.githubusercontent.com/148993962/295908767-9b2a4a47-9c68-44d9-a7ab-618d4fa551b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODk3MzUsIm5iZiI6MTcwNDk4OTQzNSwicGF0aCI6Ii8xNDg5OTM5NjIvMjk1OTA4NzY3LTliMmE0YTQ3LTljNjgtNDRkOS1hN2FiLTYxOGQ0ZmE1NTFiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjEwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjBiNjY5MTFlNDkyNDk0NDQ3MWJjM2JjZmQ4ODQyMmNhNmUxNWI0N2M1YWU3ZDJiNGIyOTBjZjRkYmVkZGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zhbqMlsqmq-GZiSLoYWZsnLQ1m4ScGk4ezi01tBAiqA)

@FernandoAndrade-NOAA Can you check if the UPP RT baselines at EPIC side are up to date on Hera?

**Comment by FernandoAndrade-NOAA** [comment]
> > Hera regression tests are in /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests.
> > 
> > * RT with UPP develop branch latest version: /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp
> > * RT with UPP fork version with SFS control files: /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp_sfs
> > 
> > Both regression tests show GFS differences:
> > ![image](https://private-user-images.githubusercontent.com/148993962/295908767-9b2a4a47-9c68-44d9-a7ab-618d4fa551b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODk3MzUsIm5iZiI6MTcwNDk4OTQzNSwicGF0aCI6Ii8xNDg5OTM5NjIvMjk1OTA4NzY3LTliMmE0YTQ3LTljNjgtNDRkOS1hN2FiLTYxOGQ0ZmE1NTFiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjEwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjBiNjY5MTFlNDkyNDk0NDQ3MWJjM2JjZmQ4ODQyMmNhNmUxNWI0N2M1YWU3ZDJiNGIyOTBjZjRkYmVkZGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zhbqMlsqmq-GZiSLoYWZsnLQ1m4ScGk4ezi01tBAiqA)
> 
> @FernandoAndrade-NOAA Can you check if the UPP RT baselines at EPIC side are up to date on Hera?

I've replied in the email discussion as well, but I believe this is related to the correction I made from #834. I need to rerun to ensure the issue was resolved and will update the gfs baselines upon success.

**Comment by KarinaAsmar-NOAA** [comment]
> > > Hera regression tests are in /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests.
> > > 
> > > * RT with UPP develop branch latest version: /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp
> > > * RT with UPP fork version with SFS control files: /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp_sfs
> > > 
> > > Both regression tests show GFS differences:
> > > ![image](https://private-user-images.githubusercontent.com/148993962/295908767-9b2a4a47-9c68-44d9-a7ab-618d4fa551b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODk3MzUsIm5iZiI6MTcwNDk4OTQzNSwicGF0aCI6Ii8xNDg5OTM5NjIvMjk1OTA4NzY3LTliMmE0YTQ3LTljNjgtNDRkOS1hN2FiLTYxOGQ0ZmE1NTFiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjEwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjBiNjY5MTFlNDkyNDk0NDQ3MWJjM2JjZmQ4ODQyMmNhNmUxNWI0N2M1YWU3ZDJiNGIyOTBjZjRkYmVkZGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zhbqMlsqmq-GZiSLoYWZsnLQ1m4ScGk4ezi01tBAiqA)
> > 
> > 
> > @FernandoAndrade-NOAA Can you check if the UPP RT baselines at EPIC side are up to date on Hera?
> 
> I've replied in the email discussion as well, but I believe this is related to the correction I made from #834. I need to rerun to ensure the issue was resolved and will update the gfs baselines upon success.

The tests ran successfully now. The results can be found in /scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp_sfs. The steps to run the regression tests were:

* $ rundir=/scratch1/NCEPDEV/stmp2/Karina.Asmar/regression_tests/rt_upp_sfs
* $ test_v=/scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone/UPP
* $ . /sfs_standalone/UPP/ci/rt.sh -a "ovp" -r $rundir -t $test_v

**Comment by WenMeng-NOAA** [comment]
> WCOSS2 (Cactus) regression tests are in /lfs/h2/emc/ptmp/karina.asmar/regression_tests. Lines 141 and 144 in rt_for_developer.sh had to be edited, it seemed like an error where $workdir should be $homedir to access and copy the driver scripts.
> 
> * RT with UPP develop branch latest version: /lfs/h2/emc/ptmp/karina.asmar/regression_tests/rt_upp
> * RT with UPP fork version with SFS control files: /lfs/h2/emc/ptmp/karina.asmar/regression_tests/rt_upp_sfs
> 
> Both regression tests show failed GEFS master files. Currently checking GEFS driver scripts.
> 
> ![image](https://private-user-images.githubusercontent.com/148993962/295931366-3a8631f2-02bb-49c7-9236-e460a84bb772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDAxNzQsIm5iZiI6MTcwNTQ5OTg3NCwicGF0aCI6Ii8xNDg5OTM5NjIvMjk1OTMxMzY2LTNhODYzMWYyLTAyYmItNDljNy05MjM2LWU0NjBhODRiYjc3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxMzU3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Mzk0M2JmOWM1ZWJiZDBlZjhiYzc0MjcwNGFiNjhmNGVjOWI0YmM5NjZjZDNmNWUwYmUzM2Y3NjZmYzNiM2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LkJRdjlo2FZ8HkFGLSZWmlV98877VE2T5ydEUSlssvQ)

@KarinaAsmar-NOAA I will check the UPP RT configuration on WCOSS2.

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA The GEFS jobs of the UPP RT on WCOSS2 were updated.

**Comment by KarinaAsmar-NOAA** [comment]
> @KarinaAsmar-NOAA The GEFS jobs of the UPP RT on WCOSS2 were updated.

@WenMeng-NOAA The WCOSS RT results are in /lfs/h2/emc/ptmp/karina.asmar/regression_tests/rt_upp_sfs. 

**Note:** $workdir needs to be changed for $homedir in lines 140 and 143 of rt_for_developer.sh

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA Your UPP RT results look good for me. Thanks for catching bugs in rt_for_developer.sh. Updated.

**Comment by KarinaAsmar-NOAA** [comment]
@WenMeng-NOAA SFS grib2 file generated with new control files is in /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone/post_sfs_1991052100. Below are the findings for the comparison of this grib2 file, the one in /scratch2/NCEPDEV/ovp/Wen.Meng/ncep_post/sfsv1/SFS-Product, and the [SFS spreadsheet](https://docs.google.com/spreadsheets/d/1lU_ZnY5dyugq9Cs5vy6SDfSMocJjrC2ia2VX8UVkDr4/edit#gid=0).

**Notes and discrepancies**:

1. CAPE variable is listed in the SFS spreadsheet (line 48) but is not in the control files (from /scratch1/NCEPDEV/stmp2/Wen.Meng/karina/sfs_control_files) nor generated in the grib2 files.
2. SFS list shows APCPCP variable, which is not generated by SFS nor GEFS. Is this variable meant to be ACPCP?
3. The **Other Variables** section in the SFS spreadsheet counts 9 total fields (line 95). There are, however, 11, for a total of 388 variables. The grib2 files are generating 387 since CAPE is missing.

**Comment by WenMeng-NOAA** [comment]
> SFS list shows APCPCP variable, which is not generated by SFS nor GEFS. Is this variable meant to be ACPCP?
264:15945580:d=1993052100:APCP:surface:12-13 day acc fcst:
265:15987614:d=1993052100:ACPCP:surface:12-13 day acc fcst:
266:16045711:d=1993052100:NCPCP:surface:12-13 day acc fcst:
@KarinaAsmar-NOAA

**Comment by KarinaAsmar-NOAA** [comment]
> > SFS list shows APCPCP variable, which is not generated by SFS nor GEFS. Is this variable meant to be ACPCP?
> > 264:15945580:d=1993052100:APCP:surface:12-13 day acc fcst:
> > 265:15987614:d=1993052100:ACPCP:surface:12-13 day acc fcst:
> > 266:16045711:d=1993052100:NCPCP:surface:12-13 day acc fcst:
> > @KarinaAsmar-NOAA

Thanks. It looks like the edit needs to be done on the spreadsheet, since instead of ACPCP the sheet shows APCPCP.

**Comment by WenMeng-NOAA** [comment]
> @WenMeng-NOAA SFS grib2 file generated with new control files is in /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone/post_sfs_1991052100. Below are the findings for the comparison of this grib2 file, the one in /scratch2/NCEPDEV/ovp/Wen.Meng/ncep_post/sfsv1/SFS-Product, and the [SFS spreadsheet](https://docs.google.com/spreadsheets/d/1lU_ZnY5dyugq9Cs5vy6SDfSMocJjrC2ia2VX8UVkDr4/edit#gid=0).
> 
> **Notes and discrepancies**:
> 
> 1. CAPE variable is listed in the SFS spreadsheet (line 48) but is not in the control files (from /scratch1/NCEPDEV/stmp2/Wen.Meng/karina/sfs_control_files) nor generated in the grib2 files.
> 2. SFS list shows APCPCP variable, which is not generated by SFS nor GEFS. Is this variable meant to be ACPCP?
> 3. The **Other Variables** section in the SFS spreadsheet counts 9 total fields (line 95). There are, however, 11, for a total of 388 variables. The grib2 files are generating 387 since CAPE is missing.

@KarinaAsmar-NOAA Thanks for catching. All issues were done.

**Comment by KarinaAsmar-NOAA** [comment]
> > @WenMeng-NOAA SFS grib2 file generated with new control files is in /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone/post_sfs_1991052100. Below are the findings for the comparison of this grib2 file, the one in /scratch2/NCEPDEV/ovp/Wen.Meng/ncep_post/sfsv1/SFS-Product, and the [SFS spreadsheet](https://docs.google.com/spreadsheets/d/1lU_ZnY5dyugq9Cs5vy6SDfSMocJjrC2ia2VX8UVkDr4/edit#gid=0).
> > **Notes and discrepancies**:
> > 
> > 1. CAPE variable is listed in the SFS spreadsheet (line 48) but is not in the control files (from /scratch1/NCEPDEV/stmp2/Wen.Meng/karina/sfs_control_files) nor generated in the grib2 files.
> > 2. SFS list shows APCPCP variable, which is not generated by SFS nor GEFS. Is this variable meant to be ACPCP?
> > 3. The **Other Variables** section in the SFS spreadsheet counts 9 total fields (line 95). There are, however, 11, for a total of 388 variables. The grib2 files are generating 387 since CAPE is missing.
> 
> @KarinaAsmar-NOAA Thanks for catching. All issues were done.

Thanks for fixing. Updated grib2 test results with fixes are in:
**Hera:** /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone/post_sfs_1991052100
**WCOSS2:** /lfs/h2/emc/ptmp/karina.asmar/sfs_standalone/post_sfs_1991052100

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA Your tests looks good to me.
