### ISSUE TITLE
change name of documentation target

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UPP#848]
In the docs directory CMakeLists.txt file we have:

```
# Build documentation with target all.
add_custom_target(doc ALL
  ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
  COMMENT "Generating API Documentation with Doxygen" VERBATIM)

```

The problem is, this code is included as submodule by fv3atm. We are now trying to add a documentation build to fv3atm, and it is breaking because we cannot have more than one target called doc, and this is used not just by upp, but also ccpp.

So I would like to change this to:

```
# Build documentation with target all.
add_custom_target(upp_doc ALL
  ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
  COMMENT "Generating API Documentation with Doxygen" VERBATIM)

```

This will have no effect on building the documentation. That is still accomplished by doing:

```
cmake -DENABLE_DOCS=ON ..
make

```

This will allow upp to peacefully co-exist with other doxygen projects being used as submodules in the UFS.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA this was the easiest way I could think of to solve the fv3atm doxygen build problem. Comments welcome...

**Comment by AlexanderRichert-NOAA** [comment]
This looks good, I agree this is a good way to let the various repos/submodules peacefully coexist.

If I build fv3atm with -DENABLE_DOCS=ON, do the submodules' docs get automatically skipped because it's not part of the parent CMake project?

**Comment by edwardhartnett** [comment]
No cmake complains about targets of the same name, whatever options are used.

**Comment by AlexanderRichert-NOAA** [comment]
I meant to say after this fix is applied

**Comment by edwardhartnett** [comment]
Well it's not working and I don't know why...
