### ISSUE TITLE
release/public-v8: Post executable should be linked with "_4" version of g2tmpl

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/UPP#85]
Post executable should be linked with "_4" version of g2tmpl ( not "_d" ), like all other ncep libraries.

https://github.com/NOAA-EMC/EMC_post/blob/d4a38debfa57b6b515f3ff5dff99f1e68a5bab92/sorc/ncep_post.fd/CMakeLists.txt#L201

Post executable is not compiled in double precision.

**Comment by WenMeng-NOAA** [comment]
@DusanJovic-NOAA I think this issue was solved in release/public-v8, right? I might close it.

**Comment by DusanJovic-NOAA** [comment]
Yes. Fixed in https://github.com/NOAA-EMC/EMC_post/commit/ed61d7dd3b2e742d6e3657bb9e9e2fe9127ed914
