### ISSUE TITLE
RRFS:  Add radar VIL and echo top to native-level, full-domain output

### ISSUE THREAD

**Issue by jaymes-kenyon** [NOAA-EMC/UPP#857]
Developers at MIT / Lincoln Lab have requested that two 2D fields (radar VIL and echo top) be included in the RRFS full-domain, native-level GRIB2 files.  These fields will support planned development of aviation-related tools.  Some info:

(1) Looking at `fv3lam_rrfs.xml`, it looks like two VIL-related fields may already be present: **VIL_ON_ENTIRE_ATMOS** and **GSD_VIL_ON_ENTIRE_ATMOS**.  Adding **GSD_RADARVIL_ON_ENTIRE_ATMOS** would make a third field.  @EricJames-NOAA — Do you happen to have any background knowledge on the VIL-related output?  The PR from Oct 2023 (https://github.com/NOAA-EMC/UPP/pull/800/files) suggests that RADARVIL was being provided in the output, but I do not see the string "RADARVIL" in the control files from that time.  Thanks for any hints!

(2) Regarding echo top, this request may be straightforward:  **RETOP_ON_ENTIRE_ATMOS_SINGLE_LYR** is provided in the pressure-level grids, and seemingly just needs to be added to the native-level grids.

This issue can be assigned to me (@jaymes-kenyon).

**Comment by EricJames-NOAA** [comment]
@jaymes-kenyon the VIL variables are confusing.  We had some exchange with NCAR back in October; they were asking for both VIL and RADARVIL.  From examining the code, I believe I came to the conclusion that IGET number 581 (VIL_ON_ENTIRE_ATMOS) is computed identically to IGET number 770 (GSD_RADARVIL_ON_ENTIRE_ATMOS) as long as we are using Thompson microphysics.  See if you agree.  So I think we are already outputting both VIL and RADARVIL in RRFS-A, we just need to convey their names.  I need to look up which one is which, but this is what I see in RRFS-A pressure level files:

38:254701218:vt=2024011719:entire atmosphere (considered as a single layer):1 hour fcst:VIL Vertically-Integrated Liquid Water [kg/m^2]:
    ndata=14452641:undef=2178109:mean=0.0232181:min=0.00123418:max=70.7443
    grid_template=1:winds(N/S):
	rotated lat-lon grid:(4881 x 2961) units 1e-06 input WE:SN output WE:SN res 48
	lat -37.000000 to 37.000000 by 0.025000
	lon 299.000000 to 61.000000 by 0.025000 #points=14452641
	south pole lat=-35.000000 lon=247.000000 angle of rot=0.000000

41:262710253:vt=2024011719:entire atmosphere:1 hour fcst:VIL Vertically-Integrated Liquid Water [kg/m^2]:
    ndata=14452641:undef=2178109:mean=0.0826812:min=0:max=51.0426
    grid_template=1:winds(N/S):
	rotated lat-lon grid:(4881 x 2961) units 1e-06 input WE:SN output WE:SN res 48
	lat -37.000000 to 37.000000 by 0.025000
	lon 299.000000 to 61.000000 by 0.025000 #points=14452641
	south pole lat=-35.000000 lon=247.000000 angle of rot=0.000000

So I think we just need to get these VIL fields and the echo top added to the native level grids.

**Comment by WenMeng-NOAA** [comment]
In RRFS control file 'postxconfig-NT-fv3lam_rrfs.txt':
```
581
VIL_ON_ENTIRE_ATMOS
entire atmosphere Vertically Integrated Liquid (kg/m-2)
1
tmpl4_0
VIL
....
...
769
GSD_VIL_ON_ENTIRE_ATMOS
?
1
tmpl4_0
VIL
?
?
entire_atmos

```
It seems to me that RADARVIL (ID 770) is not included.
