### ISSUE TITLE
Add additional isobaric levels for SFS products

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#885]
SFS developer from EMC requests adding additional isobaric levels up to 0.01 mb in the SFS products for their model evaluation.

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA Please add the following 8 isobaric levels in all isobaric level variables:
1, 2, 4, 7, 10, 20, 40, 70

**Comment by KarinaAsmar-NOAA** [comment]
> @KarinaAsmar-NOAA Please add the following 8 isobaric levels in all isobaric level variables: 1, 2, 4, 7, 10, 20, 40, 70

@WenMeng-NOAA The SFS standalone and regression test results with the added isobaric levels are in the paths below:

**Hera:**
standalone: /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone
regression: /scratch1/NCEPDEV/stmp2/Karina.Asmar/rt_sfs

**WCOSS2:**
standalone: /lfs/h2/emc/ptmp/karina.asmar/sfs_standalone
regression: /lfs/h2/emc/ptmp/karina.asmar/rt_sfs

**Comment by KarinaAsmar-NOAA** [comment]
> > @KarinaAsmar-NOAA Please add the following 8 isobaric levels in all isobaric level variables: 1, 2, 4, 7, 10, 20, 40, 70
> 
> @WenMeng-NOAA The SFS standalone and regression test results with the added isobaric levels are in the paths below:
> 
> **Hera:** standalone: /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone regression: /scratch1/NCEPDEV/stmp2/Karina.Asmar/rt_sfs
> 
> **WCOSS2:** standalone: /lfs/h2/emc/ptmp/karina.asmar/sfs_standalone regression: /lfs/h2/emc/ptmp/karina.asmar/rt_sfs

@WenMeng-NOAA I reran the tests with the latest UPP commit (Update grib2 table files with the new release g2tmpl) and the Hera regression tests are not generating bit-identical grib2 files.

**Comment by KarinaAsmar-NOAA** [comment]
> > > @KarinaAsmar-NOAA Please add the following 8 isobaric levels in all isobaric level variables: 1, 2, 4, 7, 10, 20, 40, 70
> > 
> > 
> > @WenMeng-NOAA The SFS standalone and regression test results with the added isobaric levels are in the paths below:
> > **Hera:** standalone: /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone regression: /scratch1/NCEPDEV/stmp2/Karina.Asmar/rt_sfs
> > **WCOSS2:** standalone: /lfs/h2/emc/ptmp/karina.asmar/sfs_standalone regression: /lfs/h2/emc/ptmp/karina.asmar/rt_sfs
> 
> @WenMeng-NOAA I reran the tests with the latest UPP commit (Update grib2 table files with the new release g2tmpl) and the Hera regression tests are not generating bit-identical grib2 files.

@WenMeng-NOAA The latest regression tests are available in the paths listed above, all tests now pass.
