### ISSUE TITLE
Compile with Rocky 8 OS

### ISSUE THREAD

**Issue by hu5970** [NOAA-EMC/UPP#889]
The hera, jet, and orion HPC clusters are transitioning to the Rocky O.S.
Need to use spack-stack for Rocky 8 to compile the UPP. 

Please see this issue from ufs-srweather-model:
https://github.com/ufs-community/ufs-weather-model/issues/2167

Tested "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/modulefiles/Core"
The compilation works smoothly.

**Comment by WenMeng-NOAA** [comment]
@hu5970 Thanks for sharing Rocky8 OS transition tips. We will work on that.

**Comment by WenMeng-NOAA** [comment]
@hu5970 The UPP was just updated for Rocky8 transition on Hera and jet.
