### ISSUE TITLE
Add new SFS products for CPC

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#900]
Per CPC's request, the following fields are added in the SFS product list:

- 0-3000m helicity
- total sky downward direct radiation at surface
- subsurface runoff

**Comment by KarinaAsmar-NOAA** [comment]
@WenMeng-NOAA Would you please provide the UPP ID for "total sky downward direct radiation at surface"? Also, please confirm if "subsurface runoff" refers to UPP ID 122 (SSRUN - Storm Surface Runoff).

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA use:

- VBDSF 772 for total sky downward direct radiation at surface
- SSRUN 122 for surface (storm) runoff

**Comment by KarinaAsmar-NOAA** [comment]
@WenMeng-NOAA should I use "module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/modulefiles/Core" for loading modules to run UPP in Hera and then load the modules from upp_common.lua? If so, the system cannot find the libraries. Is there a rocky8 example in Hera for running UPP I can look at?

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA The UPP develop was recently updated with the spack-stack installed for rocky8. You should login to one of hfe09-12 nodes. Further updates on Hera are ongoing.

**Comment by KarinaAsmar-NOAA** [comment]
> @KarinaAsmar-NOAA The UPP develop was recently updated with the spack-stack installed for rocky8. You should login to one of hfe09-12 nodes. Further updates on Hera are ongoing.

@WenMeng-NOAA I tried running a test in the hfe10 node, using the rocky8 module path specified in hera.lua in UPP develop, but the module libraries are not being found. I am also unable to execute the wgrib2 module outside of the UPP test. Is this due to the ongoing Hera updates or are there further changes that need to be made in how we load modules in the system for running UPP?

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA Regarding to CPC's clarification on Total sky downward direct radiation at the surface as below:

> “Total sky downward direct radiation at the surface” which is the total solar radiation that reaches the surface without being scattered, and accumulated over a particular time period. I am not sure if this parameter is available in the current CFS data.

After coordinating with one of model developers, I would suggest you make changes in your PR:

- Remove all change for VBDSF (UPP ID 772)
- Add two variables, VBDSF (UPP ID 401), NBDSF (UPP ID 403)

**Comment by KarinaAsmar-NOAA** [comment]
> @KarinaAsmar-NOAA Regarding to CPC's clarification on Total sky downward direct radiation at the surface as below:
> 
> > “Total sky downward direct radiation at the surface” which is the total solar radiation that reaches the surface without being scattered, and accumulated over a particular time period. I am not sure if this parameter is available in the current CFS data.
> 
> After coordinating with one of model developers, I would suggest you make changes in your PR:
> 
> * Remove all change for VBDSF (UPP ID 772)
> * Add two variables, VBDSF (UPP ID 401), NBDSF (UPP ID 403)

@WenMeng-NOAA Test results with IDs 401 and 403 and ID 772 removed are in the Hera /scratch1/NCEPDEV/stmp2/Karina.Asmar/sfs_standalone/post_sfs_1991052100 and WCOSS2 /lfs/h2/emc/ptmp/karina.asmar/sfs_standalone/post_sfs_1991052100

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA Your test looks good to me.
