### ISSUE TITLE
The detect_machine.sh script needs to be updated

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UPP#901]
With the most recent upgrade of Hera on 3/19, two-thirds of the head nodes are now upgraded to Rocky8.  The detect_machine.sh script needs to be updated so that head nodes hfe05-hfe08 are labeled as `hera` instead of `hera_c`.

**Comment by HenryRWinterbottom** [comment]
@DavidHuber-NOAA Thank you. I will address this issue ASAP.

**Comment by FernandoAndrade-NOAA** [comment]
Updates to detect_machine's Hera section for hfe05-08 are included within my #896

**Comment by DavidHuber-NOAA** [comment]
Great, thanks @FernandoAndrade-NOAA!
