### ISSUE TITLE
Improve organization of application specific configuration files in the UPP repository.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/UPP#921]
Presently, all application configuration files or `parm` files reside under [parm/](https://github.com/NOAA-EMC/UPP/tree/develop/parm).  There are mixed conventions used in identifying the applications and their associated sub-cycles; UPPERCASE, lowercase; e.g. GFS, gfs, GEFS, gefs.  In some instances `aerosol` is used while in some other cases `chem`.  These are just some examples.  They are not exhaustive and are simply used to illustrate the point.

A proposal here is to create subdirectories under parm based on the `modelname` (gfs, gefs, rrfs, hafs, etc.) so that it makes it easier to locate, identify, and manage the versions of the various configuration files for these and upcoming applications.

**Comment by WenMeng-NOAA** [comment]
The updates will be completed in PR #990.
