### ISSUE TITLE
Write out HGT for hydrostatic run and omega from the model output

### ISSUE THREAD

**Issue by XiaqiongZhou-NOAA** [NOAA-EMC/UPP#946]
HGT and omega are not written out correctly in UPP for hydrostatic runs.
This issue should be fixed in offline UPP as the upcoming [update](https://github.com/XiaqiongZhou-NOAA/fv3atm/compare/da95cc428d8b626e99250fd57a4279b4980044f8...4bbb4e3f1a7bfaa7c041ef9d2415bf3c0bdef0d6#diff-44bb5bc1204d2d645d5b7152243b1a3558e1f8aef18118a02256f2bbd798b956) for inline post and the corresponding ufs-weather-model PR#[2255](https://github.com/ufs-community/ufs-weather-model/pull/2255).
This fix can also process omega in post when omega is written out by the model.

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA The changes in the inline post interface (io/post_fvs.F90) from @XiaqiongZhou-NOAA 's UFS PR #[2255](https://github.com/XiaqiongZhou-NOAA/fv3atm/compare/da95cc428d8b626e99250fd57a4279b4980044f8...4bbb4e3f1a7bfaa7c041ef9d2415bf3c0bdef0d6#diff-44bb5bc1204d2d645d5b7152243b1a3558e1f8aef18118a02256f2bbd798b956) needs to be synced in the offline post interface (INITPOST_NETCDF.f) in UPP.

**Comment by KarinaAsmar-NOAA** [comment]
@XiaqiongZhou-NOAA Would you please provide the model outputs that include the new omega changes in order to test the offline results against the inline?

**Comment by XiaqiongZhou-NOAA** [comment]
> @XiaqiongZhou-NOAA Would you please provide the model outputs that include the new omega changes in order to test the offline results against the inline?
Here are the model output example and grib2 files generated with inline post on Hera:
/scratch2/NCEPDEV/ensemble/Xiaqiong.Zhou/noscrub/hydro_sample

**Comment by KarinaAsmar-NOAA** [comment]
> > @XiaqiongZhou-NOAA Would you please provide the model outputs that include the new omega changes in order to test the offline results against the inline?
> > Here are the model output example and grib2 files generated with inline post on Hera:
> > /scratch2/NCEPDEV/ensemble/Xiaqiong.Zhou/noscrub/hydro_sample

Thanks!

**Comment by KarinaAsmar-NOAA** [comment]
@XiaqiongZhou-NOAA Do you happen to have the netCDF and grib2 samples for this test in WCOSS2?

**Comment by KarinaAsmar-NOAA** [comment]
@XiaqiongZhou-NOAA For your inline post run on the sample data you provided, is the modelname 'FV3R'? And which control files were you using? It's so I can replicate the run with offline post.

**Comment by KarinaAsmar-NOAA** [comment]
@WenMeng-NOAA What are the control files and modelname used to run GFSv17 in UPP? Is it postcntrl_gfs_flux.xml and 'GFS'?

**Comment by KarinaAsmar-NOAA** [comment]
Tests were run with and without hydrostatic fix in offline post with GFSv17, GEFSv13, SFSv1. PPT slides are attached 
[UPP Hydrostatic Fix Plots.pptx](https://github.com/NOAA-EMC/UPP/files/15309201/UPP.Hydrostatic.Fix.Plots.pptx)
. GRIB2 files are in Hera /scratch1/NCEPDEV/stmp2/Karina.Asmar/hydro.

**Comment by XiaqiongZhou-NOAA** [comment]
> Tests were run with and without hydrostatic fix in offline post with GFSv17, GEFSv13, SFSv1. PPT slides are attached [UPP Hydrostatic Fix Plots.pptx](https://github.com/NOAA-EMC/UPP/files/15309201/UPP.Hydrostatic.Fix.Plots.pptx) . GRIB2 files are in Hera /scratch1/NCEPDEV/stmp2/Karina.Asmar/hydro.

The results look good. A question: Why HGT at hybrid level is missing in offline post without fix? I think it should be calculated from delz if it is as same as in online post.

**Comment by KarinaAsmar-NOAA** [comment]
> > Tests were run with and without hydrostatic fix in offline post with GFSv17, GEFSv13, SFSv1. PPT slides are attached [UPP Hydrostatic Fix Plots.pptx](https://github.com/NOAA-EMC/UPP/files/15309201/UPP.Hydrostatic.Fix.Plots.pptx) . GRIB2 files are in Hera /scratch1/NCEPDEV/stmp2/Karina.Asmar/hydro.
> 
> The results look good. A question: Why HGT at hybrid level is missing in offline post without fix? I think it should be calculated from delz if it is as same as in online post.

HGT at hybrid level is missing when running offline post without the fix because though it is calculated from delz, delz is not found in the netCDF files (the ones provided for this test in hydro_sample). The calculation is shown [here](https://github.com/KarinaAsmar-NOAA/UPP/blob/1916cb2acb5f52f04e72b9965358f0eb1c6da208/sorc/ncep_post.fd/INITPOST_NETCDF.f#L1183), where buf3d contains the delz value from the model output (not found in this case). From there it goes down to setting all [zmid values to spval](https://github.com/KarinaAsmar-NOAA/UPP/blob/1916cb2acb5f52f04e72b9965358f0eb1c6da208/sorc/ncep_post.fd/INITPOST_NETCDF.f#L1216)

**Comment by XiaqiongZhou-NOAA** [comment]
I see. I misunderstood that your data are from GFSv17.
