### ISSUE TITLE
The Read the Docs documentation of namelist entries is bare.

### ISSUE THREAD

**Issue by christinaholtNOAA** [NOAA-EMC/UPP#949]
The current [documentation for namelist entries](https://upp.readthedocs.io/en/latest/InputsOutputs.html#itag) only describes one entry under the `nampbg` section. Upon digging into the UPP source code, almost 2 dozen entries are accepted. More thorough documentation of these entries is necessary, including defaults, types, and descriptions, which are not easy to find in the code.

The style and content of the [ufw-weather-model namelist documentation](https://ufs-weather-model.readthedocs.io/en/develop/InputsOutputs.html#namelist-file-input-nml) seems sufficient for updating the UPP docs.

**Comment by FernandoAndrade-NOAA** [comment]
Fixed with the merge of #940.
