### ISSUE TITLE
Ensemble member information missing in aerosol fields

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#950]
@bingfu-NOAA reported that ensemble member information regarding aerosol variables is missing in his initial effort to configure aerosols  in every member for GEFS v13 development as:
```
123:65787856:d=2018010400:PMTF:surface:114 hour fcst:aerosol=Dust Dry:aerosol_size <2.5e-06:
124:66271887:d=2018010400:PMTC:surface:114 hour fcst:aerosol=Dust Dry:aerosol_size <1e-05:
125:66697804:d=2018010400:PMTF:surface:114 hour fcst:aerosol=Sea Salt Dry:aerosol_size <2.5e-06:
126:67687796:d=2018010400:PMTC:surface:114 hour fcst:aerosol=Total Aerosol:aerosol_size <1e-05:
127:68548175:d=2018010400:PMTF:surface:114 hour fcst:aerosol=Total Aerosol:aerosol_size <2.5e-06:
128:69453791:d=2018010400:CAPE:180-0 mb above ground:114 hour fcst:ENS=+5
129:69893859:d=2018010400:CIN:180-0 mb above ground:114 hour fcst:ENS=+5
130:70386470:d=2018010400:ICEC:surface:114 hour fcst:ENS=+5
131:70396013:d=2018010400:PVORT:450 K isentropic level:114 hour fcst:ENS=+5
132:71038425:d=2018010400:PVORT:550 K isentropic level:114 hour fcst:ENS=+5
133:71771703:d=2018010400:PVORT:650 K isentropic level:114 hour fcst:ENS=+5
```

**Comment by WenMeng-NOAA** [comment]
The UPP has no capability to encode ensemble member information for aerosol fields in GRIB2. To approach that, the first step is adding [temp 4.49](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-49.shtml) in g2tmpl source at the [g2tmpl repository](https://github.com/NOAA-EMC/NCEPLIBS-g2tmpl).

**Comment by WenMeng-NOAA** [comment]
@bingfu-NOAA @lipan-NOAA and I worked on the workarounds, now the UPP can generate aerosol fields including ensemble information as:
```
442:359461071:d=2018081600:PMTF:surface:18 hour fcst:ENS=+7:aerosol=Dust dry 
443:360026218:d=2018081600:PMTC:surface:18 hour fcst:ENS=+7:aerosol=Dust dry
444:360534870:d=2018081600:PMTF:surface:18 hour fcst:ENS=+7:aerosol=Sea salt dry
445:361774978:d=2018081600:PMTC:surface:18 hour fcst:ENS=+7:aerosol=Total aerosol
446:362584961:d=2018081600:PMTF:surface:18 hour fcst:ENS=+7:aerosol=Total aerosol
```

**Comment by WenMeng-NOAA** [comment]
The sample new grib2 data file GFSPRS.GrbF18 is at /u/wen.meng/noscrub/ncep_post/g2tmpl/g2tmpl_pan/post_gefs_2018081600 on dogwood. The wgrib2 v3.1.3 should be used to dump this grib2 file.

**Comment by WenMeng-NOAA** [comment]
By 07/08/2024,

- g2 repository was committed the updates for template 4.49. The tag g2 v3.5.1 was released by the NCEPLIB team.
- g2tmpl repository was committed the updates for template 4.49. The tag g2tmpl v1.13.0 was released by the NCEPLIB team.
- Wen submitted the request to install g2/3.5.1 and g2tmpl/1.13.0 on R&D platforms and WCOSS2 to the [spack-stack](https://github.com/JCSDA/spack-stack/issues/1180) repository.
- With @AndrewBenjamin-NOAA returning to work, he will follow up the status of library installation from the VPB perspective.

**Comment by WenMeng-NOAA** [comment]
@bingfu-NOAA This issue was solved in the UPP develop branch with @lipan-NOAA 's PR #1011. May I close it as completed?

**Comment by bingfu-NOAA** [comment]
@WenMeng-NOAA Sure, thanks.
