### ISSUE TITLE
Bug in prob values denoted in QPFARI and QPFFFG fields in RRFS

### ISSUE THREAD

**Issue by EricJames-NOAA** [NOAA-EMC/UPP#962]
The prob values showing up for QPFARI and QPFFFG fields in RRFS are not reproducible.  Subsequent runs lead to different values as shown here:

< 772:4824832913:vt=2024022023:surface:11-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat
=1 parm=197:prob >1:prob fcst 72/110
---
> 772:4824832913:vt=2024022023:surface:11-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat
=1 parm=197:prob >1:prob fcst 96/110
6177c6177
< 773:4824833141:vt=2024022023:surface:0-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat=
1 parm=197:prob >1:prob fcst 72/110
---
> 773:4824833141:vt=2024022023:surface:0-12 hour acc fcst:var discipline=1 center=7 local_table=1 parmcat=
1 parm=197:prob >1:prob fcst 96/110

**Comment by WenMeng-NOAA** [comment]
This issue was solved in the PR #968.
