### ISSUE TITLE
extraneous GSD_ in number concentration variable names

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [NOAA-EMC/UPP#972]
The number concentration variables begin with "GSD_" which implies they're model-specific:

- GSD_NCRAIN_ON_HYBRID_LVL
- GSD_NCCD_ON_HYBRID_LVL
- GSD_NCIP_ON_HYBRID_LVL

They're simply the number concentration. Nothing to do with GSD.

~~I suggest we add synonym variables (ie. NCRAIN_ON_HYBRID_LEVEL) and deprecate the GSD_ versions.~~

@WenMeng-NOAA's preference is to rename the variables and *not* add synonyms. This will require updating model workflows to use new *.txt files with the correct names.

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA You might update UPP IDs 747,752,754 with

- NCRAIN_ON_HYBRID_LVL
- NCCD_ON_HYBRID_LVL
- NCIP_ON_HYBRID_LVL

**Comment by SamuelTrahanNOAA** [comment]
> You might update UPP IDs 747,752,754 with

Is there any way that could break existing model workflows?

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA No, the RRFS workflow has been using the branch 'release/rrfs_v1' aiming RRFS v1 implementation. Your PR will merged to the 'develop' branch for future implementations.

**Comment by SamuelTrahanNOAA** [comment]
Okay. I'll update my branch to do what you suggest (merely rename the variables). Presently, I'm arguing with the inline post, trying to get it to run with the latest UPP. Your suggestion will be in the next round of testing.

**Comment by WenMeng-NOAA** [comment]
> Okay. I'll update my branch to do what you suggest (merely rename the variables). Presently, I'm arguing with the inline post, trying to get it to run with the latest UPP. Your suggestion will be in the next round of testing.

@SamuelTrahanNOAA There might be more efforts to get inline post working at UFS side with the latest UPP, e.g. g2tmpl, inline post interface. Let's get your changes working in offline post first. Thanks!

**Comment by SamuelTrahanNOAA** [comment]
My changes already work in the offline post, and I have a fix for the inline post. I expect to have it working shortly, probably today.

**Comment by jaymes-kenyon** [comment]
@SamuelTrahanNOAA — Just wanted to say thanks for removing the unnecessary "GSD_" prefixes from the number-concentration shortnames.  My PR in Aug 2023 (https://github.com/NOAA-EMC/UPP/pull/758/) added the number concentrations to RRFS output, but I did not seize the opportunity to drop the "GSD_" designations.  Simplified code is always welcomed—thanks again!
