### ISSUE TITLE
number concentration on pressure levels

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [NOAA-EMC/UPP#973]
The Water in the West project would like to output number concentration on pressure levels. Presently, the UPP can only output that on hybrid levels.

**Comment by WenMeng-NOAA** [comment]
@SamuelTrahanNOAA Will the new changes be applied for HAFS v3 implementation?

**Comment by SamuelTrahanNOAA** [comment]
> Will the new changes be applied for HAFS v3 implementation?

Not that I know of.
