### ISSUE TITLE
Update Orion module file to point to Rocky-9 environment

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UPP#983]
Orion was updated to the Rocky-9 OS and spack-stack has been installed in `/work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/unified-env-rocky9`.  The module file should be updated.  Ideally, this would go in with https://github.com/ufs-community/ufs-weather-model/pull/2336.

Lastly, there is an issue with one of the spack-stack CRTM fix files in the new installation.  https://github.com/JCSDA/spack-stack/issues/1158 is open to track that and have it corrected, though I don't think it will have a direct impact on the UPP.

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA and @FernandoAndrade-NOAA Could either of you work on this update? Thanks!

**Comment by DavidHuber-NOAA** [comment]
@FernandoAndrade-NOAA @WenMeng-NOAA I can update the module file and test build if someone else can run the RTs.

**Comment by WenMeng-NOAA** [comment]
@DavidHuber-NOAA Thanks! @FernandoAndrade-NOAA maintains the UPP RTs on Orion. 
I opened the spack-stack issue #[1164](https://github.com/JCSDA/spack-stack/issues/1164) to install g2tmpl/1.12.0 for Rocky9, please follow up it.
