### ISSUE TITLE
Add temporal max wind at 10-meter as SFS product

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/UPP#986]
CPC requests temporal max wind at 10-meter as SFS product.

**Comment by KarinaAsmar-NOAA** [comment]
@WenMeng-NOAA Is this the same max wind output as in RRFS? I see in [rrfs_postcntrl.xml](https://github.com/KarinaAsmar-NOAA/UPP/blob/70fc7625efef6055ca038fcfcdc648353214845b/parm/rrfs_postcntrl.xml#L2108) the max u,v wind components at 10m (ids 506 and 507 in [UPP GRIB2 Table](https://upp.readthedocs.io/en/latest/UPP_GRIB2_Table_byID.html).

**Comment by KarinaAsmar-NOAA** [comment]
@JesseMeng-NOAA CPC has requested the [10m temporal max wind](https://github.com/NOAA-EMC/UPP/issues/887#issuecomment-2231680918) to be added to SFS products list. The EMC developer team will be adding the feature to the model so that it can be read by UPP. UPP currently has a similar capability for [RRFS](https://github.com/NOAA-EMC/UPP/blob/47358ed86d8127168ba9266abb87950567aabe07/parm/rrfs_postcntrl.xml#L1545), with id 422.  Can this UPP ID along with its source variable name 'spd10max' in [INITPOST_NETCDF.f](https://github.com/NOAA-EMC/UPP/blob/47358ed86d8127168ba9266abb87950567aabe07/sorc/ncep_post.fd/INITPOST_NETCDF.f#L2002) be used for this SFS application?

**Comment by HuiyaChuang-NOAA** [comment]
> @JesseMeng-NOAA CPC has requested the [10m temporal max wind](https://github.com/NOAA-EMC/UPP/issues/887#issuecomment-2231680918) to be added to SFS products list. The EMC developer team will be adding the feature to the model so that it can be read by UPP. UPP currently has a similar capability for [RRFS](https://github.com/NOAA-EMC/UPP/blob/47358ed86d8127168ba9266abb87950567aabe07/parm/rrfs_postcntrl.xml#L1545), with id 422. Can this UPP ID along with its source variable name 'spd10max' in [INITPOST_NETCDF.f](https://github.com/NOAA-EMC/UPP/blob/47358ed86d8127168ba9266abb87950567aabe07/sorc/ncep_post.fd/INITPOST_NETCDF.f#L2002) be used for this SFS application?

Yes I believe so but model needs to add this variables to the output first for UPP to read in.
@wzzheng90 @yangfanglin  CPC confirmed at SFS meeting today, they are looking for maximum 10 m wind speed over a certain time
period.  I think we can just output maximum  10 m wind speed over our GFS/SFS bucket of 6 hours and then CPC can find 
12 hr and 24 hr max from our 6 hourlu max.

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA Please provide @wzzheng90 the variable name of maximum 10-m wind speed in the model history files so he can look into it the model code.

**Comment by KarinaAsmar-NOAA** [comment]
@wzzheng90 The variable name for the max 10m wind speed that UPP is currently reading is **'spd10max'**, see code [here](https://github.com/KarinaAsmar-NOAA/UPP/blob/47358ed86d8127168ba9266abb87950567aabe07/sorc/ncep_post.fd/INITPOST_NETCDF.f#L2002)

**Comment by wzzheng90** [comment]
@KarinaAsmar-NOAA  Yes, the model history files include hourly maximum wind speed  'spd10max'.

**Comment by KarinaAsmar-NOAA** [comment]
> @KarinaAsmar-NOAA Yes, the model history files include hourly maximum wind speed 'spd10max'.

@wzzheng90 Thanks. Is it possible for the model to produce 6-hr max or longer wind speed using the 'spd10max' variable name?

**Comment by wzzheng90** [comment]
Need to modify the code in the model, I think.

**Comment by KarinaAsmar-NOAA** [comment]
> Need to modify the code in the model, I think.

Thanks. If you can output 'spd10max' at 6-hour intervals from the model, we should be able to test it with UPP.

**Comment by wzzheng90** [comment]
@KarinaAsmar-NOAA  It is just hard-wired for hourly maximum wind speed 'spd10max' in the model.  If you need 'spd10max' at 6-hour intervals, you'd better to contact the model management to decide what the best solution is about this issue.

**Comment by KarinaAsmar-NOAA** [comment]
> @KarinaAsmar-NOAA It is just hard-wired for hourly maximum wind speed 'spd10max' in the model. If you need 'spd10max' at 6-hour intervals, you'd better to contact the model management to decide what the best solution is about this issue.

Thanks. 

@yangfanglin @HuiyaChuang-NOAA @WenMeng-NOAA Would you please advise on the best path forward? It seems the SFS model is hard-wired for hourly outputs of max wind speed. For CPC use, we would need at least 6-hour.

**Comment by yangfanglin** [comment]
the current hourly spd10max needs to be kept to support regional model application.   A new variable needs to be added in the UFS model and UPP to produce and record max wind speed at a 6-hour interval.

@wzzheng90 please proceed forward to add the latter to the ufs_weather_model code, using a different name, for instance, spd10max6hr

**Comment by wzzheng90** [comment]
@yangfanglin and all:  It seems that adding 'spd10max' at 6-hour intervals is not trivial in the ufs_weather_model code.  For the current hourly spd10max, please see:  "maximum_hourly_diagnostics.F90" and "maximum_hourly_diagnostics.meta" (https://github.com/ufs-community/ccpp-physics/blob/2a50cccd916cceafaf031f4cd14f2ecef277be8f/physics/Interstitials/UFS_SCM_NEPTUNE/maximum_hourly_diagnostics.F90).
So,do you know who manages this kind of code in the ufs_weather_model, so that I can contact him/her to discuss about this issue?

At the same time, is it possible to derive 'spd10max' at 6-hour intervals (spd10max6hr) from the current hourly spd10max in the UPP?
Any further suggestions?  Thanks!

**Comment by WenMeng-NOAA** [comment]
The UPP has no capability to save instant/hourly variables to calculate time averaged/accumulated variables. @wzzheng90 @yangfanglin

**Comment by HuiyaChuang-NOAA** [comment]
Echoing what Wen said, UPP does not read from multiple forecasts.

**Comment by yangfanglin** [comment]
@wzzheng90  can you follow in the ufs-weatehr-model code how T2m_max and T2m_min etc are computed to set up spd10max6hr ?

**Comment by wzzheng90** [comment]
@yangfanglin   Just check them.  Similar to T2m_max or T2m_min,  the ufs-weatehr-model code also outputs the maximum wind speed "'wind10mmax".  So, can the UPP read this "wind10mmax"?

**Comment by HuiyaChuang-NOAA** [comment]
> @yangfanglin Just check them. Similar to T2m_max or T2m_min, the ufs-weatehr-model code also outputs the maximum wind speed "'wind10mmax". So, can the UPP read this "wind10mmax"?

Is this wind speed max over 6 hour bucket?  Yes, UPP can be updated to read any variables from model.

**Comment by wzzheng90** [comment]
@HuiyaChuang-NOAA  yes. should be the same way as T2m_max or T2m_min.

**Comment by WenMeng-NOAA** [comment]
@wzzheng90 Thanks for working on this. Could you generate one cycle of model history files for the UPP testing?

**Comment by wzzheng90** [comment]
@WenMeng-NOAA  Sure.  I am going to test one case.

**Comment by wzzheng90** [comment]
I generated the 48-h model history files for the UPP testing with adding 3 fields:

    wind10mmax, u10mmax and v10mmax

    /lfs/h2/emc/stmp/weizhong.zheng/HR3_SFS_C96/COMROOT/hr3_2022090100_SFS/gfs.20220901/00/model_data/atmos/history

Please check.  Thanks.

**Comment by WenMeng-NOAA** [comment]
> I generated the 48-h model history files for the UPP testing with adding 3 fields:
> 
> ```
> wind10mmax, u10mmax and v10mmax
> 
> /lfs/h2/emc/stmp/weizhong.zheng/HR3_SFS_C96/COMROOT/hr3_2022090100_SFS/gfs.20220901/00/model_data/atmos/history
> ```
> 
> Please check. Thanks.

@wzzheng90 The model history files look good for me. Thanks!

@KarinaAsmar-NOAA Please working on the UPP updates to read in new fields "u10_max", "v10_max" and "wind10m_max" and write in grib2.

**Comment by KarinaAsmar-NOAA** [comment]
> > I generated the 48-h model history files for the UPP testing with adding 3 fields:
> > ```
> > wind10mmax, u10mmax and v10mmax
> > 
> > /lfs/h2/emc/stmp/weizhong.zheng/HR3_SFS_C96/COMROOT/hr3_2022090100_SFS/gfs.20220901/00/model_data/atmos/history
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please check. Thanks.
> 
> @wzzheng90 The model history files look good for me. Thanks!
> 
> @KarinaAsmar-NOAA Please working on the UPP updates to read in new fields "u10_max", "v10_max" and "wind10m_max" and write in grib2.

Thanks @wzzheng90 for generating the files. @WenMeng-NOAA I'll update UPP to read these fields and notify when ready.

**Comment by KarinaAsmar-NOAA** [comment]
> I generated the 48-h model history files for the UPP testing with adding 3 fields:
> 
> ```
> wind10mmax, u10mmax and v10mmax
> 
> /lfs/h2/emc/stmp/weizhong.zheng/HR3_SFS_C96/COMROOT/hr3_2022090100_SFS/gfs.20220901/00/model_data/atmos/history
> ```
> 
> Please check. Thanks.

@wzzheng90 I can no longer access this directory. Would you please generate another copy that I can access? This time I'll make and keep a copy to avoid it being removed. Thanks.

**Comment by wzzheng90** [comment]
> > I generated the 48-h model history files for the UPP testing with adding 3 fields:
> > ```
> > wind10mmax, u10mmax and v10mmax
> > 
> > /lfs/h2/emc/stmp/weizhong.zheng/HR3_SFS_C96/COMROOT/hr3_2022090100_SFS/gfs.20220901/00/model_data/atmos/history
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please check. Thanks.
> 
> @wzzheng90 I can no longer access this directory. Would you please generate another copy that I can access? This time I'll make and keep a copy to avoid it being removed. Thanks.

@KarinaAsmar-NOAA  The files on stmp (WCOSS2) can not be kept for longer.  Anyway, I am going to generate them again, but it may take time.

**Comment by KarinaAsmar-NOAA** [comment]
> > > I generated the 48-h model history files for the UPP testing with adding 3 fields:
> > > ```
> > > wind10mmax, u10mmax and v10mmax
> > > 
> > > /lfs/h2/emc/stmp/weizhong.zheng/HR3_SFS_C96/COMROOT/hr3_2022090100_SFS/gfs.20220901/00/model_data/atmos/history
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Please check. Thanks.
> > 
> > 
> > @wzzheng90 I can no longer access this directory. Would you please generate another copy that I can access? This time I'll make and keep a copy to avoid it being removed. Thanks.
> 
> @KarinaAsmar-NOAA The files on stmp (WCOSS2) can not be kept for longer. Anyway, I am going to generate them again, but it may take time.

Thanks @wzzheng90. It did not occur to me to make a copy. Please let me know when the new files are ready and I'll copy a few into my directories and keep for testing. Thanks!

**Comment by wzzheng90** [comment]
@KarinaAsmar-NOAA  I re-generated the 48-h model history files for the UPP testing with adding 3 fields (wind10mmax, u10mmax and v10mmax):
/lfs/h2/emc/stmp/weizhong.zheng/HR3_SFS_C96/COMROOT/hr3_2022090100_SFS/gfs.20220901/00/model_data/atmos/history

**Comment by KarinaAsmar-NOAA** [comment]
> 

> @KarinaAsmar-NOAA I re-generated the 48-h model history files for the UPP testing with adding 3 fields (wind10mmax, u10mmax and v10mmax): /lfs/h2/emc/stmp/weizhong.zheng/HR3_SFS_C96/COMROOT/hr3_2022090100_SFS/gfs.20220901/00/model_data/atmos/history

Thanks @wzzheng90. I'll make a copy for testing.

**Comment by KarinaAsmar-NOAA** [comment]
Comparison of max winds generated with SFS model vs. UPP is here: 
[Comparison of SFS Max Wind outputs.pptx](https://github.com/user-attachments/files/16680682/Comparison.of.SFS.Max.Wind.outputs.pptx). Please note that different tools were used for plotting (Python for model netCDF vs. GrADS for UPP GRIB2), therefore the plots are not standardized for comparison. They serve to assess overall similarity between max winds produced with SFS model and UPP.

**Comment by HuiyaChuang-NOAA** [comment]
> Comparison of max winds generated with SFS model vs. UPP is here: [Comparison of SFS Max Wind outputs.pptx](https://github.com/user-attachments/files/16680682/Comparison.of.SFS.Max.Wind.outputs.pptx). Please note that different tools were used for plotting (Python for model netCDF vs. GrADS for UPP GRIB2), therefore the plots are not standardized for comparison. They serve to assess overall similarity between max winds produced with SFS model and UPP.

@KarinaAsmar-NOAA your model and UPP output comparisons look good.  Did you make sure UPP output has appropriate time stamps?

**Comment by KarinaAsmar-NOAA** [comment]
> > Comparison of max winds generated with SFS model vs. UPP is here: [Comparison of SFS Max Wind outputs.pptx](https://github.com/user-attachments/files/16680682/Comparison.of.SFS.Max.Wind.outputs.pptx). Please note that different tools were used for plotting (Python for model netCDF vs. GrADS for UPP GRIB2), therefore the plots are not standardized for comparison. They serve to assess overall similarity between max winds produced with SFS model and UPP.
> 
> @KarinaAsmar-NOAA your model and UPP output comparisons look good. Did you make sure UPP output has appropriate time stamps?

@HuiyaChuang-NOAA Are you referring to the valid date and the forecast time as below? Or the actual time values for the time series?
![image](https://github.com/user-attachments/assets/1ea3bd3a-b36c-447d-9f5e-9d6fd96d5d37)

**Comment by WenMeng-NOAA** [comment]
@JesseMeng-NOAA @KarinaAsmar-NOAA It appears to me, that UPP IDs 422, 783 and 784 can be used to output max wind speed, and relevant U/V components in UPP code. There are no need to assign new UPP IDd or new grib2 name.
```
max wind speed: 422, grib2 name -- WIND
max wind speed U component: 783, grib2 name -- WAXUW
max wind peed V component 784: grib2 name -- WAXVW
```

**Comment by KarinaAsmar-NOAA** [comment]
> @JesseMeng-NOAA @KarinaAsmar-NOAA It appears to me, that UPP IDs 422, 783 and 784 can be used to output max wind speed, and relevant U/V components in UPP code. There are no need to assign new UPP IDd or new grib2 name.
> 
> ```
> max wind speed: 422, grib2 name -- WIND
> max wind speed U component: 783, grib2 name -- WAXUW
> max wind peed V component 784: grib2 name -- WAXVW
> ```

@WenMeng-NOAA Those IDs (422,783,784) read different [variable names](https://github.com/KarinaAsmar-NOAA/UPP/blob/6c88ef4b3536e4f5e27d5ba8fde67911bc284e67/sorc/ncep_post.fd/INITPOST.F#L1383) the netCDF files than the ones provided for SFS. Also, from the [documentation](https://github.com/KarinaAsmar-NOAA/UPP/blob/6c88ef4b3536e4f5e27d5ba8fde67911bc284e67/sorc/ncep_post.fd/VRBLS2D_mod.f#L142) and the [code](https://github.com/KarinaAsmar-NOAA/UPP/blob/6c88ef4b3536e4f5e27d5ba8fde67911bc284e67/sorc/ncep_post.fd/SURFCE.f#L2612) it seems that these IDs are meant for hourly products. An example of the GRIB2 product for 783 and 784 is below, which shows hourly products:

![image](https://github.com/user-attachments/assets/ad1967b9-3a97-4fdb-bff6-6c51ff1cfafa)

Do you suggest we try using these IDs for the 6-hourly max winds?

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA 

> max wind speed: 422, grib2 name -- WIND
> max wind speed U component: 783, grib2 name -- WAXUW
> max wind peed V component 784: grib2 name -- WAXVW

**Comment by WenMeng-NOAA** [comment]
@KarinaAsmar-NOAA You might modify these products in UPP to  be universal for all UFS-based model outputs (e.g. GFS, GEFS, SFS), rather than hard-wired to 6-hourly max.

**Comment by KarinaAsmar-NOAA** [comment]
> @KarinaAsmar-NOAA You might modify these products in UPP to be universal for all UFS-based model outputs (e.g. GFS, GEFS, SFS), rather than hard-wired to 6-hourly max.

@WenMeng-NOAA Ok I'll give that a try. Thanks!

**Comment by KarinaAsmar-NOAA** [comment]
@WenMeng-NOAA The branch has been updated to modify existing ids 422, 783, and 784 with ufs time buckets. Comparison of SFS model winds vs. UPP outputs is here: 
[Comparison.of.SFS.Max.Wind.outputs.pptx](https://github.com/user-attachments/files/16763393/Comparison.of.SFS.Max.Wind.outputs.pptx). The slides include a snapshot of the forecast times for 2 models with the new changes: 6-hourly for SFS and 1-hourly for HRRR.
