### ISSUE TITLE
Need update g2tmpl to 1.12.0 on CSPs

### ISSUE THREAD

**Issue by weihuang-jedi** [NOAA-EMC/UPP#989]
Can we update g2tmpl within spack-stack on CSPs to 1.12.0?

The current develop branch on CSPs has problem to compile:

+ ./compile_upp.sh
Building for machine noaacloud, compiler intel
Lmod has detected the following error:  The following module(s) are unknown: "g2tmpl/1.12.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "g2tmpl/1.12.0"

Also make sure that all modulefiles written in TCL start with the string #%Module

Executing this command requires loading "g2tmpl/1.12.0" which failed while processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    upp_common       /contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/modulefiles/upp_common.lua
    noaacloud        /contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/modulefiles/noaacloud.lua

Current on CSPs, we have:
[Wei.Huang@wei1epic2azure3slurm-85 c48atm]$ module spider g2tmpl

-----------------------------------------------------------------------------------------------------------------------------------------------------------
  g2tmpl: g2tmpl/1.10.2

If we force to use g2tmpl/1.10.2, we got error:
/contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/sorc/ncep_post.fd/grib2_module.f(502): error #6580: Name in only-list does not exist or is not accessible.   [G2SEC4_TEMP9]
                           g2sec4_temp0,g2sec4_temp8,g2sec4_temp9,g2sec4_temp44,         &
-----------------------------------------------------^
/contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/sorc/ncep_post.fd/grib2_module.f(503): error #6580: Name in only-list does not exist or is not accessible.   [G2SEC4_TEMP46]
                           g2sec4_temp46,g2sec4_temp48,g2sec5_temp0,g2sec5_temp2,        &
---------------------------^
compilation aborted for /contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/sorc/ncep_post.fd/grib2_module.f (code 1)
make[2]: *** [sorc/ncep_post.fd/CMakeFiles/upp.dir/grib2_module.f.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [sorc/ncep_post.fd/CMakeFiles/upp.dir/all] Error 2
make: *** [all] Error 2

**Comment by WenMeng-NOAA** [comment]
@weihuang-jedi You should send the request to the spack-stack repository
https://github.com/JCSDA/spack-stack/issues

**Comment by FernandoAndrade-NOAA** [comment]
This issue is being tracked and worked on in [spack-stack #1183](https://github.com/JCSDA/spack-stack/issues/1183), I will go ahead and close this out in the meantime. Please let me know if this needs to stay open or if a new issue is required once new configurations are set up after the spack-stack issue resolution. Thank you.
