### ISSUE TITLE
UPP fails to build on Gaea at head of develop

### ISSUE THREAD

**Issue by DavidBurrows-NCO** [NOAA-EMC/UPP#992]
After #917 was merged, compiling UPP on Gaea now fails with:
```
Lmod has detected the following error:  The following module(s) are unknown:
"stack-python/3.10.13"
```
I notice that about half the modules load python.  I tested compiling without loading python, and it's successful.

**Comment by DavidBurrows-NCO** [comment]
Thank you @WenMeng-NOAA @FernandoAndrade-NOAA for such a quick response. I just cloned and tested a build on Gaea. Looks good.

**Comment by WenMeng-NOAA** [comment]
> Thank you @WenMeng-NOAA @FernandoAndrade-NOAA for such a quick response. I just cloned and tested a build on Gaea. Looks good.

@DavidBurrows-NCO Thanks for confirming. We will include this update in the UFS PR [#2326](https://github.com/ufs-community/ufs-weather-model/pull/2326/commits).

**Comment by DavidBurrows-NCO** [comment]
@WenMeng-NOAA Great to hear...thanks
