### ISSUE TITLE
Testing new params_grib2_tbl_new file from GRIB2 v33.0 update

### ISSUE THREAD

**Issue by AndrewBenjamin-NOAA** [NOAA-EMC/UPP#999]
Testing of updated params_grib2_tbl_new file is needed before a PR can be submitted to update the develop branch of the g2tmpl.
Test files can be found on the dev machine of WCOSS2: /lfs/h2/emc/vpppg/noscrub/andrew.benjamin/NCEPLIBS-g2tmpl/src

*This will not impact the current install work of g2tmpl and g2 for spack_stack and WCOSS2. This is strictly on the develop branch of g2tmpl.

**Comment by WenMeng-NOAA** [comment]
@AndrewBenjamin-NOAA The UPP RTs indicate no changes with your new params_grib2_tbl_new file. From the UPP perspective, the new version of "params_grib2_tbl_new" is good to go.

**Comment by AndrewBenjamin-NOAA** [comment]
PR submitted to g2tmpl: NOAA-EMC/NCEPLIBS-g2tmpl/pull/139
